### ISSUE TITLE
checking for iconv_open() in iconv.h... no

### ISSUE THREAD

**Issue by joshuairl** [rails-sqlserver/tiny_tds#104]
I don't understand this...
I've debugged extconf.rb and only included my lib / header paths that I KNOW are there...
and I run ruby extconf.rb while `puts dir_config('iconv',   HEADER_DIRS, LIB_DIRS)` and `puts "lookup in " + "'#{HEADER_DIRS.join("','")}'" + " " + "'#{LIB_DIRS.join("','")}'"` and they are returning correct paths.

I open up iconv.h and I can find iconv_open() inside that file... what am I missing here?

This is running via MAC OS X 10.8 with xcode cli tools, and freetds 0.91 installed via homebrew.  Also, got libiconv installed via homebrew at 1.14.

**Comment by metaskills** [comment]
Pruning old issue.
