### ISSUE TITLE
README.md : stored procedure example

### ISSUE THREAD

**Issue by beho** [rails-sqlserver/tiny_tds#119]
At the end of the section **TinyTds::Result Usage** is the example for a getting return value of called stored procedure:

```
client.return_code  # => nil

result = client.execute("EXEC tinytds_TestReturnCodes")
result.return_code  # => 420
client.return_code  # => 420
```

Such code does not work for me because a call to `Result#do` is missing. Thus if the example is supposed to be complete then it should be:

```
client.return_code  # => nil

result = client.execute("EXEC tinytds_TestReturnCodes")
result.do
result.return_code  # => 420
client.return_code  # => 420
```

I admit that I'm new to tiny_tds so its possible that I'm doing something wrong and in that case I'd appreciate an advice.

**Comment by abigailvo** [comment]
Hi @metaskills @beho I've been running to the same issue and can't fix it. I've added the result.do right after exec line but nothing happens, no error and SP isn't executed too. May I ask how you fixed it?

**Comment by aharpervc** [comment]
@abigailvo this is a very old issue. If you're having a problem, please open a new issue & fill out the issue template appropriately, and also try to provide a specific reproducible example.
