### ISSUE TITLE
tiny_tds does not work on ruby 2.2

### ISSUE THREAD

**Issue by jeremyevans** [rails-sqlserver/tiny_tds#176]
Ruby 2.2 removes `rb_thread_blocking_region`, which tiny_tds uses.  Are there plans to update tiny_tds to work with ruby 2.2?

**Comment by metaskills** [comment]
#181 solved this and 0.6.3/master has the fix.

**Comment by kronn** [comment]
I could not find the `0.6.3`-tag. Is there a release planned including this fix?

**Comment by metaskills** [comment]
There is no git tag, the 0.6.3 is master now since it is in active development till a release.

**Comment by kronn** [comment]
Okay, then I just stick with master (which is working for us with ruby 2.2.2). thanks.

**Comment by andretf** [comment]
It there a new release on sight?

**Comment by metaskills** [comment]
Pre-releases are not set to create git tags. Till we release the official v0.7.0 in a few days, you can use the 0.6.3.rc2 gem that was pushed to rubygems.

**Comment by andretf** [comment]
I've seen now that you released 0.7. Thanks!
