### ISSUE TITLE
'argument out of range' error on Linux x86_64

### ISSUE THREAD

**Issue by noahgibbs** [rails-sqlserver/tiny_tds#182]
When trying to query a datetime column with activerecord-sqlserver-adapter, I get an 'argument out of range' error on a CentOS x86_64 server running FreeTDS 0.91.

The error doesn't occur with FreeTDS tsql on the same query. It reads the values without a hitch. It *does* occur in irb where I just do this:

require 'tiny_tds'
client = TinyTds::Client.new username: 'user', password: 'pwd', host: 'my-host.onlive.net', database: 'box'
result = client.execute "select email, email_campaign from ipost_automation where email_sent_datetime >= '2015-01-04'"
result.to_a

So I'm pretty sure it's a tiny_tds error, not FreeTDS. Here's the output of 'tsql -C':

Compile-time settings (established with the "configure" script)
                            Version: freetds v0.91
             freetds.conf directory: /etc
     MS db-lib source compatibility: yes
        Sybase binary compatibility: yes
                      Thread safety: yes
                      iconv library: yes
                        TDS version: 4.2
                              iODBC: no
                           unixodbc: yes
              SSPI "trusted" logins: no
                           Kerberos: yes

The TDS version there looked suspect, but running my script with "TDSVER=7.1" in front doesn't change anything.

This argument error seems to have started happening at approximately the new year in 2015 -- one week ago, as I write this.

The error doesn't occur on Mac OS X for me, just on Linux with the same code.

I have tried this with tiny_tds 0.6.1 and 0.6.2. Both have the same error. I have tried it with activerecord-sqlserver-adapter 3.2.12 and 4.1.0 (plus with only tiny_tds in irb, as above), though I don't think the ActiveRecord adapter is the problem.

**Comment by wbond** [comment]
Do you have a backtrace for the error?

**Comment by noahgibbs** [comment]
Yes, though it's not terribly useful. In the irb listing it dies directly in .to_a (presumably in the C extension). Here's where it dies in my script using ActiveRecord:

/opt/cryptic_ipost_sync/vendor/bundle/ruby/1.9.1/gems/activerecord-sqlserver-adapter-4.1.0/lib/active_record/connection_adapters/sqlserver/database_statements.rb:423:in `utc': ArgumentError: argument out of range: EXEC sp_executesql N'SELECT [ipost_automation].* FROM [ipost_automation] WHERE [ipost_automation].[email_sent_datetime] IS NULL' (ActiveRecord::StatementInvalid)
	from /opt/cryptic_ipost_sync/vendor/bundle/ruby/1.9.1/gems/activerecord-sqlserver-adapter-4.1.0/lib/active_record/connection_adapters/sqlserver/database_statements.rb:423:in `each'
	from /opt/cryptic_ipost_sync/vendor/bundle/ruby/1.9.1/gems/activerecord-sqlserver-adapter-4.1.0/lib/active_record/connection_adapters/sqlserver/database_statements.rb:423:in `handle_to_names_and_values_dblib'
	from /opt/cryptic_ipost_sync/vendor/bundle/ruby/1.9.1/gems/activerecord-sqlserver-adapter-4.1.0/lib/active_record/connection_adapters/sqlserver/database_statements.rb:412:in `handle_to_names_and_values'
	from /opt/cryptic_ipost_sync/vendor/bundle/ruby/1.9.1/gems/activerecord-sqlserver-adapter-4.1.0/lib/active_record/connection_adapters/sqlserver/database_statements.rb:385:in `_raw_select'
	from /opt/cryptic_ipost_sync/vendor/bundle/ruby/1.9.1/gems/activerecord-sqlserver-adapter-4.1.0/lib/active_record/connection_adapters/sqlserver/database_statements.rb:380:in `block in raw_select'
	from /opt/cryptic_ipost_sync/vendor/bundle/ruby/1.9.1/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract_adapter.rb:373:in `block in log'
	from /opt/cryptic_ipost_sync/vendor/bundle/ruby/1.9.1/gems/activesupport-4.1.8/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
	from /opt/cryptic_ipost_sync/vendor/bundle/ruby/1.9.1/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract_adapter.rb:367:in `log'
	from /opt/cryptic_ipost_sync/vendor/bundle/ruby/1.9.1/gems/activerecord-sqlserver-adapter-4.1.0/lib/active_record/connection_adapters/sqlserver/database_statements.rb:380:in `raw_select'
	from /opt/cryptic_ipost_sync/vendor/bundle/ruby/1.9.1/gems/activerecord-sqlserver-adapter-4.1.0/lib/active_record/connection_adapters/sqlserver/database_statements.rb:363:in `do_exec_query'
	from /opt/cryptic_ipost_sync/vendor/bundle/ruby/1.9.1/gems/activerecord-sqlserver-adapter-4.1.0/lib/active_record/connection_adapters/sqlserver/database_statements.rb:24:in `exec_query'
	from /opt/cryptic_ipost_sync/vendor/bundle/ruby/1.9.1/gems/activerecord-sqlserver-adapter-4.1.0/lib/active_record/connection_adapters/sqlserver/database_statements.rb:295:in `select'
	from /opt/cryptic_ipost_sync/vendor/bundle/ruby/1.9.1/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/database_statements.rb:24:in `select_all'
	from /opt/cryptic_ipost_sync/vendor/bundle/ruby/1.9.1/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/query_cache.rb:70:in `select_all'
	from /opt/cryptic_ipost_sync/vendor/bundle/ruby/1.9.1/gems/activerecord-4.1.8/lib/active_record/querying.rb:39:in `find_by_sql'
	from /opt/cryptic_ipost_sync/vendor/bundle/ruby/1.9.1/gems/activerecord-4.1.8/lib/active_record/relation.rb:611:in `exec_queries'
	from /opt/cryptic_ipost_sync/vendor/bundle/ruby/1.9.1/gems/activerecord-4.1.8/lib/active_record/relation.rb:493:in `load'
	from /opt/cryptic_ipost_sync/vendor/bundle/ruby/1.9.1/gems/activerecord-4.1.8/lib/active_record/relation.rb:238:in `to_a'
	from bin/ipost-sync:98:in `<main>'

**Comment by wbond** [comment]
Can you post the full irb session with backtrace?

Looking at that backtrace, it points to https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/blob/4-1-stable/lib/active_record/connection_adapters/sqlserver/database_statements.rb#L419-L423, which seems to indicate that your active record default timezone may not be compatible with FreeTDS.

**Comment by noahgibbs** [comment]
Sure, here's the full irb transcript. bin/irb is a wrapper that sets a local Gemfile and does a bundle exec, which is why you're seeing vendored paths to gems in the transcript above.

[mca-0-3-0-12 cryptic_ipost_sync]$ bin/irb
1.9.3p327 :001 > require "tiny_tds"
 => true
1.9.3p327 :002 > client = TinyTds::Client.new username: 'talend', password: 'talend', host: 'marketing-sql01.onlive.net', database: 'box'
 => #<TinyTds::Client:0x0000001846e368>
1.9.3p327 :003 > result = client.execute "select * from ipost_automation where email_sent_datetime >= '2015-01-04'"
 => #<TinyTds::Result:0x00000018454198>
1.9.3p327 :004 > result.to_a
ArgumentError: argument out of range
	from (irb):4:in `local'
	from (irb):4:in `each'
	from (irb):4:in `to_a'
	from (irb):4
	from /usr/local/rvm/rubies/ruby-1.9.3-p327/bin/irb:16:in `<main>'
1.9.3p327 :005 >

**Comment by noahgibbs** [comment]
Sorry - deleted previous comment because it included sensitive info :-(

Sure. bin/irb is a script that just sets a Gemfile and does a bundle exec irb, which is why you're seeing vendored gem paths in the transcript above.

[mca-0-3-0-12 cryptic_ipost_sync]$ bin/irb
1.9.3p327 :001 > require "tiny_tds"
 => true
1.9.3p327 :002 > client = TinyTds::Client.new username: 'username', password: 'pw', host: 'my-host.onlive.net', database: 'box'
 => #<TinyTds::Client:0x0000001846e368>
1.9.3p327 :003 > result = client.execute "select * from ipost_automation where email_sent_datetime >= '2015-01-04'"
 => #<TinyTds::Result:0x00000018454198>
1.9.3p327 :004 > result.to_a
ArgumentError: argument out of range
	from (irb):4:in `local'
	from (irb):4:in `each'
	from (irb):4:in `to_a'
	from (irb):4
	from /usr/local/rvm/rubies/ruby-1.9.3-p327/bin/irb:16:in `<main>'
1.9.3p327 :005 >

**Comment by wbond** [comment]
What are the actual raw values in those rows? I wonder if the Rails date/time parsing library is having trouble with one of the date/times?

**Comment by wbond** [comment]
Perhaps you could try filtering rows via your where clause to figure out what value is having trouble?

**Comment by wbond** [comment]
My guess is some code in here is the culprit: https://github.com/rails-sqlserver/tiny_tds/blob/master/ext/tiny_tds/result.c#L277-317

**Comment by noahgibbs** [comment]
I've tried several values of the where clause, and it seems to be having trouble with a lot of them, possibly all of them. Although I can't be sure it's the specific datetime column in question. I'll see if I can narrow it down.

I agree, that seems like an obvious area of the code to potentially cause the problem.

**Comment by noahgibbs** [comment]
Nope, never mind. If I select only the email_sent_datetime column I can still reproduce the problem. I'll try to narrow it down to some more specific values.

**Comment by noahgibbs** [comment]
Okay. I can select exactly one value in exactly one column, the datetime "Jan 7 2015 16:58:04:600", and get the same error.

FreeTDS tsql can select and show the value just fine, tiny_tds gives the argument error.

**Comment by wbond** [comment]
The only way I can get that to fail is to adjust one of the numbers to be outside a normal range. I wonder if there is some sort of default date formatting going on that is messing it up?

```ruby
# Works
Time.local(2015, 1, 7, 16, 58, 4, 600*1000)
# Fails
Time.local(2015, 0, 7, 16, 58, 4, 600*1000)
```

**Comment by noahgibbs** [comment]
I'm not finding any environment variables set related to time or time zones. So there should be no unusual configuration.

**Comment by noahgibbs** [comment]
We're using SQL Server 2012 R 2 if that makes a difference. This is just a datetime column.

**Comment by metaskills** [comment]
> MS db-lib source compatibility: yes
> Sybase binary compatibility: yes

Aside, these need not be configured. I know our README says that they can be and ignored. But just wanted to mention that. See [here](https://github.com/rails-sqlserver/tiny_tds#freetds-compatibility--configuration) on the last bullet.

> TDS version: 4.2

Yea, we mention this in the [same section](https://github.com/rails-sqlserver/tiny_tds#freetds-compatibility--configuration) and I doubt it is the cause, but it is worth trying to recompile using `--with-tdsver=7.1` just to check.

Onward, your error has a history with us. [Check out these issues](https://github.com/rails-sqlserver/tiny_tds/issues?q=is%3Aissue+argument+out+of+range) for some back story. I'll read to job my own memory but I think most relate to a certain bug in a certain ruby version and arch on time ranges. It was one reason we used to check and return a `DateTime` object back vs the more acceptable `Time`.

**Comment by metaskills** [comment]
@noahgibbs Please let me know if you can try the configure args I posted and if you can read thru the old issues... newest to oldest first. There is some helpful info in there. Could even be the FreeTDS linked on CentOS.

**Comment by metaskills** [comment]
Any updates on this?

**Comment by noahgibbs** [comment]
Afraid I haven't had time to rebuild this -- been busy with other stuff at work recently, and I found a workaround for our script in question.

**Comment by masonjm** [comment]
Having the same issue, so I'll hijack this one :). Running this code:

    client = TinyTds::Client.new username: "****", password: "****", host: "****", database: "****"
    result = client.execute "select convert(datetime, '2009-01-19 21:14:36.440')"
    result.each { |row| puts row }

Give this error:

    ArgumentError: argument out of range
      from (irb):45:in `local'
      from (irb):45:in `each'
      from (irb):45
      from /emf/sui/shared/bundle/ruby/2.0.0/gems/railties-4.1.9/lib/rails/commands/console.rb:90:in `start'
      from /emf/sui/shared/bundle/ruby/2.0.0/gems/railties-4.1.9/lib/rails/commands/console.rb:9:in `start'
      from /emf/sui/shared/bundle/ruby/2.0.0/gems/railties-4.1.9/lib/rails/commands/commands_tasks.rb:69:in `console'
      from /emf/sui/shared/bundle/ruby/2.0.0/gems/railties-4.1.9/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
      from /emf/sui/shared/bundle/ruby/2.0.0/gems/railties-4.1.9/lib/rails/commands.rb:17:in `<top (required)>'
      from script/rails:6:in `require'
      from script/rails:6:in `<main>'

This is with tiny_tds 0.6.2 and freetds 0.91.103 configured with `--with-tdsver-7.1 --disable-odbc`.

**Comment by masonjm** [comment]
Upgrading Ruby to 2.1.5 resolved this issue for us.
