### ISSUE TITLE
Connection closed

### ISSUE THREAD

**Issue by cbezares** [rails-sqlserver/tiny_tds#183]
My connection is closed just after client is created, and this happens only when I use `:dataserver` instead `:host`

**Works (external server):**

     client = TinyTds::Client.new username: 'sa', password: 'secret', host: '192.168.0.74', database: 'MyDB'

**Doesn't work (with local server connection is closed):**

     client = TinyTds::Client.new username: 'sa', password: 'secret', dataserver: 'MYNTBK\SQLEXPRESS', database: 'MyDB'

**Error trace:**
    
    irb(main):001:0> client = TinyTds::Client.new username: 'sa', password: 'secret', dataserver: 'MYNTBK\SQLEXPRESS'
    => #<TinyTds::Client:0x564a530>
    irb(main):002:0> client.execute('USE MyDB')
    TinyTds::Error: closed connection
        from (irb):7:in `execute'
        from (irb):7
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/railties-4.1.0/lib/rails/commands/console.rb:90:in `start'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/railties-4.1.0/lib/rails/commands/console.rb:9:in `start'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/railties-4.1.0/lib/rails/commands/commands_tasks.rb:69:in `console'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/railties-4.1.0/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/railties-4.1.0/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'

**Configuration file:**

    development:
        adapter: sqlserver
        dataserver: MYNTBK\SQLEXPRESS
        database: MyDB
        username: sa
        password: secret

I'm working on Windows 7 with MS SQL Server 2005 and Rails 4.1.0

Thanks

**Comment by metaskills** [comment]
Do you have an entry in freetds conf for that name of that dataserver? Or are you relying on `MYNTBK` resolving to a host name?

**Comment by cbezares** [comment]
I dont' have a freetds conf file, actually I didn't install FreeTDS for Windows. Is this necessary to local server connection?

**Comment by metaskills** [comment]
If you are using the precompiled Windows binary then FreeTDS is built into the gem using [these](https://github.com/rails-sqlserver/tiny_tds/blob/master/tasks/ports.rake#L55) defaults. That means you can make a conf if needed in that directory and do those fancy things if needed. For now, just ignore since it sounds like this is all new to you.

That said, it sounds like you are indeed relying on `MYNTBK` to resolve DNS wise for you local machine? Something else? The reason it is hard for me to debug these things could be due to how other factors outside of this gem treat that name/pipe. Did you see my recommendation on the [README](https://github.com/rails-sqlserver/tiny_tds#tinytdsclient-usage) about dataserver?

**Comment by cbezares** [comment]
Thanks @metaskills for your answers and your time.

The problem was the SQL Server service port. I was using default port 1433 but in my case (i don't know why) the service is using port 59532 to listen. So finally my freetds conf file that works is the following:

    [global]
        # TDS protocol version
        tds version = 8.0
        client charset = UTF-8
        dump file = C:\Site\freeTDS.log
        text size = 64512

    [MYNTBK\SQLEXPRESS]
        host = localhost
        port = 59532
        # use ntlmv2 = yes
        encryption = request

And these configuration allows me to do the following with no "connection closed" error after client connection:

    client = TinyTds::Client.new username: 'sa', password: 'secret', dataserver: 'MYNTBK\SQLEXPRESS'

Sorry for my english and I hope this will be helpful for those that assume that their SQL Server service port is 1433.

**Comment by metaskills** [comment]
Ah yeah, the whole named instances things are ways to run on dynamic ports and keep you from thinking about it. The login negotiation is supposed to figure it out but I think FreeTDS has issue with it. I would just use a simple name like "myss2014" or "development" or something and just get rid of those slashes. Glad it is working for you too!
