### ISSUE TITLE
The same issue as issue #79. (DBPROCESS is dead).

### ISSUE THREAD

**Issue by BMahabir** [rails-sqlserver/tiny_tds#185]
https://github.com/rails-sqlserver/tiny_tds/issues/79

Hi there, I do not want to duplicate issues already present, but my team & I really need an answer to this problem that continues to occur on our production environment.  Example logging line from one of our master logs : 

```
ERROR Accounts Logger: #<ActiveRecord::LostConnection: TinyTds::Error: DBPROCESS is dead or not enabled: SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE' ORDER BY TABLE_NAME>
```

We really have no idea why this keeps happening, we have tried to modify the database.yml by increasing the pool count and the timeout value but to no avail.  Another team member & I also dug into the source code for tiny_tds and noticed that the code changes in issue #79 above are NOT present in our install of tiny_tds, currently version 0.6.2 (at least they weren't in the .c file locally).  We thought that maybe upgrading to 0.6.3 might help, but apparently it is not actually released yet.

Please let us know how to proceed; thanks very much for your time.

**Comment by metaskills** [comment]
What platform OS are you on and what version of Ruby?

**Comment by BMahabir** [comment]
Ruby 1.9.3p484
Windows Server 2012 R2 Standard

Hope it helps.

**Comment by metaskills** [comment]
What platform is the one that TinyTDS is running on? Windows too?

**Comment by BMahabir** [comment]
I don't get it, why would they be different?  tiny_tds is a gem for Rails... which is what I'm running ruby on (???)

**Comment by metaskills** [comment]
Most developers I know use some form of UNIX. I myself use OS X and its is more common that you might think that Ruby/TinyTDS runs on an entirely different platform as the database. 

The reason I asked is that I wanted to gauge if you ha the capability to install the updated TinyTDS 0.6.3 in our master branch now. Which is much more easy on a POSIX system than Windows. In lieu of that, you are at the mercy till we find time to build gems for you and it slows down the process. Aside, the master branch is not ready to build static gems yet, we have some work todo.. cc @wbond that mess is likely my fault. 

@BMahabir I've seen reports by others that 1.9.3 might be the issue here. Do you have the ability to user a higher Ruby version?

**Comment by BMahabir** [comment]
Yep, I understand, I'm a noob developer for not using UNIX :-)  Although I didn't have a choice in the matter for our platform.  And YES ruby/tiny_tds IS running on an entirely different platform than the database (the DB is on another machine in the network, but it's also a Windows install, a Windows Server 2003 box).

So I was right?  0.6.3 would be the answer for me?  If so that's fine, and I'm happy to wait for the new gem build (days or weeks, not months right?), 'cause I'm not about to go back to the rest of the dev team and tell them we have to switch platforms just 'cause tiny_tds doesn't work.

**Comment by metaskills** [comment]
> Yep, I understand, I'm a noob developer for not using UNIX :-) 

I did not say that at all nor meat to imply. I was simply going to communicate that if you were on a system where you can install FreeTDS then build from master `rake build TINYTDS_SKIP_PORTS=true` that you might want to explore that. If that's something you are up for, cool. But I can not give any advice on how to do this on Windows.

> So I was right? 0.6.3 would be the answer for me?

I honestly do not know. Like I was saying, I have seen reports of Ruby 2.1 fixing issues for some people.

**Comment by neongrau** [comment]
I've tried upgrading to ruby 2.1.5 and 2.0.0 because of this. Problem was that with both these versions my Rails App became so unstable i have the whole ruby process crashing long before i could verify that it helps in any way to fix the DB connection losses :(

**Comment by YvesR** [comment]
You can close #177 and link it to this ticket.
We facing the same issue on the same platform. 
If I can help in any tests please tell, but as I am failing to compile own FreeTDS version on windows myself at the moment I will need some advise then I fear.

**Comment by neongrau** [comment]
I've done some more testing with Ruby 2.1.5 32bit as well as the 64bit from rubyinstaller.org.
During my test runs i've never seen any DB related problems which always came up on 1.9.3 after a little while.
BUT 2.1.5 and also 2.0.0 are leaking memory like water at the Niagara Falls :(
After a couple hours with just a single Browser doing a couple of XHR requests memory rose until the rubyw.exe just died. Even without any client accessing, just by starting a thin server under any 2.x i can see 10-50 KB of memory increase per second.

With 1.9.3 memory was stable but connections are dropping left and right.
TBH, i'm pretty much out of ideas right now.

**Comment by metaskills** [comment]
So I hear this is not a TinyTDS issue per se, at least not one that I can account for. I have run the tests on 1.9.3 and they pass. My advice would be to troubleshoot the memory leaks. Is it your code or framework code? You never did mention what Rails version you are on?

**Comment by neongrau** [comment]
The connection issues happen with ruby 1.9.3p385 and Rails 3.2.12.
The memory leaks now were with Rails 3.2.21 (from what i learned that is reuqired to run with Ruby >=2.0). Do you have any hint on how to start debugging for such memory leaks on Windows?
As i said with 1.9.3 and the slightly older Rails minor version i can't see memory leaking in a such drastic way (memory goes slightly up over time but wouldn't become an issue even after weeks of uptime).
I'm also currently planning to migrate the app to Rails 4.2. but this will take quite some time before i can start testing.

**Comment by metaskills** [comment]
> how to start debugging for such memory leaks on Windows

No, but I would approach it first as not a platform bug and Google around.

**Comment by neongrau** [comment]
My tests so far show that when i create a vanilla rails app and fire it up with thin under 2.0.0p598 x64 i see the exact same memore leaking behavior just that there is not a single byte of code added by me. And also not even set up with SQL-Server just default sqlite. Once done on a Windows Server 2008 with Rails 4.2+thin 1.6.1 and on a Windows Server 2012 with Rails 3.2.21 and thin 1.6.3.
So does this look like a platform bug or not?
*sigh*
- 1.9.3 buggy with unstable SQL connections
- 2.0.0 and 2.1.5 leaking memory until the ruby processes die
not sure if i should cry, laugh or smash random things into pieces /o\

**Comment by metaskills** [comment]
It does sound like a platform bug, maybe @luislavena might know some details of if this is a known issue or not.

**Comment by neongrau** [comment]
Now i've narrowed it down a bit more. After testing with webrick i started suspecting Thin having the leak, and now i downgraded the Eventmachine gem. During my tests on friday i had the brand spanking new eventmachine-1.0.6 installed and now after downgrading to 1.0.4 the ruby processes seem memory stable (at least when not serving any requests).
