### ISSUE TITLE
Connecting to SQL Compact Edition

### ISSUE THREAD

**Issue by jwoertink** [rails-sqlserver/tiny_tds#186]
I'm having issues trying to connect to SQLExpress Compact Edition 4.0. Using version '0.6.2'. I keep getting 
```text
TinyTds::Error: Unable to connect: Adaptive Server is unavailable or does not exist
```
I'm sure I'm just doing this wrong, but when the .NET guys connect to this database, they use
```xml
<add value="Data Source=C:\Program Files (x86)\Company\Alice\Local\AliceLocal.sdf" key="AliceConnectionString"/>
```
The code I'm trying is
```ruby
client = TinyTds::Client.new(username: 'a', password: 'a', host: '172.16.1.160', database: 'AliceLocal.sdf')
```

Does TinyTds support this and I'm just doing it wrong?

**Comment by metaskills** [comment]
Is the DB on the default port of 1433? Most named instances are not.

**Comment by jwoertink** [comment]
I don't think so. I didn't find much in the way of google searches for ruby, so I started looking at other languages. I'm thinking it's not possible because it might need to use the `WIN32OLE` object. My issue is that I have a rails app deployed on a linux box inside virtualbox trying to connect to this Sql CE 4.0 on the windows host machine. 

I [came across this](http://stackoverflow.com/questions/168240/is-it-possible-to-connect-php-to-sql-server-compact-edition) where I guy used the php COM object to connect, but it only works from windows. 
 I also [found this](http://rubyonwindows.blogspot.com/2007/06/using-ruby-ado-to-work-with-ms-access.html) which is for MS Access, but I think sql ce runs the same way. Thoughts?

**Comment by metaskills** [comment]
If you have a database running on a host/port, you can use Ruby and hence TinyTDS, period.

**Comment by jwoertink** [comment]
Right. I'm not very familiar with any of these SQL server stuff, but from what I understand, SQL C.E. isn't running on a host and port. It's just a flat file. I may be wrong, but luckily they said we can use the normal sql server which does have a host and port. I'll close this out for now though. Thanks for the help!

**Comment by metaskills** [comment]
> host and port. It's just a flat file

Oh good lord. I totally missed that :) have fun. Ping us if you need anything.
