### ISSUE TITLE
undefined symbol rb_thread_blocking_region

### ISSUE THREAD

**Issue by xangelux** [rails-sqlserver/tiny_tds#187]
I try to use rake db:schema:dump and the command fails with the error:

ruby: symbol lookup error: ~/.rvm/gems/ruby-2.2.0@mfc/extensions/x86_64-linux/2.2.0/tiny_tds-0.6.2/tiny_tds/tiny_tds.so: undefined symbol: rb_thread_blocking_region

I've been searching all over the world... in google... and found the rb_thread_blocking_region was deprecated in a ruby update (https://github.com/ruby/ruby/blob/1c87fee3166c5208e92f1b7779507dd52c3087e1/NEWS#L282) and it has a "replacement" with the method  rb_thread_call_without_gvl. I'm trying to convience my coworkers that ruby is a tool to consider to migrate a system connected to SQLServer, should I try something else? or can this be fixed easly?

**Comment by metaskills** [comment]
This duplicates #176. The change for 2.2 compatibility is in master and not yet released. Bundle to that or build you own native gem if needed using the readme instructions. Cheers.

**Comment by xangelux** [comment]
thanks, didn't see that, I'll try to bundle so the case doesn't go cold and my coworkers won't try python first

**Comment by metaskills** [comment]
Word :) I'll get out gem releases when I find time to make finish up a few others issues and fix the rake-compiler stuff for Windows.
