### ISSUE TITLE
tiny_tds 0.6.2 symbol lookup error with ruby 2.2.0

### ISSUE THREAD

**Issue by daveramachandran** [rails-sqlserver/tiny_tds#188]
symbol lookup error: /usr/local/rvm/gems/ruby-2.2.0/extensions/x86_64-linux/2.2.0/tiny_tds-0.6.2/tiny_tds/tiny_tds.so: undefined symbol: rb_thread_blocking_region

on ubuntu 12.04

FreeTDS Version: 0.91

I see that the issue has been resolved in 0.6.3, but has it been released..?

**Comment by metaskills** [comment]
No, you have to bundle to master

**Comment by metaskills** [comment]
I have pushed 0.6.3.rc1 which is POSIX only. No pre-build win binaries now. HTH!
