### ISSUE TITLE
Transaction rollback fails with "use_output_insert == false" if a SQL error happened during the transaction

### ISSUE THREAD

**Issue by naag** [rails-sqlserver/tiny_tds#189]
We're running a Rails 4.2.0 app with activerecord-sqlserver-adapter 4.2.2 and SQL Server 2012 and have run into an issue with both emoji encoding and transaction rollback in that scenario. Trying to create a simple record with an emoji fails due to TinyTDS character conversion, but the transaction rollback also fails when using `ActiveRecord::ConnectionAdapters::SQLServerAdapter.use_output_inserted = true
`.

Example:

```
ActiveRecord::ConnectionAdapters::SQLServerAdapter.use_output_inserted = false
Emoji.create!(text: "😢")
```

This fails with these error messages:

```
Started GET "/encoding/really_bad" for 172.17.42.1 at 2015-02-16 15:37:49 +0000
Processing by EncodingController#really_bad as */*
  SQL (1.4ms)  BEGIN TRANSACTION
  SQL (0.3ms)  EXEC sp_executesql N'INSERT INTO [emojis] ([text]) VALUES (@0); SELECT CAST(SCOPE_IDENTITY() AS bigint) AS Ident', N'@0 nvarchar(4000)', @0 = N'😢'  [["text", "😢"]]
TinyTds::Error: Error converting characters into server's character set. Some character(s) could not be converted: EXEC sp_executesql N'INSERT INTO [emojis] ([text]) VALUES (@0); SELECT CAST(SCOPE_IDENTITY() AS bigint) AS Ident', N'@0 nvarchar(4000)', @0 = N'😢'
  SQL (3.3ms)  ROLLBACK TRANSACTION
TinyTds::Error: Unclosed quotation mark after the character string '@0 nvarcharROLLBACK TRANSACTION'.: ROLLBACK TRANSACTION
Completed 500 Internal Server Error in 31ms

ActiveRecord::StatementInvalid (TinyTds::Error: Unclosed quotation mark after the character string '@0 nvarcharROLLBACK TRANSACTION'.: ROLLBACK TRANSACTION)
```

Switching to `ActiveRecord::ConnectionAdapters::SQLServerAdapter.use_output_inserted = true` just leaves us with the encoding error:

```
Started GET "/encoding/bad" for 172.17.42.1 at 2015-02-16 15:42:45 +0000
Processing by EncodingController#bad as */*
  SQL (1.5ms)  BEGIN TRANSACTION
  SQL (0.4ms)  EXEC sp_executesql N'INSERT INTO [emojis] ([text]) OUTPUT INSERTED.[id] VALUES (@0)', N'@0 nvarchar(4000)', @0 = N'😄'  [["text", "😄"]]
TinyTds::Error: Error converting characters into server's character set. Some character(s) could not be converted: EXEC sp_executesql N'INSERT INTO [emojis] ([text]) OUTPUT INSERTED.[id] VALUES (@0)', N'@0 nvarchar(4000)', @0 = N'😄'
  SQL (1.6ms)  ROLLBACK TRANSACTION
Completed 500 Internal Server Error in 6ms

ActiveRecord::StatementInvalid (TinyTds::Error: Error converting characters into server's character set. Some character(s) could not be converted: EXEC sp_executesql N'INSERT INTO [emojis] ([text]) OUTPUT INSERTED.[id] VALUES (@0)', N'@0 nvarchar(4000)', @0 = N'😄')
```

but unfortunately we have some insert triggers on the database and thus cannot change the insert mode.

So two questions arise:

1. Can the encoding issue be fixed? We've never been able to insert Emojis via TinyTDS. We're aware that SQL Server 2012 cannot save them anyway, but we're unsure if TinyTDS should raise exceptions in that case (or should it just save question marks instead?)

2. What can we do about the failing ROLLBACK TRANSACTION? This is really a big issue for us.

We've created a sample Rails application which shows this behaviour at https://github.com/naag/sqlserver-encoding. Just run it with `rails s` and `curl http://127.0.0.1:3003/encoding/good`, `curl http://127.0.0.1:3003/encoding/bad`, `curl http://127.0.0.1:3003/encoding/really_bad`. They demonstrate the three cases (no emoji, emoji with `use_output_inserted = true` and `use_output_inserted = false`).

Any help is really appreciated!

**Comment by metaskills** [comment]
Quick question... I did not think SQL Server has the capacity to store full UTF-8 4-byte chars?

**Comment by naag** [comment]
Agreed. If we insert the Emoji through SMS, it just inserts to question marks `??`. In the meantime we also noticed the part in the TinyTDS README pointing out that raising encoding exceptions is intended behaviour. I guess we're fine with that.

The transaction rollback error however is what is really causing us headaches. It seems that activerecord-sqlserver-adapter generates the right SQL statements, but TinyTDS somehow merges half of the previous SQL statement with the ROLLBACK TRANSACTION statement: `Unclosed quotation mark after the character string '@0 nvarcharROLLBACK TRANSACTION'.: ROLLBACK TRANSACTION`.

**Comment by metaskills** [comment]
> The transaction rollback error however is what is really causing us headaches.

Can you open an issue on the adapter with the focused notes about that. This seems like a bug with the new `use_output_inserted` config when set to false as you pointed out.

**Comment by naag** [comment]
Done, thanks.

**Comment by metaskills** [comment]
I have a commit in the TinyTDS/FreeTDS 1.0 branch that takes about how Emoji support work in 0.95 and upward. Hope this helps! https://github.com/rails-sqlserver/tiny_tds/pull/265/commits/a9437697c5b8fb6efa3479f2f44fec5353dfbd8a
