### ISSUE TITLE
Which version of freetds is used by tiny_tds gem <0.6.2 x86-mingw32>!

### ISSUE THREAD

**Issue by raihan29s** [rails-sqlserver/tiny_tds#190]
I m running my redmine application on local host. it is running there perfectly. but when i try to remotely connect with my sql server 2014 database, it is giving NotImplementatedError. 

I m using redmine 2.3
ruby 1.9
my local database is sql server 08 r2 s2

remote database server is sql server 2014
  
I even tried it with redmine-2.6.1 But same error persists.

So, I need to know which version of freetds is used by tiny_tds library<0.6.2 x86-mingw32>? 

and whether this version of redmine and ruby is supported by sql server 2014?

**Comment by metaskills** [comment]
> Which version of freetds is used by tiny_tds gem

For [v0.6.2 it is 0.91](https://github.com/rails-sqlserver/tiny_tds/blob/v0.6.2/tasks/ports.rake#L11) however I am not sure what patch version. Whenever if fix cross compile and release v0.6.3 (or maybe v0.7.0) it will use the latest 0.91 which as of today is 0.91.112. Both versions can connect to a 2014 DB just fine.

> it is giving NotImplementatedError

That tells me nothing. I need a stack trace please.

**Comment by metaskills** [comment]
And please post a link to a Gist vs pasting an entire trace inline.

**Comment by dkmdnielsen** [comment]
Ya know...I have a similar environment:  SqlServer 2008 local on laptop and
2014 on a server.  Using an identical db setup on both servers, Microsoft's
own SSMS throws exceptions when accessing the remote 2014 server and it
runs just fine when accessing the local 2008 server.  I just chalked it up
as a standard MS feature.  Someone suggested I need to install/upgrade the
db tool set on laptop and that should fix things.  But that has not
happened, yet.

I guess what I am saying is, maybe it isn't tiny_tds.

**Comment by raihan29s** [comment]
![capture](https://cloud.githubusercontent.com/assets/10660626/6251976/b4d667e0-b75c-11e4-8efc-9296d02b5080.PNG)


@metaskills sorry for late response. I attached the error here. please see whether u can help me or not.

**Comment by metaskills** [comment]
This is easy. All that message is saying is that the adapter is old and at that time it did not know about 2014. What version of Rails are you using?

**Comment by raihan29s** [comment]
I m using Rails version 3.2.13.

**Comment by metaskills** [comment]
Well, update to the latest version of the 3.2.x adapter.

https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/blob/3-2-stable/lib/active_record/connection_adapters/sqlserver_adapter.rb#L184

This has nothing to do with TinyTDS and the latest 3.2.x version of the adapter has 2014 in the supported list. Closing.

**Comment by raihan29s** [comment]
my activerecord is already updated. which is 3.2.21

**Comment by metaskills** [comment]
You could always bundle to the repo using the branch 3-2-stable. That said, I just released v3.2.13 of the adapter with that change. In case updating the adapter is new to you, you typically just do this:

```
$ bundle update activerecord-sqlserver-adapter
```

**Comment by raihan29s** [comment]
Oh ur assistance worked. thanks
