### ISSUE TITLE
IPv6 fails to connect

### ISSUE THREAD

**Issue by jacob-ewald** [rails-sqlserver/tiny_tds#191]
While trying to connect to a MS SQL Server using either hostname or IP address is giving me this error:
`Unable to connect: Adaptive Server is unavailable or does not exist (TinyTds::Error)`

The hostname resolves by DNS to an IPv6 address. Putting that address directly in for the `host:` value gives a slightly different error:
`Server name not found in configuration files (TinyTds::Error)`

I thought maybe it was a yaml parsing problem so I tried double-quoting the IPv6 address, but that yielded the same error.

Is there a way to use IPv6 addresses, either directly or indirectly via DNS with TinyTDS?

**Comment by sixfeetover** [comment]
This could be because FreeTDS 0.91/0.92 didn't have support for IPv6. FreeTDS 0.95 was just released recently and does contain IPv6 support (http://lists.ibiblio.org/pipermail/freetds/2015q2/029377.html). You could try installing v0.95 and rebuilding tiny_tds with it to see if that fixes it.

**Comment by metaskills** [comment]
Thanks @sixfeetover
