### ISSUE TITLE
TinyTds::Error: Adaptive Server connection failed - message comes when trying to connect SQL server 2014 db using ruby? any ideas why and how to resolve that?

### ISSUE THREAD

**Issue by Tester-Sri** [rails-sqlserver/tiny_tds#192]
TinyTds::Error: Adaptive Server connection failed - message comes when trying to connect SQL server 2014 db using ruby? any ideas why and how to resolve that?

**Comment by metaskills** [comment]
Have you read the readme in detail yet? https://github.com/rails-sqlserver/tiny_tds#tinytdsclient-usage
