### ISSUE TITLE
what does result.do does exactly?

### ISSUE THREAD

**Issue by curiousize** [rails-sqlserver/tiny_tds#193]
I am just wondering what the do method in result.do does exactly?
And in general it would be very useful if there was an api doc for this great gem.

**Comment by metaskills** [comment]
Please see the README for all API and info. For example:

https://github.com/rails-sqlserver/tiny_tds#tinytdsresult-usage

> This pattern is so common for UPDATE and DELETE statements that the #do method cancels any need for loading the result data and returns the #affected_rows.

I much prefer a single README for a gem like this that is both simple and small. It helps connect the dots in such a way that I think are better than nerdy interface oriented docs. Not dissing them, but I find for this project, for this size, etc that a single easy GitHub README.markdown is the best option. Cheers!
