### ISSUE TITLE
Ruby 2.0.0 Symbol Lookup Error rb_thread_blocking_region

### ISSUE THREAD

**Issue by eklamer1** [rails-sqlserver/tiny_tds#194]
Hi! First of all, thank you so much for your work. This tool has made my work a whole lot less complicated. I just tried updating Ruby from 2.1.5 to 2.0.0 to keep up with AWS, and I am getting this error in tiny_tds.so:

symbol lookup error: /home/eric/.rvm/gems/ruby-2.2.0/gems/tiny_tds-0.6.2/lib/tiny_tds/tiny_tds.so: undefined symbol: rb_thread_blocking_region

I read elsewhere that this method was deprecate in Ruby 2.0.0 and replaced with something else.

**Comment by bjmllr** [comment]
see https://github.com/rails-sqlserver/tiny_tds/pull/181

**Comment by eklamer1** [comment]
Whoops! Didn't notice that one. Sorry!

**Comment by metaskills** [comment]
I have pushed 0.6.3.rc1 which is POSIX only. No pre-build win binaries now. HTH!
