### ISSUE TITLE
Segmentation fault on super :initialize in error.rb

### ISSUE THREAD

**Issue by timothybonci** [rails-sqlserver/tiny_tds#195]
I have a wall monitor running Dashing, and my jobs connect to sql servers to grab info every minute.  After minutes or hours, we will crash with:

/var/lib/gems/1.9.1/gems/tiny_tds-0.6.2/lib/tiny_tds/error.rb:21: 
[BUG] Segmentation fault
ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]

-- Control frame information 
-----------------------------------------------
c:0023 p:---- s:0090 b:0090 l:000089 d:000089 CFUNC  :initialize
c:0022 p:0012 s:0086 b:0086 l:000085 d:000085 METHOD 
/var/lib/gems/1.9.1/gems/tiny_tds-0.6.2/lib/tiny_tds/error.rb:21
c:0021 p:---- s:0082 b:0082 l:000081 d:000081 FINISH
c:0020 p:---- s:0080 b:0080 l:000079 d:000079 CFUNC  :new
c:0019 p:---- s:0078 b:0078 l:000077 d:000077 CFUNC  :cancel
c:0018 p:0258 s:0075 b:0075 l:001e30 d:000074 BLOCK  
/usr/local/bin/pbm-wallmon/jobs/staff.rb:71
c:0017 p:---- s:0054 b:0054 l:000053 d:000053 FINISH
c:0016 p:---- s:0052 b:0052 l:000051 d:000051 CFUNC  :call
c:0015 p:0027 s:0048 b:0048 l:000047 d:000047 METHOD 
/var/lib/gems/1.9.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:230
c:0014 p:0105 s:0045 b:0045 l:000330 d:000044 BLOCK  
/var/lib/gems/1.9.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:204
c:0013 p:---- s:0041 b:0041 l:000040 d:000040 FINISH
c:0012 p:---- s:0039 b:0039 l:000038 d:000038 CFUNC  :call
c:0011 p:0022 s:0036 b:0036 l:000035 d:000035 METHOD 
/var/lib/gems/1.9.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/scheduler.rb:426
c:0010 p:0102 s:0030 b:0030 l:000330 d:000330 METHOD 
/var/lib/gems/1.9.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:176
c:0009 p:0020 s:0024 b:0024 l:000023 d:000023 METHOD 
/var/lib/gems/1.9.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:360
c:0008 p:0037 s:0021 b:0021 l:000020 d:000020 METHOD 
/var/lib/gems/1.9.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobqueues.rb:60
c:0007 p:0025 s:0016 b:0016 l:000015 d:000015 METHOD 
/var/lib/gems/1.9.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/scheduler.rb:384
c:0006 p:0022 s:0013 b:0013 l:001638 d:000012 BLOCK  
/var/lib/gems/1.9.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/scheduler.rb:464
c:0005 p:---- s:0011 b:0011 l:000010 d:000010 FINISH
c:0004 p:---- s:0009 b:0009 l:000008 d:000008 CFUNC  :loop
c:0003 p:0009 s:0006 b:0006 l:001638 d:000005 BLOCK  
/var/lib/gems/1.9.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/scheduler.rb:462
c:0002 p:---- s:0004 b:0004 l:000003 d:000003 FINISH
c:0001 p:---- s:0002 b:0002 l:000001 d:000001 TOP

-- Ruby level backtrace information 
----------------------------------------
/var/lib/gems/1.9.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/scheduler.rb:462:in
 `block in start'
/var/lib/gems/1.9.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/scheduler.rb:462:in
 `loop'
/var/lib/gems/1.9.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/scheduler.rb:464:in
 `block (2 levels) in start'
/var/lib/gems/1.9.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/scheduler.rb:384:in
 `step'
/var/lib/gems/1.9.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobqueues.rb:60:in
`trigger_matching_jobs'
/var/lib/gems/1.9.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:360:in `trigger'
/var/lib/gems/1.9.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:176:in `trigger'
/var/lib/gems/1.9.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/scheduler.rb:426:in
 `trigger_job'
/var/lib/gems/1.9.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/scheduler.rb:426:in
 `call'
/var/lib/gems/1.9.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:204:in `block in trigger'
/var/lib/gems/1.9.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:230:in `trigger_block'
/var/lib/gems/1.9.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:230:in `call'
/usr/local/bin/pbm-wallmon/jobs/staff.rb:71:in `block in <top 
(required)>'
/usr/local/bin/pbm-wallmon/jobs/staff.rb:71:in `cancel'
/usr/local/bin/pbm-wallmon/jobs/staff.rb:71:in `new'
/var/lib/gems/1.9.1/gems/tiny_tds-0.6.2/lib/tiny_tds/error.rb:21:in 
`initialize'

/var/lib/gems/1.9.1/gems/tiny_tds-0.6.2/lib/tiny_tds/error.rb:21:in 
`initialize'

-- C level backtrace information 
-------------------------------------------

/usr/local/bin/pbm-wallmon/jobs/staff.rb:71 is:
next_oncall_response.cancel

which refers to:
next_oncall_response = querydb(next_oncall_query, options)
and:
def querydb(query, options)
  client = TinyTds::Client.new(options)
  return client.execute(query)
end

I can imagine an error occurring in what I'm doing (pulling a data set, iterating over it, and canceling the query in case I hit a problem so I don't tie up the connection), but I can't imaging an error here:

    def initialize(message)
      super

Any guidance would be great, and I'm happy to provide more helpful information if I can.

**Comment by metaskills** [comment]
Please try the latest 0.6.3 pre release versions and open this back up if there is an issue. Also, you might find this issue (https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/issues/402) interesting which talks about using `ActiveRecord::Base.clear_active_connections!`. But thought it might relate.
