### ISSUE TITLE
Heroku Plattform Builds

### ISSUE THREAD

**Issue by bainur** [rails-sqlserver/tiny_tds#197]
hi. 

im having difficulties to install this gem on heroku cedar.

could someone help me , how to make this gem works, or maybe any tutorial links?

this build pack
https://github.com/firmhouse/heroku-buildpack-ruby-freetds

heroku support said :
"That buildpack is approximately 2 years old now and we're not able to support 3rd party buildpacks I'm afraid - you would need to reach out to the buildpack owner to have them fix the issue."

any help would be appreciate. 

Thanks

**Comment by metaskills** [comment]
Interesting... never knew about that buildpack. Have you tried contacting @firmhouse or looking over the forks (https://github.com/firmhouse/heroku-buildpack-ruby-freetds/network) of the project for someone that has addressed this?

**Comment by eltiare** [comment]
There's this buildpack which you can use in conjunction with the most current Ruby buildpack, but sadly I can't get it to work either. https://github.com/foraker/heroku-buildpack-freetds

**Comment by ginolon** [comment]
@metaskills any help?

**Comment by larskanis** [comment]
tiny_tds-0.6.3-rc2 has some significant changes to how it is installed. It should now install and run without any buildpacks. Could you please retry with this pre-release?

**Comment by metaskills** [comment]
Can anyone confirm the 0.6.3-rc2 release for Heroku? This will be our 0.7.0 by the end of the week.

**Comment by larskanis** [comment]
My [very simple test application](https://tranquil-caverns-6259.herokuapp.com/) builds and loads successfully tiny_tds, but I don't have a DB server to connect to. So I can not verify, whether connection and encryption work. Sources are here: https://github.com/larskanis/ruby-getting-started

**Comment by metaskills** [comment]
The v0.7.0 will be published shortly. Closing this issue.

**Comment by metaskills** [comment]
## GO HERE

https://github.com/rails-sqlserver/heroku-buildpack-freetds
