### ISSUE TITLE
symbol lookup error: tiny_tds.so: undefined symbol: rb_thread_blocking_region

### ISSUE THREAD

**Issue by kevin25** [rails-sqlserver/tiny_tds#198]
When i ran the command:

rake db:migrate RAILS_ENV=production

I got the issue:

/home/deploy/.rbenv/versions/2.2.2/bin/ruby: symbol lookup error: /home/deploy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/extensions/x86_64-linux/2.2.0-static/tiny_tds-0.6.2/tiny_tds/tiny_tds.so: undefined symbol: rb_thread_blocking_region

I am using tiny_tds 0.6.2, ruby 2.2.2,  capistrino 3.2.1 and unicorn 4.9.0.

Please help me. Thanks!

**Comment by metaskills** [comment]
0.6.3.pre is for Ruby 2.

**Comment by kevin25** [comment]
Thanks, metaskills. I added it on gem and upgrade it. it is working now. For someone who needs:

gem 'tiny_tds', '~> 0.6.3.rc1'
