### ISSUE TITLE
Rake compile fails on Ubuntu 15.04 x64

### ISSUE THREAD

**Issue by kevin25** [rails-sqlserver/tiny_tds#199]
I tried to compile tiny_tds 0.6.3 but failed with these messages:

Running 'compile' for libiconv 1.14... ERROR, review '/home/deploy/soft/tiny_tds/tmp/x86_64-unknown-linux-gnu/ports/libiconv/1.14/compile.log' to see what happened.
rake aborted!
Failed to complete compile task
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/mini_portile-0.6.2/lib/mini_portile.rb:279:in `block in execute'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/mini_portile-0.6.2/lib/mini_portile.rb:271:in `chdir'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/mini_portile-0.6.2/lib/mini_portile.rb:271:in `execute'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/mini_portile-0.6.2/lib/mini_portile.rb:70:in `compile'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/mini_portile-0.6.2/lib/mini_portile.rb:110:in `cook'
tasks/ports.rake:28:in `block in define_libiconv_recipe'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rake/task.rb:240:in `call'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rake/task.rb:240:in `block in execute'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rake/task.rb:235:in `each'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rake/task.rb:235:in `execute'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rake/task.rb:179:in `block in invoke_with_call_chain'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rake/task.rb:201:in `block in invoke_prerequisites'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rake/task.rb:199:in `each'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rake/task.rb:199:in `invoke_prerequisites'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rake/task.rb:178:in `block in invoke_with_call_chain'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rake/task.rb:201:in `block in invoke_prerequisites'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rake/task.rb:199:in `each'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rake/task.rb:199:in `invoke_prerequisites'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rake/task.rb:178:in `block in invoke_with_call_chain'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rake/task.rb:201:in `block in invoke_prerequisites'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rake/task.rb:199:in `each'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rake/task.rb:199:in `invoke_prerequisites'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rake/task.rb:178:in `block in invoke_with_call_chain'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rake/task.rb:165:in `invoke'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rake/application.rb:150:in `invoke_task'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rake/application.rb:106:in `block (2 levels) in top_level'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rake/application.rb:106:in `each'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rake/application.rb:106:in `block in top_level'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rake/application.rb:115:in `run_with_threads'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rake/application.rb:100:in `top_level'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rake/application.rb:78:in `block in run'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rake/application.rb:75:in `run'
/home/deploy/.rbenv/versions/2.2.2/bin/rake:33:in `<main>'
Tasks: TOP => compile => ports:freetds => ports:freetds:x86_64-linux => ports:libiconv:x86_64-linux

What's wrong with it?

**Comment by metaskills** [comment]
Have you tried a normal gem install? `gem install tiny_tds -v 0.6.3.rc1`, if that works. Then I recommend just adding that version to your Gemfile and just using it.

**Comment by kevin25** [comment]
Thanks, metaskills. I added it on gem and upgrade it. it is working now. For someone who needs:

gem 'tiny_tds', '~> 0.6.3.rc1'

**Comment by kevin25** [comment]
Btw, when i deploy it

cap production deploy, i got the old tiny_tds

/home/deploy/.rbenv/versions/2.2.2/bin/ruby: symbol lookup error: /home/deploy/apps/miraclegrow2/shared/bundle/ruby/2.2.0/extensions/x86_64-linux/2.2.0-static/tiny_tds-0.6.2/tiny_tds/tiny_tds.so: undefined symbol: rb_thread_blocking_region

What's wrong?

**Comment by metaskills** [comment]
Well, if this `gem 'tiny_tds', '~> 0.6.3.rc1'` is in your Gemfile... and you updated your Gemfile.lock... then it has to work.

**Comment by kevin25** [comment]
I removed the Gemfile.lock and install the bundle but still got the same issue.

/home/deploy/.rbenv/versions/2.2.2/bin/ruby: symbol lookup error: /home/deploy/apps/miraclegrow2/shared/bundle/ruby/2.2.0/extensions/x86_64-linux/2.2.0-static/tiny_tds-0.6.2/tiny_tds/tiny_tds.so: undefined symbol: rb_thread_blocking_region

**Comment by metaskills** [comment]
I can assure you this has something to do with your own setup. It has nothing to do with TinyTDS. You need to verify that your Gemfile is doing what is specter on your remote box. Do things like check to make sure you committed changes, pushed them, verified those on the remote box, etc. This is not a TinyTDS issue at this point.

**Comment by kevin25** [comment]
I renamed tiny_tds-0.6.2 and symlinked tiny_tds-0.6.3.rc1 to tiny_tds-0.6.2. Now I passed such error, but i got the new one:

Tasks: TOP => deploy:migrate
(See full trace by running task with --trace)
The deploy has failed with an error: Exception while executing as deploy@10.10.18.102: rake exit status: 1
rake stdout: == 20140903211802 RebuildAmountInExpenseItem: migrating =======================
-- remove_column(:expense_items, :expense_amount)
   -> 0.0363s
   -> -1 rows
-- add_column(:expense_items, :expense_amount, :decimal, {:null=>false, :precision=>18, :scale=>2})

 DEBUG [a95431d8]       rake aborted!
 DEBUG [a95431d8]       StandardError: An error has occurred, this and all later migrations canceled:
 DEBUG [a95431d8]
 DEBUG [a95431d8]       TinyTds::Error: ALTER TABLE only allows columns to be added that can contain nulls, or have a DEFAULT definition specified, or the column being
added is an identity or timestamp column, or alternatively if none of the previous conditions are satisfied the table must be empty to allow addition of this column. Co
lumn 'expense_amount' cannot be added to non-empty table 'expense_items' because it does not satisfy these conditions.: ALTER TABLE [expense_items] ADD [expense_amount]
 decimal(18,2) NOT NULL
 DEBUG [a95431d8]       /home/deploy/apps/miraclegrow2/shared/bundle/ruby/2.2.0/gems/activerecord-sqlserver-adapter-4.2.4/lib/active_record/connection_adapters/sqlserve
r/database_statements.rb:284:in `do'
 DEBUG [a95431d8]       /home/deploy/apps/miraclegrow2/shared/bundle/ruby/2.2.0/gems/activerecord-sqlserver-adapter-4.2.4/lib/active_record/connection_adapters/sqlserve
r/database_statements.rb:284:in `raw_connection_do'
 DEBUG [a95431d8]       /home/deploy/apps/miraclegrow2/shared/bundle/ruby/2.2.0/gems/activerecord-sqlserver-adapter-4.2.4/lib/active_record/connection_adapters/sqlserve
r/database_statements.rb:237:in `block in do_execute'
 DEBUG [a95431d8]       /home/deploy/apps/miraclegrow2/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:473:in
 `block in log'
 DEBUG [a95431d8]       /home/deploy/apps/miraclegrow2/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/notifications/instrumenter.rb:20:in `instrum
ent'
 DEBUG [a95431d8]       /home/deploy/apps/miraclegrow2/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:467:in
 `log'


 DEBUG [a95431d8]       TinyTds::Error: ALTER TABLE only allows columns to be added that can contain nulls, or have a DEFAULT definition specified, or the column being added is an identity or timestamp column, or alternatively if none of the previous conditions are satisfied the table must be empty to allow addition of this column. Column 'expense_amount' cannot be added to non-empty table 'expense_items' because it does not satisfy these conditions.

  DEBUG [a95431d8]       Tasks: TOP => db:migrate
 DEBUG [a95431d8]       (See full trace by running task with --trace)
 DEBUG [a95431d8]       == 20140903211802 RebuildAmountInExpenseItem: migrating =======================
 DEBUG [a95431d8]       -- remove_column(:expense_items, :expense_amount)
 DEBUG [a95431d8]          -> 0.0363s
 DEBUG [a95431d8]          -> -1 rows
 DEBUG [a95431d8]       -- add_column(:expense_items, :expense_amount, :decimal, {:null=>false, :precision=>18, :scale=>2})



May relate to my SQL server?

**Comment by metaskills** [comment]
> I renamed tiny_tds-0.6.2 and symlinked tiny_tds-0.6.3.rc1 to tiny_tds-0.6.2.

That sounds like a bad idea. I recommend you debug the core issue of why your Gemfile.lock was not working. Your other issue is what it says, SQL Server related. Nothing to do with TinyTDS or the adapter. Cheers.

**Comment by kevin25** [comment]
it loads the old tiny_tds, that was why i got such errors. I symlinked it and it is working now.
