### ISSUE TITLE
Using TinyTDS for SQL Azure on Windows

### ISSUE THREAD

**Issue by meet-bhagdev** [rails-sqlserver/tiny_tds#200]
I am struggling to make TinyTDS work for SQL Azure on Windows. I am aware that I have to configure and build FreeTDS using OpenSSL,I followed all the required steps and it still did not work. Is there anyway I can get TinyTDS(included FreeTDS) available for direct install?
Thanks!

**Comment by metaskills** [comment]
Hey Meet! Please read issue #196 where @aharpervc started working on getting Windows binaries published by fixing rake-compiler-dev-box. So my question is, does the latest rake-compiler-dev-box have OpenSSL and can we change our port file to take advantage of this? If so, this is what issue https://github.com/rails-sqlserver/tiny_tds/issues/75 is for too.

**Comment by meet-bhagdev** [comment]
Hi metaskills, no luck yet :( Still trying to make TinyTDS work on windows with SQL Azure. Got it to work with SQL Azure on Mac though so thats good. But if someone can help with the windows installations that would be great. gem install tiny_tds doesn't do the trick unfortunately.

**Comment by metaskills** [comment]
Gonna close this issue while we work on #207 and get another pre-release of native windows binaries. That issue also adds OpenSSL too which is needed for Azure. Please watch that issue for updates. Cheers
