### ISSUE TITLE
Username is not displayed as expected

### ISSUE THREAD

**Issue by ajaynayakt** [rails-sqlserver/tiny_tds#204]
I'm providing the input as Client.new (:username=>'Domain\username', ...) and output for username is returned with two slashes through Client.rb file. I'm using 0.6.2 version of Tiny_TDS on Mac

there are two forward slashes in the output and I think this is causing me not to login to the MSSQL database. Is this an issue or do we have a workaround?

Thanks
Ajay

**Comment by metaskills** [comment]
That's just how Ruby works, check in IRB, it is just a display issue since \ is an escape sequence.

```ruby
$ irb
>> u = 'Domain\username'
=> "Domain\\username"
```
