### ISSUE TITLE
TinyTDS install on Mac fails

### ISSUE THREAD

**Issue by meet-bhagdev** [rails-sqlserver/tiny_tds#205]
Hello,
I am trying to install TinyTDS on my Mac.
I installed freetds with homebrew and tested it to make sure it works. 
Then I try to install TinyTDS with sudo gem install tiny_tds and it gives me following error(i am on ruby 2.0.0)
Building native extensions.  This could take a while...
ERROR:  Error installing tiny_tds:
	ERROR: Failed to build gem native extension.

    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby extconf.rb
checking for iconv_open() in iconv.h... no
checking for iconv_open() in -liconv... yes
checking for sybfront.h... yes
checking for sybdb.h... yes
checking for tdsdbopen() in -lsybdb... no
-----
freetds is missing.
-----
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
	--enable-lookup
	--disable-lookup
	--with-iconv-dir
	--without-iconv-dir
	--with-iconv-include
	--without-iconv-include=${iconv-dir}/include
	--with-iconv-lib
	--without-iconv-lib=${iconv-dir}/
	--with-freetds-dir
	--without-freetds-dir
	--with-freetds-include
	--without-freetds-include=${freetds-dir}/include
	--with-freetds-lib
	--without-freetds-lib=${freetds-dir}/
	--with-iconvlib
	--without-iconvlib
	--with-sybdblib
	--without-sybdblib

Gem files will remain installed in /Library/Ruby/Gems/2.0.0/gems/tiny_tds-0.6.2 for inspection.
Results logged to /Library/Ruby/Gems/2.0.0/gems/tiny_tds-0.6.2/ext/tiny_tds/gem_make.out

Can someone help out please? I have ensured that FreeTDS is installed.
Thanks!

**Comment by metaskills** [comment]
Can you try bundling to this repos master branch to see if that helps?

**Comment by meet-bhagdev** [comment]
Hi metaskills, thanks for your prompt response. Can you please help me with instructions as to how I can do so?

**Comment by metaskills** [comment]
Sure... this is just a simple Bundler thing. http://bundler.io/v1.10/git.html

```ruby
gem 'tiny_tds', github: 'rails-sqlserver/tiny_tds'
```

Should work.

**Comment by meet-bhagdev** [comment]
Hello metaskils - here is what i get when I run that - 
ERROR:  While executing gem ... (Gem::CommandLineError)
    Unknown command tiny_tds,

**Comment by meet-bhagdev** [comment]
Hello @metaskills ,
I was able to fix the problem. 
Here is what I did : 
brew install FreeTDS
sudo ARCHFLAGS="-arch x86_64" gem install tiny_tds

Here is the link to the getting started doc - https://azure.microsoft.com/en-us/documentation/articles/sql-database-develop-ruby-simple-mac-osx/

Let me know what you think of it :)

**Comment by metaskills** [comment]
I think it is awesome! Thanks so much y'all for doing that. Keep an eye out on #207 too!
