### ISSUE TITLE
TinyTds::Error: Unable to open socket on Heroku

### ISSUE THREAD

**Issue by adambilsing** [rails-sqlserver/tiny_tds#206]
I got TinyTds along with the 'activerecord-sqlserver-adapter' gem working on rails hosted at Heroku.  I accomplished this by using the apt-get buildpack and installing freetds on the server.  Everything deploys fine, but once im in the console and I attempt to trigger a connection to the sql server I get back the following error:  'TinyTds::Error: Unable to open socket'.

Everything works fine locally.

**Comment by larskanis** [comment]
tiny_tds-0.6.3-rc2 has some significant changes to how it is installed. It should now install and run without any buildpacks. Could you please retry with this pre-release?

**Comment by metaskills** [comment]
Closing this since it duplicates #197
