### ISSUE TITLE
Heroku "FreeTDS" is missing. With or without buildpacks the error remains there.

### ISSUE THREAD

**Issue by ginolon** [rails-sqlserver/tiny_tds#210]
How to install freetds on cedar-14 on Heroku?

There is an updated guide?

**Comment by eltiare** [comment]
Following

**Comment by eltiare** [comment]
I finally got it to work by kludging code together from a couple of repos. Try this: https://github.com/eltiare/heroku-buildpack-freetds

**Comment by ginolon** [comment]
Yes, but how? I have ti create a file on my local PC And then git push heroku master? Please step by step, thanks.

**Comment by eltiare** [comment]
You need to configure the buildpacks on Heroku. You can easily do it by using https://github.com/ddollar/heroku-buildpack-multi

**Comment by ginolon** [comment]
After a good deploy with multipack and this .buildpacks file:

```
https://github.com/eltiare/heroku-buildpack-freetds.git#master
https://github.com/heroku/heroku-buildpack-ruby.git#master
```

I have this error on Heroku:

```
/app/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require': libsybdb.so.5: cannot open shared object file: No such file or directory - /app/vendor/bundle/ruby/2.1.0/extensions/x86_64-linux/2.1.0-static/tiny_tds-0.6.2/tiny_tds/tiny_tds.so (LoadError)
```

**Comment by eltiare** [comment]
Yeah, I'm getting that now too. I have no idea why it compiled at first and now it's barfing. Sorry. :(

**Comment by eltiare** [comment]
I'm rather tired of Heroku so I'm attempting to get the ops team to move us to AWS.

**Comment by ginolon** [comment]
The problem is still there so... How to fix... damn...

**Comment by ginolon** [comment]
I opened a problem here, with bounty: http://stackoverflow.com/questions/31604378/heroku-freetds-how-to-use-rasil-sql-server-with-tinytds-with-multi-buildpacks

**Comment by ginolon** [comment]
@eltiare, if I run `heroku run bash` and I go here:

```
cd vendor
~/vendor $ dir
dir
assets  bundle  freetds  heroku  ruby-2.1.6
```

I have a ruby 2.1.6 and the error is this:

```
/app/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require': libsybdb.so.5: cannot open shared object file: No such file or directory - /app/vendor/bundle/ruby/2.1.0/extensions/x86_64-linux/2.1.0-static/tiny_tds-0.6.2/tiny_tds/tiny_tds.so (LoadError)
```

so the directory 2.1.0 isn't there. why?

**Comment by ginolon** [comment]
I tried also to change the download url to:

https://fossies.org/linux/privat/freetds-0.95.19.tar.gz

but nothing, the same error:

```
LoadError: libsybdb.so.5: cannot open shared object file: No such file or directory - /tmp/build_77614230336e05e686009861d71719ea/vendor/bundle/ruby/2.1.0/extensions/x86_64-linux/2.1.0-static/tiny_tds-0.6.2/tiny_tds/tiny_tds.so
```

**Comment by ginolon** [comment]
Here is the answer, but i'm not good to accomplish. Is your buildpack for this?

https://github.com/rails-sqlserver/tiny_tds/issues/74#issuecomment-4528748

**Comment by larskanis** [comment]
This should be fixed in release 0.6.3-rc2. Tiny_tds should install and run without any special requirements.

**Comment by ginolon** [comment]
@larskanis I'm not with my PC. You are such a great person. I will let you know soon!

**Comment by metaskills** [comment]
Closing this issue since it duplicates #197, pleas make comments there.

**Comment by metaskills** [comment]
## GO HERE

https://github.com/rails-sqlserver/heroku-buildpack-freetds
