### ISSUE TITLE
Using a proxy

### ISSUE THREAD

**Issue by eltiare** [rails-sqlserver/tiny_tds#211]
My environment requires that I use a proxy. I don't see any options for setting one in this library. Any suggestions on how I can achieve this?

**Comment by metaskills** [comment]
TBH, I a weak on proxy setups. I had to Google to see if FreeTDS supported a proxy and it does not seem to. So I am sure there is nothing this gem can do about it either. 

Other searches for "TDS Proxy SQL Server" yielded some interesting results. This thread (http://serverfault.com/questions/488945/how-to-setup-an-tcp-ip-proxy-with-traffic-interception-for-ms-sql-traffic-in-th) seems to suggest that there might be a commercial product while this thread on FreeTDS (http://marc.info/?l=freetds&m=127212944809614) seems to suggest just doing a VPN. Hope that is helpful and if you think there is anything we can do, please let me know and we can re-open this issue.

**Comment by eltiare** [comment]
Thanks for the suggestion to use a VPN. Proximo may work for Heroku, which is my environment.
