### ISSUE TITLE
null values written into the database

### ISSUE THREAD

**Issue by hbzhang** [rails-sqlserver/tiny_tds#212]
There, I tried to use 

gem 'tiny_tds'
gem 'activerecord-sqlserver-adapter'

I am able to write to sql server database on another server. However, the string I am trying to write turns out to be 'NULL' values in the database tables. 

What is wrong here?

I used the latest version of tiny_tds,activerecord-sqlserver-adapter, rails 4.2, sql server 2014.

**Comment by metaskills** [comment]
I have no idea, could you try to explain the issue you are having with some steps to reproduce?

**Comment by metaskills** [comment]
Closing this issue, you have cross posted here.
https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/issues/410
