### ISSUE TITLE
Forcing Static/MiniPortile Builds

### ISSUE THREAD

**Issue by metaskills** [rails-sqlserver/tiny_tds#215]
@larskanis Is there a way I can force our extconf.rb to use MiniPortile and make a static build for the current platform? I was playing around with making a helper to encapsulate `TINYTDS_FORCE_PORTS` and remove the `SKIP` ones to do this. But it seems that our build recipes are really category first to Windows and would require some bail outs as well. Thoughts?

**Comment by larskanis** [comment]
Only the OpenSSL recipe is Windows specific. Libiconv and freetds should
build on a Unix system, too.  It is possible, of course, to allow static
builds, but requires changes to both the recipes and the tiny_tds extension
build. Maybe I don't your intent behind this - why do you want to link
static?

**Comment by metaskills** [comment]
I was thinking of removing all the language in the README that talks about allowing users to create ad-hoc static builds and just wanted to start a discussion around it.

**Comment by larskanis** [comment]
OK, I understand. The [MiniPortile section](https://github.com/rails-sqlserver/tiny_tds#using-miniportile) is no longer up-to-date. In fact, `rake native gem` should still work when using system freetds, but it doesn't work with shared libraries built per MiniPortile. However there is little benefit in using `rake native gem`, since `gem install` does mostly the same now. IMHO it's not worth to add the additional complexity to support static builds for `rake native gem`.

The description to `TINYTDS_FREETDS_VERSION` is still valid, but now works for gem install, too. 

@metaskills As a non-native English speaker, I don't like to write longer README texts - it's probably better if you revamp the section, isn't it?

**Comment by metaskills** [comment]
> since gem install does mostly the same now. IMHO it's not worth to add the additional complexity to support static builds for rake native gem

Very well said! I agree.

> it's probably better if you revamp the section, isn't it?

Well, you speak really well IMO, but I will make the changes :) thanks again!

**Comment by metaskills** [comment]
Hmmm... one big draw back I just figured out is that I can no longer test different versions of FreeTDS using:

```
$ bundle exec rake TINYTDS_FREETDS_VERSION="current"
```

**Comment by larskanis** [comment]
For me it works:
```
$ rake compile  TINYTDS_FREETDS_VERSION=current
mkdir -p tmp/x86_64-linux/tiny_tds/2.2.0
cd tmp/x86_64-linux/tiny_tds/2.2.0
/home/lars/.rvm/rubies/ruby-2.2.0/bin/ruby -I. ../../../../ext/tiny_tds/extconf.rb
checking for sybfront.h... no
Downloading freetds-current.tar.gz (100%) 
Extracting freetds-current.tar.gz into tmp/x86_64-unknown-linux-gnu/ports/freetds/current... OK
Running 'configure' for freetds current... OK
Running 'compile' for freetds current... OK
Running 'install' for freetds current... OK
Activating freetds current (from /home/lars/comcard/tiny_tds/ports/x86_64-unknown-linux-gnu)...
checking for sybfront.h... yes
checking for sybdb.h... yes
checking for tdsdbopen() in -lsybdb... yes
[...]
```
and it loads, too.

**Comment by metaskills** [comment]
Maybe you do not have a system FreeTDS installed? On mine:

```
$ bundle exec rake compile TINYTDS_FREETDS_VERSION=current                      
mkdir -p tmp/x86_64-darwin14.0/tiny_tds/2.1.6
cd tmp/x86_64-darwin14.0/tiny_tds/2.1.6
/Users/kencollins/.rbenv/versions/2.1.6/bin/ruby -I. ../../../../ext/tiny_tds/extconf.rb
checking for sybfront.h... yes
checking for sybdb.h... yes
checking for tdsdbopen() in -lsybdb... yes
checking for ct_bind() in -lct... yes
checking for sybfront.h... yes
checking for sybdb.h... yes
checking for tdsdbopen() in -lsybdb... yes
checking for ct_bind() in -lct... yes
creating Makefile
...
```

I am working on a way around this now unless you have some thoughts?

**Comment by larskanis** [comment]
Maybe there should be something like `TINYTDS_FORCE_PORTS` in addition to `TINYTDS_SKIP_PORTS`. This is what `gem inst tiny_tds -- --disable-system-freetds` does. Unfortunately I don't know a way how to set extconf.rb parameters at `rake compile`.

**Comment by larskanis** [comment]
```
rake TINYTDS_FREETDS_VERSION=current -- --disable-system-freetds
```
should disable system freetds and force mini_portiles.

**Comment by metaskills** [comment]
Love it. Closing this issue.
