### ISSUE TITLE
Does tiny_tds support executing 'PRINT 'Hello World'' statement?

### ISSUE THREAD

**Issue by zhongxiao37** [rails-sqlserver/tiny_tds#216]
I wonder if tiny_tds could support executing 'PRINT 'Hello World'' statement? How could I make it? Thanks in advance.

```
result = Client.execute("PRINT 'Hello World'").do
p result
```

**Comment by metaskills** [comment]
I am almost certain that `PRINT` output should not go to the results stream. It could go to STDOUT but that sounds wrong too. Can you do some research on the following:

1. Does FreeTDS/DBLIB contain any interface to capture these?
2. Is there any history with this type of request to Rails core for MySQL, PostgreSQL, and/or SQLite?

I did some quick research on the first point and could not find anything.

**Comment by metaskills** [comment]
Started this branch https://github.com/rails-sqlserver/tiny_tds/tree/print_feature

**Comment by aharpervc** [comment]
This was added with #352 and released with 2.1.0
