### ISSUE TITLE
TinyTds::Error: Unable to connect: Adaptive Server is unavailable or does not exist

### ISSUE THREAD

**Issue by dharmdip** [rails-sqlserver/tiny_tds#218]
i am trying with FreeTds. I am checking on Windows server 2012 R2. I keep getting error Adaptive Server is unavailable or does not exist (TinyTds::Error), i went through firewall but it seems fine also i am able to connect from SQL management studio.

Also later i tried with different ruby version and dev-kit but end-up with same error.

TinyTds::Error: Unable to connect: Adaptive Server is unavailable or does not exist

Any thought?

**Comment by dharmdip** [comment]
Hello @metaskills, 

When i run separately using gem i am able to connect and tsql works. Do you have any idea what i am doing wrong?

Thanks,
Dharmdip

**Comment by metaskills** [comment]
> When i run separately using gem i am able to connect

Can you explain what you mean there? Thanks.

**Comment by dharmdip** [comment]
Yes, sure. 

From irb, i can connect using TinyTds gem to Azure DB and able to perform query, also same applies to tsql from command prompt, but while using from rails application i keep getting this error.

**Comment by metaskills** [comment]
Is the Rails application using the latest version of TinyTDS? What version is in the Gemfile.lock?

**Comment by dharmdip** [comment]
it's latest gem version. gem 'tiny_tds', '~> 0.7.0' , and yes i am on windows with DevKit installed.

**Comment by metaskills** [comment]
Hmmm... this could be a problem with the adapter then. Or it could be an issue with your database.yml and configs. Can you post me both of these:

* How you connected successfully with IRB?
* What your Rails database.yml looks like.

Thanks in advance.

**Comment by dharmdip** [comment]
Yes, sure. Here it is.

**IRB Code**

```
require 'rubygems'
require 'tiny_tds'

client = TinyTds::Client.new username: 'username@server', password: 'password', host: 'host.database.windows.net', port: 1433, database: 'database', azure:true 

results = client.execute("select * from table") 
 results.each do |row| 
 puts row 
end 
```

**database.yml**

```
development:
  adapter: sqlserver
  dataserver: database.windows.net
  database: database
  username: username@node
  password: password  
  azure: true
```

**Comment by metaskills** [comment]
Can you remove the "dataserver" option from your YAML and replace it with "host" instead and let me know if that works.

**Comment by dharmdip** [comment]
Same error, while running migration on server.

rake aborted!
TinyTds::Error: Unable to connect: Adaptive Server is unavailable or does not exist

**Comment by metaskills** [comment]
Can you remove the `database` option in both. This should not be needed and ignored with Azure. Just want to make sure it is not the issue. Also make sure that your username follows the `username@server` in both too please.

**Comment by dharmdip** [comment]
Sorry, again same error this time it took long time.

TinyTds::Error: Unable to connect: Adaptive Server is unavailable or does not exist

**Comment by metaskills** [comment]
OK, I'll do some adapter tests later with the new Azure DBs I have. Give me a bit tho.

**Comment by dharmdip** [comment]
It's nice of you, I will run some more test and try to dig error in detail.

**Comment by dharmdip** [comment]
@metaskills, is new Azure DBs connection works for you?

**Comment by dharmdip** [comment]
Hi @metaskills, 

any guide for me to resolve this problem?

**Comment by metaskills** [comment]
@dharmdip Did you resolve this? I read back thru and got a bit confused. Your IRB code shows me you are trying to connect to Azure but your orig comment says a 2012 DB.

**Comment by dharmdip** [comment]
@Ken, I am trying to connect Azure DB, while connecting I am getting this
error.

**Comment by metaskills** [comment]
Did you configure a firewall rule on Azure?

**Comment by dharmdip** [comment]
Yes, i am able to connect through tsql from command prompt, but not able to
connect via application.

If you need more details from my side i will do.

On Mon, Nov 16, 2015 at 8:31 AM, Ken Collins <notifications@github.com>
wrote:

> Did you configure a firewall rule on Azure?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rails-sqlserver/tiny_tds/issues/218#issuecomment-156900360>
> .
>



-- 
Thanks & Regards,
Dharmdipsinh R Rathod,
Cell : +91-9924033384.

**Comment by metaskills** [comment]
Which `tsql` are you using?

**Comment by dharmdip** [comment]
i am using following version,

Microsoft SQL Server 2012 - 11.0.2100.60 (x64)

On Mon, Nov 16, 2015 at 5:24 PM, Ken Collins <notifications@github.com>
wrote:

> Which tsql are you using?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rails-sqlserver/tiny_tds/issues/218#issuecomment-157007661>
> .
>



-- 
Thanks & Regards,
Dharmdipsinh R Rathod,
Cell : +91-9924033384.

**Comment by dharmdip** [comment]
Here are more details.

> @@VERSION

Microsoft SQL Server 2012 - 11.0.2100.60 (X64)
        Feb 10 2012 19:39:15
        Copyright (c) Microsoft Corporation
        Express Edition (64-bit) on Windows NT 6.2 <X64> (Build 9200: )

> tsql -C

Compile-time settings (established with the "configure" script)
                            Version: freetds v0.95rc2
             freetds.conf directory: \freetds-0.95rc2\etc
     MS db-lib source compatibility: no
        Sybase binary compatibility: no
                      Thread safety: yes
                      iconv library: yes
                        TDS version: 7.0
                              iODBC: no
                           unixodbc: yes (unixODBC 2.3.2)
              SSPI "trusted" logins: yes
                           Kerberos: yes (Heimdal 1.6.99)
                            OpenSSL: yes (OpenSSL 1.0.2a)
                             GnuTLS: no

On Mon, Nov 16, 2015 at 5:52 PM, Dharmdip <dharmdip.rathod@gmail.com> wrote:

> i am using following version,
>
> Microsoft SQL Server 2012 - 11.0.2100.60 (x64)
>
> On Mon, Nov 16, 2015 at 5:24 PM, Ken Collins <notifications@github.com>
> wrote:
>
>> Which tsql are you using?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/rails-sqlserver/tiny_tds/issues/218#issuecomment-157007661>
>> .
>>
>
>
>
> --
> Thanks & Regards,
> Dharmdipsinh R Rathod,
> Cell : +91-9924033384.
>



-- 
Thanks & Regards,
Dharmdipsinh R Rathod,
Cell : +91-9924033384.

**Comment by metaskills** [comment]
OK... so I think I see what is going on here and you may be the best to debug your situation. From what I can tell, you have installed your own FreeTDS and you are not using the Windows gems' precompiled static FreeTDS. Does this make sense? Because you have this complex setup going on... there could be NUMEROUS places that a small config could cross the steams between the static lib and the one you have installed. For example, maybe you have TDSVER or FREETDS or some other ENV set that makes your static lib use a non local conf file? I honestly have no idea. But you are honestly going to be better to debug your setup.... I can only offer hints from a distance. For example, if you have the tools to build your own gem and install things, have you tried using the master branch of this repo?

**Comment by dharmdip** [comment]
okay, let me start using master branch of the repo, i was using windows
gems' precompiled static freeTDS. I had setup on brand new installed
Windows 2012 R2 server to test config. So, i am going to check with
following cases.

1) Use latest repo for gem.
2) Again check with new windows machine (as there may be chance of
configuration mess-up)

let me check and get back to you with results, apart from anything i need
to take care?



On Mon, Nov 16, 2015 at 6:07 PM, Ken Collins <notifications@github.com>
wrote:

> OK... so I think I see what is going on here and you may be the best to
> debug your situation. From what I can tell, you have installed your own
> FreeTDS and you are not using the Windows gems' precompiled static FreeTDS.
> Does this make sense? Because you have this complex setup going on... there
> could be NUMEROUS places that a small config could cross the steams between
> the static lib and the one you have installed. For example, maybe you have
> TDSVER or FREETDS or some other ENV set that makes your static lib use a
> non local conf file? I honestly have no idea. But you are honestly going to
> be better to debug your setup.... I can only offer hints from a distance.
> For example, if you have the tools to build your own gem and install
> things, have you tried using the master branch of this repo?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rails-sqlserver/tiny_tds/issues/218#issuecomment-157015250>
> .
>



-- 
Thanks & Regards,
Dharmdipsinh R Rathod,
Cell : +91-9924033384.

**Comment by dharmdip** [comment]
okay, i have checked on windows 8 and fresh installation of gems, development environment. Again i am facing same issue, here is log for error.

<script src="https://gist.github.com/dharmdip/e9e1031160de598ef23c.js"></script>

**Comment by dharmdip** [comment]
Here are more details. 

1) https://gist.github.com/dharmdip/367ed4d17f2557ee350e#file-gem_make-out
2) https://gist.github.com/dharmdip/74ec5ac0445bbe18cc5a#file-mkmf-log

**Comment by metaskills** [comment]
Can you try master now?

**Comment by dharmdip** [comment]
Okay, let me check with master.
Thank you.

**Comment by dharmdip** [comment]
Okay, end up with new error. 

../gems/tiny_tds-33e381242a8b/lib/tiny_tds/client.rb:75:in `connect': Write to the server failed (TinyTds::Error)

**Comment by metaskills** [comment]
OK, please follow along #249, I think this issue duplicates it.

**Comment by dharmdip** [comment]
My database.yml is 

development:
  adapter: sqlserver
  host: xxxxxx.database.windows.net
  database: database
  username: username@node
  password: password  
  azure: true

i am passing Boolean.

**Comment by metaskills** [comment]
Remove database

**Comment by dharmdip** [comment]
No luck, same error.

**Comment by metaskills** [comment]
Closing this in favor of https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/issues/446 which may related back to https://github.com/rails-sqlserver/tiny_tds/issues/250
