### ISSUE TITLE
TinyTds::Error: Error converting characters into server's character set. Some character(s) could not be converted

### ISSUE THREAD

**Issue by TLmaK0** [rails-sqlserver/tiny_tds#219]
Hi,

first, thanks for this awesome gem.

I'm trying to store Japanese characters. I have created a new rails app to reproduce the problems.
I'm using activerecord-3.2.22, activerecord-sqlserver-adapter-3.2.13 and tinytds-0.7.0. Freetds is 0.91.112

The sqlserver is a sqlserver 2008 R2, with a database with collation SQL_Latin1_General_CP1_CI_AS, only have a table "posts" with a column 'name' NVARCHAR(255).

I run the rails console and write:

    connection = TinyTds::Client.new(:host=>'192.168.1.10', :database=>'dbname', :username=>'user', :password=>'pass')
    result = connection.execute("insert into dbname.dbo.posts(name) values(N'𫠝')")

An the console response is:

    TinyTds::Error: Error converting characters into server's character set. Some character(s) could not be converted

I'm not sure how to debug the issue.

**Comment by TLmaK0** [comment]
Executing this at command line:

    TDSVER=8.0 tsql -H server_connection -U user -P pass -p 1433 <<EOS
    use dbname
    go
    insert into dbname.dbo.posts(name) values(N'𫠝')
    go
    exit
    EOS

returns:

    Error 2402 (severity 4):
        Error converting characters into server's character set. Some character(s) could not be converted
    Msg 105 (severity 15, state 1) from SPBARAPIWIN01V\SQLEXPRESS Line 1:
        "Unclosed quotation mark after the character string ''."
    Msg 102 (severity 15, state 1) from SPBARAPIWIN01V\SQLEXPRESS Line 1:
        "Incorrect syntax near ''."

**Comment by TLmaK0** [comment]
I will move this question to freetds.

Thanks

**Comment by metaskills** [comment]
Interesting. This could be the right place to discuss. I'm gonna reopen the issue.

**Comment by metaskills** [comment]
OK, this is [our section on how we do reads/writes with encodings](https://github.com/rails-sqlserver/tiny_tds#encoding-error-handling). You are doing a write and we want to raise an exception if something is not right. We have various encoding tests including a [nice clean insert](https://github.com/rails-sqlserver/tiny_tds/blob/master/test/result_test.rb#L123-L131) for a multi-byte char. There are even more tests specifically for Japanese characters in the adapter too on top of TinyTDS. These all pass. 

So I suspect this is something is different on your end and I am interested in find out out what. What is the output of `connection.charset`? What happens when you do this?

```ruby
connection.execute("INSERT INTO dbname.dbo.posts ([name]) VALUES (N'✓')").do
```

**Comment by TLmaK0** [comment]
Thanks @metaskills,

`connection.charset` returns "UTF-8" and the `connection.execute("INSERT INTO dbname.dbo.posts ([name]) VALUES (N'✓')").do` works perfectly.

I was unable to find the tests for Japanese characters in the adapter. Could you paste the link?, I will try to pass them in my enviroment.

**Comment by TLmaK0** [comment]
Finally I was able to make it work. At freetds.conf I have comment out 
```
dump file = /tmp/freetds.log
debug flags = 0xffff
```
then in /tmp/freetds.log. I can see:

```
09:13:59.947760 25205 (iconv.c:351):preparing iconv for "UTF-8" <-> "UCS-2LE" conversion
09:13:59.947822 25205 (iconv.c:391):preparing iconv for "ISO-8859-1" <-> "UCS-2LE" conversion
...
09:13:59.952327 25205 (token.c:375):Product name for 0x71000001 is 2000 SP1
```

I don't know why it says that it is a Sqlserver 2000 SP1. Looking at http://www.freetds.org/tds.html I have seen that the correct protocol for MSQL 2000 is 7.1.

Changing 'client charset' to 'ISO-8859-1' and 'tds version' to 7.1, it works perfectly with tsql.

Then I tried the same with TinyTDS. I had to specify the encoding in connection:

```ruby
connection = TinyTds::Client.new(:host=>'192.168.1.10', :database=>'dbname', 
           :username=>'user', :password=>'pass', :encoding=>'ISO-8859-1')
result = connection.execute("insert into dbname.dbo.posts(name) values(N'𫠝')")
result.insert
result = connection.execute("select * from dbname.dbo.posts")
result.each {|post| puts post['name'] }
```

Now I have problems with activerecord-sqlserver-adapter encoding, but this is another history :)

**Comment by metaskills** [comment]
Cool, I think I may add some of this to the README for debugging.

**Comment by TLmaK0** [comment]
There is another thing to take care. Chars stored in database are stored in some kind of compatible encoding, not in UCS-2, so other apps with real UCS-2 encoding will not be able to read this chars. I have asked FreeTDS group but no answer.

**Comment by TLmaK0** [comment]
Finally, someone from FreeTDS point to me to the correct fix. The problem is that newer versions of SQL Server uses UTF-16LE to encoding but older versions uses UCS-2. Freetds works with UCS-2 by default. Adding this "use utf-16 = true" to freetds.conf fix the problem:

```
client charset = UTF-8
tds version = 7.3
use utf-16 = true
```

**Comment by metaskills** [comment]
This is really really helpful! Will think about this a bit more, but please leave this open.

**Comment by sixfeetover** [comment]
Just wanted to jump in and agree: I needed to use `use utf-16 = true` in my freetds.conf file as well to successfully round trip > 2 byte characters (especially emoji). We're on SQL Server 2014.

**Comment by metaskills** [comment]
I have a commit in the TinyTDS/FreeTDS 1.0 branch that takes about how Emoji support work in 0.95 and upward. Hope this helps! https://github.com/rails-sqlserver/tiny_tds/pull/265/commits/a9437697c5b8fb6efa3479f2f44fec5353dfbd8a
