### ISSUE TITLE
Getting "Azure connections not supported in this version of FreeTDS"

### ISSUE THREAD

**Issue by jenko** [rails-sqlserver/tiny_tds#222]
I followed the instructions here: https://azure.microsoft.com/en-us/documentation/articles/sql-database-develop-ruby-simple-linux/

on 2 machines, both with rvm 1.26.10, Ruby 2.2.1p85.  Machine 1 had Ubuntu 14.04, and I connected to my azure database just fine.  Machine 2 has Ubuntu 10.04, and on that machine I get the error, "/client.rb:74: warning: TinyTds: Azure connections not supported in this version of FreeTDS".  Since the only difference I can detect is the versions of Ubuntu, could this be the problem?  I couldn't figure out how to detect the actual version of FreeTDS, and the freetds.conf files on both machines were identical.

Any assistance would be greatly appreciated.

**Comment by jenko** [comment]
I think I found the problem, I watched the install on Ubuntu 10.04 and it showed "freetds-common 0.82-6build1", and I know tiny_tdy requires 0.91.  I will close this and search elsewhere to see if 0.91 can be forced.

**Comment by metaskills** [comment]
Thanks for posting back!
