### ISSUE TITLE
Ubuntu 10.10 uses FreeTDS 0.82 which is incompatible w/Azure

### ISSUE THREAD

**Issue by jenko** [rails-sqlserver/tiny_tds#223]
I know it's pretty ancient at this point, but I have a box running Ubuntu 10.10 and when I do

sudo apt-get --assume-yes install freetds-dev freetds-bin

it installs FreeTDS 0.82, which doesn't have support for Azure connections.  Is there any way I can force it to use 9.1, or installed 9.1 some other way?

TIA

**Comment by metaskills** [comment]
So we have a new build system based on top of Miniportile which is actually used when you are doing a gem install too. We've done a good job at documenting these here and here:

* https://github.com/rails-sqlserver/tiny_tds#install
* https://github.com/rails-sqlserver/tiny_tds#using-miniportile

So something like this should work when installing the gem manually on your Ubuntu box.

```
$ TINYTDS_FREETDS_VERSION="0.92" gem install tiny_tds -- --disable-system-freetds --disable-system-iconv
```

**Comment by jenko** [comment]
Very cool! I'll give that a shot and get back.  Thanks again.

**Comment by jenko** [comment]
Ok, I tried that, and it says it successfully installed, and I tried my connection string (copied and pasted from the working machine) and got 

TinyTds::Error: Adaptive Server connection failed
        from /home/qe2user/.rvm/gems/ruby-2.2.1/gems/tiny_tds-0.7.0/lib/tiny_tds/client.rb:74:in `connect'
        from /home/qe2user/.rvm/gems/ruby-2.2.1/gems/tiny_tds-0.7.0/lib/tiny_tds/client.rb:74:in `initialize'
        from (irb):2:in `new'
        from (irb):2
        from /home/qe2user/.rvm/rubies/ruby-2.2.1/bin/irb:11:in `<main>'

this is a different error than I was getting before, no mention this time that the version of FreeTDS being used is incompatible w/Azure, so that's a step in the right direction.  Any ideas?

**Comment by metaskills** [comment]
Hmmm... I'm not sure the install you did is going to work for you. You need FreeTDS installed with OpenSSL when connecting to Azure and I can't remember the details of how we have this (https://github.com/rails-sqlserver/tiny_tds/blob/master/ext/tiny_tds/extconf.rb) setup to do that. Maybe it would help if you posted a full gist of the install output you did? Maybe use `--enable-system-openssl` too?

**Comment by jenko** [comment]
Ok, I'll try that.  I'm installing it again, this time I made sure I scoured the machine first (uninstalled the freetds libs that I'd previously installed as well as the gem). It's still going, last time it took about 20 min.  
Here's the gist with the full install output: https://gist.github.com/jenko/c5c7bdf8782f3865a7ce

**Comment by metaskills** [comment]
Darn... we should add some output to the recipes so we know what is doing what :(

**Comment by jenko** [comment]
Tried it with that openssl tweak, same thing. 

Oh well, I appreciate your efforts.  This'll teach me to do my (ubuntu) upgrades, I guess. :)

**Comment by metaskills** [comment]
Sorry... there could be a way. I think we have it on our list to allow OpenSSL full integration as well. We do this for the Windows builds. Could be fairly straight forward.

**Comment by jenko** [comment]
I'll try whatever you suggest, beats migrating just for this issue.  I'm all ears!

**Comment by larskanis** [comment]
For Windows the use of OpenSSL is enabled, because we build it in a non standard path (per MiniPortile). I thought, that on Linux/OS-X, the freetds configure script would enable OpenSSL per default (if it is in the standard paths). Unfortunately this is not the case. We probably should add a `--with-openssl` argument without a path for non-Windows builds in `extconf.rb` , to prefer OpenSSL-enabled builds. It's too late to try this today - will try tomorrow.

**Comment by metaskills** [comment]
Closing this in favor of the PR.
