### ISSUE TITLE
Does tiny_tds support FreeTDS's Connection Encryption attribute?

### ISSUE THREAD

**Issue by skingvht** [rails-sqlserver/tiny_tds#235]
I see on [FreeTDS's Connection documentation](http://www.freetds.org/userguide/odbcconnattr.htm) that there is an `Encryption` attribute, but have tried using it within tiny_tds and it appears that it is not being used. We have a SQL Server 2012 instance that needs to have the Connection Encryption option enabled and were hoping that by setting the `Encryption` attribute it would allow the connection from tiny_tds successfully. I've also searched through the source code to see if there is a way to pass that option, but am not finding anything. Thanks in advance for any assistance.

**Comment by metaskills** [comment]
1. Is your FreeTDS configured to use OpenSSL?
1. When you turn on mandatory encryption in SQL Server, does TinyTDS not connect?

**Comment by skingvht** [comment]
1. We're running on Windows with the devkit and native gems. Do we need to run a separate command to configure FreeTDS to use OpenSSL?
2. Yes. When we turn on mandatory encryption, TinyTDS returns an error "TinyTds::Error = Adaptive Server connection failed".

**Comment by metaskills** [comment]
The native Windows gems have OpenSSL configured by default.  Could you try the latest v0.7.0 version of TinyTDS?

**Comment by skingvht** [comment]
OK, I'll test v0.7.0 and provide an update here. Thanks again.

**Comment by skingvht** [comment]
Version v0.7.0 fixed this issue. Thanks for all your help!

**Comment by metaskills** [comment]
Glad to hear it!
