### ISSUE TITLE
Installing on OSX El Capitan. FreeTDS exists, but error is thrown.

### ISSUE THREAD

**Issue by Quasso** [rails-sqlserver/tiny_tds#237]
Hey guys,

Great job with this--lovely tool. I'd like to point out though that I had major issues figuring out what was going wrong with my install. 

I was relentlessly getting an error claiming FreeTDS wasn't installed--even though I was explicitly specifying its path.

In the end I figured out the problem, it was that I needed to explicitly specify that it was a 64-bit environment.

I used this for installation, with immediate success: sudo ARCHFLAGS="-arch x86_64" gem install tiny_tds

I just thought I'd like to point it out as I'm sure others have encountered this issue, and it may be something you're able to fix.

**Comment by metaskills** [comment]
Interesting, I did some tests over the weekend and was able to get things working. I wonder if this line here has anything to do with your issue. https://github.com/rails-sqlserver/tiny_tds/blob/master/ext/tiny_tds/extconf.rb#L1
