### ISSUE TITLE
Reduce Appveyor Warnings

### ISSUE THREAD

**Issue by metaskills** [rails-sqlserver/tiny_tds#238]
I'd like to see the Appveyor builds with less of these errors when compiling TinyTDS' extension.

```
warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
```

I read that we can bypass this by using `-std=c99`. @larskanis do you know where I can put that? I tried putting things in the extension tasks' `config_options`, but that did not work.

**Comment by larskanis** [comment]
@metaskills Shall I fix the warnings (add forward declarations for variables) or do you want to switch to c99? IMHO I would not change to c99, to be more portable.

**Comment by metaskills** [comment]
Based on the c99 recommendation, I think we could just ignore this.

**Comment by metaskills** [comment]
This is now done. Thanks so much @larskanis
