### ISSUE TITLE
CASE SQL Server statement

### ISSUE THREAD

**Issue by trekr5** [rails-sqlserver/tiny_tds#239]
Hi,

I've installed tiny_tds gem on a Ubuntu 14.04 box to connect to a  SQL Server database. I have read-only access to this database.

I have the followiing issue:-

Using tiny_tds to run this CASE expression:

        CASE 
		WHEN EC.EventContributionId IS NULL THEN 'Direct Donations' 
		ELSE 'Funding Pages' 
		END AS DonationCategory
        INTO #tmp
        FROM BB01.dbo.BB01_Donation X with (nolock)

When I try to run this expression using tiny_tds, I get an error. Essentially the question is can I run  this CASE expression using tiny_tds. If yes then please tell me how I can do this?

**Comment by trekr5** [comment]
Hi,

Apologies for not including the SELECT. The full expression is:-

      SELECT F.FUNDING AS CompanyName
      CASE 
      WHEN EC.EventContributionId IS NULL THEN 'Direct Donations' 
      ELSE 'Funding Pages' 
      END AS DonationCategory
      INTO #tmp
      FROM BB01.dbo.BB01_Donation X with (nolock)

And yes I can run this in Management Studio.

Would the best way to structure this in TinyTDS be:-

   sql = ["SELECT F.FUNDING FROM BB01.dbo.BB01_Donation X AS CompanyName", "CASE            WHEN...", "...."].join(' ')
sq1, sq2, sq3.... = client.execute(sql).each

Assistance would be much appreciated.

**Comment by metaskills** [comment]
It appears you are using an array of batches and expecting multiple result sets? If so, have you read the section of the readme that covers that? https://github.com/rails-sqlserver/tiny_tds#tinytdsresult-usage

Also, please be specific. If you run this:

```ruby
sql = <<-SQL
  SELECT F.FUNDING AS CompanyName
  CASE 
  WHEN EC.EventContributionId IS NULL THEN 'Direct Donations' 
  ELSE 'Funding Pages' 
  END AS DonationCategory
  INTO #tmp
  FROM BB01.dbo.BB01_Donation X with (no lock)
SQL

client.execute(sql).each
```

What are you not seeing that you expect and what errors. Your details are lacking and leads us to guess. Hope that helps.

**Comment by trekr5** [comment]
Hi,

Yes your assistance is much appreciated and you have pointed me in the right direction!

Regards

**Comment by metaskills** [comment]
Awesome, closing this issue then. Thanks too @sixfeetover
