### ISSUE TITLE
Trying to connect to SQL Server using tiny_tds fails with tds_init_winsock: WSAEnumProtocols failed with 10055

### ISSUE THREAD

**Issue by arliooper** [rails-sqlserver/tiny_tds#242]
I am trying to use tiny_tds to connect to a SQL Server Database from Windows 7 using Ruby. I am able to successfully do this using the 'DBI' gem, but when I try using tiny_tds gem I get the error listed below, any advice on how to resolve this would be greatly appreciated. A pretty thorough Google search has not helped:

irb(main):003:0> require 'tiny_tds'
=> true
irb(main):004:0> client = TinyTds::Client.new username: '!Reporting', password: 'password', host: 'host'
tds_init_winsock: WSAEnumProtocols failed with 10055 (WSAENOBUFS: No buffer space available.)
C:/Ruby200/lib/ruby/gems/2.0.0/gems/tiny_tds-0.7.0-x86-mingw32/lib/tiny_tds/client.rb:74: [BUG] Segmentation fault
ruby 2.0.0p647 (2015-08-18) [i386-mingw32]

-- Control frame information -----------------------------------------------
c:0021 p:---- s:0084 e:000083 CFUNC :connect
c:0020 p:0320 s:0080 e:000079 METHOD C:/Ruby200/lib/ruby/gems/2.0.0/gems/tiny_tds-0.7.0-x86-mingw32/lib/tiny_tds/client.rb:74 [FINISH]
c:0019 p:---- s:0076 e:000075 CFUNC :new
c:0018 p:0035 s:0072 e:000071 EVAL (irb):4 [FINISH]
c:0017 p:---- s:0070 e:000069 CFUNC :eval
c:0016 p:0024 s:0063 e:000062 METHOD C:/Ruby200/lib/ruby/2.0.0/irb/workspace.rb:86
c:0015 p:0025 s:0056 e:000054 METHOD C:/Ruby200/lib/ruby/2.0.0/irb/context.rb:380
c:0014 p:0022 s:0050 e:000049 BLOCK C:/Ruby200/lib/ruby/2.0.0/irb.rb:492
c:0013 p:0040 s:0042 e:000041 METHOD C:/Ruby200/lib/ruby/2.0.0/irb.rb:624
c:0012 p:0009 s:0037 e:000036 BLOCK C:/Ruby200/lib/ruby/2.0.0/irb.rb:489
c:0011 p:0118 s:0033 e:000032 BLOCK C:/Ruby200/lib/ruby/2.0.0/irb/ruby-lex.rb:247 [FINISH]
c:0010 p:---- s:0030 e:000029 CFUNC :loop
c:0009 p:0007 s:0027 e:000026 BLOCK C:/Ruby200/lib/ruby/2.0.0/irb/ruby-lex.rb:233 [FINISH]
c:0008 p:---- s:0025 e:000024 CFUNC :catch
c:0007 p:0015 s:0021 e:000020 METHOD C:/Ruby200/lib/ruby/2.0.0/irb/ruby-lex.rb:232
c:0006 p:0030 s:0018 E:002134 METHOD C:/Ruby200/lib/ruby/2.0.0/irb.rb:488
c:0005 p:0008 s:0015 e:000014 BLOCK C:/Ruby200/lib/ruby/2.0.0/irb.rb:397 [FINISH]
c:0004 p:---- s:0013 e:000012 CFUNC :catch
c:0003 p:0143 s:0009 E:0017e4 METHOD C:/Ruby200/lib/ruby/2.0.0/irb.rb:396
c:0002 p:0031 s:0004 E:001ea4 EVAL C:/Ruby200/bin/irb:12 [FINISH]
c:0001 p:0000 s:0002 E:000bfc TOP [FINISH]

C:/Ruby200/bin/irb:12:in <main>'

C:/Ruby200/lib/ruby/2.0.0/irb.rb:396:instart'
C:/Ruby200/lib/ruby/2.0.0/irb.rb:396:in catch'

C:/Ruby200/lib/ruby/2.0.0/irb.rb:397:inblock in start'
C:/Ruby200/lib/ruby/2.0.0/irb.rb:488:in eval_input'

C:/Ruby200/lib/ruby/2.0.0/irb/ruby-lex.rb:232:ineach_top_level_statement'
C:/Ruby200/lib/ruby/2.0.0/irb/ruby-lex.rb:232:in catch'

C:/Ruby200/lib/ruby/2.0.0/irb/ruby-lex.rb:233:inblock in each_top_level_statement'
C:/Ruby200/lib/ruby/2.0.0/irb/ruby-lex.rb:233:in loop'

C:/Ruby200/lib/ruby/2.0.0/irb/ruby-lex.rb:247:inblock (2 levels) in each_top_level_statement'
C:/Ruby200/lib/ruby/2.0.0/irb.rb:489:in block in eval_input'

C:/Ruby200/lib/ruby/2.0.0/irb.rb:624:insignal_status'
C:/Ruby200/lib/ruby/2.0.0/irb.rb:492:in block (2 levels) in eval_input'

C:/Ruby200/lib/ruby/2.0.0/irb/context.rb:380:inevaluate'
C:/Ruby200/lib/ruby/2.0.0/irb/workspace.rb:86:in evaluate'

C:/Ruby200/lib/ruby/2.0.0/irb/workspace.rb:86:ineval'
(irb):4:in irb_binding'

(irb):4:innew'
C:/Ruby200/lib/ruby/gems/2.0.0/gems/tiny_tds-0.7.0-x86-mingw32/lib/tiny_tds/client.rb:74:in initialize'

C:/Ruby200/lib/ruby/gems/2.0.0/gems/tiny_tds-0.7.0-x86-mingw32/lib/tiny_tds/client.rb:74:inconnect'

-- C level backtrace information -------------------------------------------
C:\WINDOWS\SYSTEM32\ntdll.dll(KiFastSystemCallRet+0x0) [0x77B371B4]
C:\WINDOWS\system32\kernel32.dll(WaitForSingleObjectEx+0x43) [0x7696C413]
C:\WINDOWS\system32\kernel32.dll(WaitForSingleObject+0x12) [0x7696C3C2]
C:\Ruby200\bin\msvcrt-ruby200.dll(rb_vm_bugreport+0xa7) [0x66903317]
C:\Ruby200\bin\msvcrt-ruby200.dll(rb_name_err_mesg_new+0x69d) [0x667C131D]
C:\Ruby200\bin\msvcrt-ruby200.dll(rb_bug+0x2e) [0x667C213E]
C:\Ruby200\bin\msvcrt-ruby200.dll(rb_check_safe_str+0x37a) [0x6688636A]
[0x00401866]
C:\WINDOWS\SYSTEM32\ntdll.dll(EtwReplyNotification+0x366) [0x77B6820A]

-- Other runtime information -----------------------------------------------

Loaded script: irb

Loaded features:

0 enumerator.so
1 C:/Ruby200/lib/ruby/2.0.0/i386-mingw32/enc/encdb.so
2 C:/Ruby200/lib/ruby/2.0.0/i386-mingw32/enc/iso_8859_1.so
3 C:/Ruby200/lib/ruby/2.0.0/i386-mingw32/enc/trans/transdb.so
4 C:/Ruby200/lib/ruby/2.0.0/i386-mingw32/rbconfig.rb
5 C:/Ruby200/lib/ruby/2.0.0/rubygems/compatibility.rb
6 C:/Ruby200/lib/ruby/2.0.0/rubygems/defaults.rb
7 C:/Ruby200/lib/ruby/2.0.0/rubygems/deprecate.rb
8 C:/Ruby200/lib/ruby/2.0.0/rubygems/errors.rb
9 C:/Ruby200/lib/ruby/2.0.0/rubygems/version.rb
10 C:/Ruby200/lib/ruby/2.0.0/rubygems/requirement.rb
11 C:/Ruby200/lib/ruby/2.0.0/rubygems/platform.rb
12 C:/Ruby200/lib/ruby/2.0.0/rubygems/specification.rb
13 C:/Ruby200/lib/ruby/2.0.0/rubygems/exceptions.rb
14 C:/Ruby200/lib/ruby/2.0.0/rubygems/defaults/operating_system.rb
15 C:/Ruby200/lib/ruby/2.0.0/i386-mingw32/enc/utf_16le.so
16 C:/Ruby200/lib/ruby/2.0.0/i386-mingw32/enc/trans/utf_16_32.so
17 C:/Ruby200/lib/ruby/2.0.0/rubygems/core_ext/kernel_gem.rb
18 C:/Ruby200/lib/ruby/2.0.0/thread.rb
19 C:/Ruby200/lib/ruby/2.0.0/monitor.rb
20 C:/Ruby200/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb
21 C:/Ruby200/lib/ruby/2.0.0/rubygems.rb
22 C:/Ruby200/lib/ruby/2.0.0/e2mmap.rb
23 C:/Ruby200/lib/ruby/2.0.0/irb/init.rb
24 C:/Ruby200/lib/ruby/2.0.0/irb/workspace.rb
25 C:/Ruby200/lib/ruby/2.0.0/irb/inspector.rb
26 C:/Ruby200/lib/ruby/2.0.0/irb/context.rb
27 C:/Ruby200/lib/ruby/2.0.0/irb/extend-command.rb
28 C:/Ruby200/lib/ruby/2.0.0/irb/output-method.rb
29 C:/Ruby200/lib/ruby/2.0.0/irb/notifier.rb
30 C:/Ruby200/lib/ruby/2.0.0/irb/slex.rb
31 C:/Ruby200/lib/ruby/2.0.0/irb/ruby-token.rb
32 C:/Ruby200/lib/ruby/2.0.0/irb/ruby-lex.rb
33 C:/Ruby200/lib/ruby/2.0.0/irb/src_encoding.rb
34 C:/Ruby200/lib/ruby/2.0.0/irb/magic-file.rb
35 C:/Ruby200/lib/ruby/2.0.0/i386-mingw32/enc/euc_jp.so
36 C:/Ruby200/lib/ruby/2.0.0/i386-mingw32/enc/windows_31j.so
37 C:/Ruby200/lib/ruby/site_ruby/2.0.0/rbreadline/version.rb
38 C:/Ruby200/lib/ruby/2.0.0/i386-mingw32/etc.so
39 C:/Ruby200/lib/ruby/2.0.0/i386-mingw32/enc/trans/single_byte.so
40 C:/Ruby200/lib/ruby/2.0.0/i386-mingw32/fiddle.so
41 C:/Ruby200/lib/ruby/2.0.0/fiddle/function.rb
42 C:/Ruby200/lib/ruby/2.0.0/fiddle/closure.rb
43 C:/Ruby200/lib/ruby/2.0.0/fiddle.rb
44 C:/Ruby200/lib/ruby/site_ruby/2.0.0/rbreadline.rb
45 C:/Ruby200/lib/ruby/site_ruby/2.0.0/readline.rb
46 C:/Ruby200/lib/ruby/2.0.0/irb/input-method.rb
47 C:/Ruby200/lib/ruby/2.0.0/irb/locale.rb
48 C:/Ruby200/lib/ruby/2.0.0/irb.rb
49 C:/Ruby200/lib/ruby/2.0.0/rubygems/path_support.rb
50 C:/Ruby200/lib/ruby/2.0.0/rubygems/dependency.rb
51 C:/Ruby200/lib/ruby/2.0.0/i386-mingw32/date_core.so
52 C:/Ruby200/lib/ruby/2.0.0/date/format.rb
53 C:/Ruby200/lib/ruby/2.0.0/date.rb
54 C:/Ruby200/lib/ruby/2.0.0/i386-mingw32/bigdecimal.so
55 C:/Ruby200/lib/ruby/gems/2.0.0/gems/tiny_tds-0.7.0-x86-mingw32/lib/tiny_tds/version.rb
56 C:/Ruby200/lib/ruby/gems/2.0.0/gems/tiny_tds-0.7.0-x86-mingw32/lib/tiny_tds/error.rb
57 C:/Ruby200/lib/ruby/gems/2.0.0/gems/tiny_tds-0.7.0-x86-mingw32/lib/tiny_tds/client.rb
58 C:/Ruby200/lib/ruby/gems/2.0.0/gems/tiny_tds-0.7.0-x86-mingw32/lib/tiny_tds/result.rb
59 C:/Ruby200/lib/ruby/gems/2.0.0/gems/tiny_tds-0.7.0-x86-mingw32/lib/tiny_tds/2.0/tiny_tds.so
60 C:/Ruby200/lib/ruby/gems/2.0.0/gems/tiny_tds-0.7.0-x86-mingw32/lib/tiny_tds.rb

**Comment by metaskills** [comment]
What does your connection params look like? Are you using a named instance like `localhost\SQLEXPRESS`? If so, can you try the direct TCP IP/PORT?
