### ISSUE TITLE
TinyTDS doesn't close connections

### ISSUE THREAD

**Issue by atomical** [rails-sqlserver/tiny_tds#243]
I'm checking the open connections and even though I use close each time I call TinyTDS, the connections do not appear to be closing. This is on ruby-2.1.6.

 `netstat -atn | grep 1433 | wc -l`

**Comment by metaskills** [comment]
Hmmm... I see the opposite, works just fine. Tried on a few different Ruby versions as well as FreeTDS 0.91 and 0.95 latest. We are using the FreeTDS interface `dbclose` when you call the Ruby method. There is not a lot that can go wrong there. Could you investigate more on your end? You able to keep using the client's connection even tho you called close on it? What platform are you on?

**Comment by metaskills** [comment]
Closing issue, no pun intended :) But please let me know if you see something that warrants action or if I missed something.
