### ISSUE TITLE
TinyTds::Error: Adaptive Server connection failed trying to reach an Azure db

### ISSUE THREAD

**Issue by jenko** [rails-sqlserver/tiny_tds#247]
I have 2 virtualbox virtual machines running on separate win7pro boxes, both running 
  Ubuntu 14.04.3 LTS
  ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]
  tiny_tds gem 0.7.0

both machines, 
  are running with windows firewall is turned off for all networks
  are on the same internal subnet, so both are seen as the same (external) IP by Azure

On one machine, the following command works fine:

@azure_client = TinyTds::Client.new username: 'username@hostname', password: 'myPassword',
                                   host: 'hostname.database.windows.net', port: 1433,
                                   database: 'myDatabase', azure:true

on the other, I get the following error: 
     Adaptive Server connection failed
            from /home/qe2user/.rvm/gems/ruby-2.2.1/gems/tiny_tds-0.7.0/lib/tiny_tds/client.rb:74:in `connect'
            from /home/qe2user/.rvm/gems/ruby-2.2.1/gems/tiny_tds-0.7.0/lib/tiny_tds/client.rb:74:in `initialize'
            from (irb):2:in `new'
            from (irb):2
            from /home/qe2user/.rvm/rubies/ruby-2.2.1/bin/irb:11:in `<main>'

Known differences: 
1. the vm that works is ubuntudesktop, the one that doesn't is server

Both machines were set up according to the instructions here:
https://azure.microsoft.com/en-us/documentation/articles/sql-database-develop-ruby-simple-linux/

both vm's versions of /etc/freetds/freetds.conf appear identical, but I have attached them anyway just in case.

I do not know what else to check/try.  Any assistance would be greatly appreciated.

Thank you.

[freetds.conf_from_NON_working_machine.txt](https://github.com/rails-sqlserver/tiny_tds/files/54321/freetds.conf_from_NON_working_machine.txt)
[freetds.conf_from_working_machine.txt](https://github.com/rails-sqlserver/tiny_tds/files/54322/freetds.conf_from_working_machine.txt)

**Comment by TigerMint** [comment]
I've seen this error before cause I accidentally install/bundle tiny_tds prior to installing freeTDS and I uninstalled the tiny_gem and reinstalled it which fixed the problem.

**Comment by jenko** [comment]
@TigerMint That did it!  THANK YOU!
