### ISSUE TITLE
TinyTds::Error: Write to the server failed

### ISSUE THREAD

**Issue by vin-yu** [rails-sqlserver/tiny_tds#249]
I’ve setup tiny_tds for my Rails app on Windows and when trying to run rake db:migrate or any other commands, each time the same command would fail with either:

rake aborted!
TinyTds::Error: Write to the server failed
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/tiny_tds-0.7.0-x64-mingw32/lib/tiny_tds/client.rb:74:in `connect'
Or,
TinyTds::Error: Read from the server failed

The tiny_tds (and the FreeTds comes with it) does work when running 
Client = TinyTds::Client.new ( connection properties )
Client.execute (some query)

Also tried installed the FreeTds for Windows and reinstalled tiny_tds with gem install tiny_tds -- --with-freetds-dir=C:\freetds-0.95rc2.

Still running into the same issue.

Additional info:

Database.yml:
development:
  adapter: sqlserver
  mode: dblib
  host: servername.database.windows.net
  database: databasename
  pool: 5
  timeout: 120000
  port: 1433
  username: mylogin@servername
  password: password
  azure: true
  tds_version: 7.3 

The environment I have is,
Windows 2012 R2
ruby (2.2.3p173)
rails (4.2.5)
tiny_tds (0.7.0)
activerecord-sqlserver-adapter (4.2.6, 4.2.4)

Couple questions,
[1] How do I know TinyTds is using which FreeTds? The one comes with the gem or the one I installed?
[2] I can connect and execute query via FreeTds and TinyTds. The test program also works. How else I can troubleshoot?  

thank you in advance for the help

**Comment by metaskills** [comment]
Hey Vin, compiling your own FreeTDS will likely have a few errors. This project has a few patches that are needed. See here https://github.com/rails-sqlserver/tiny_tds/tree/master/ports/patches/freetds So if you want to use master, then building your own from latest using our tool (or bundler) is preferred.

> [1] How do I know TinyTds is using which FreeTds?

Any windows gem has extensions pre-build which have statically linked versions of FreeTDS, etc. For the 0.7.0 version, this is FreeTDS 0.91.112. See the following two links for more details.

* https://github.com/rails-sqlserver/tiny_tds#install
* https://github.com/rails-sqlserver/tiny_tds/blob/v0.7.0/ext/tiny_tds/extconf.rb#L17-L22

> [2] I can connect and execute query via FreeTds and TinyTds.

It sounds like you are having a config issue with your Rails app. Nothing related to TinyTDS. Likely with your database.yml, Gemfile, etc. I would have to see much more to help. But I would first look at your database.yml and go from there. Knowing what Rails, adapter version and what is in your Gemfile(.lock) helps too.

**Comment by metaskills** [comment]
How did Ruby get on your system? I believe our Appveyor tests leverage DevKit and the RubyInstaller project http://rubyinstaller.org and all the tests are passing for each DB including Azure. So what would be different about your env?

**Comment by TigerMint** [comment]
we used the Ruby 2.2.3 (x64) and DevKit from http://rubyinstaller.org/downloads/.    
Gemlock FIle here:http://pastebin.com/DJ1hkkSY tried with Rails 4.2.2 and 4.2.5. 

i'll take a look at the tests and replicate that environment

**Comment by metaskills** [comment]
Thanks... forgot you said that TInyTDS works fine and that the Rails rake task does not. Can you show me a pastebin of the full stack trace from that rake error?

**Comment by TigerMint** [comment]
I think it is some connection configuration issue. I can enter the wrong password, user name server, etc and the same error would be returned. here is the pastebin: http://pastebin.com/47uxXNdn. Thanks for the help.

**Comment by metaskills** [comment]
Yup config issue. Try removing `database: databasename` from your DB yaml. Also remove `tds_version: 7.3`.

**Comment by TigerMint** [comment]
updated database.yml to the following but still running into the same issue: 

default: &default
  adapter: sqlserver
  encoding: utf8
  reconnect: false
  username: login@servername
  password: pw
  timeout: 100000
  host: servername.database.windows.net
  azure: true


development:
  <<: *default

**Comment by TigerMint** [comment]
I added a simple print statement just to see what options (opts{}) are being passed within the tiny_tds/lib/tiny_tds/client.rb:

The Rails app w/ database.yml

[:dataserver, "server.database.windows.net:1433"] => 0
[:host, "server.database.windows.net"] => 1
[:port, 1433] => 2
[:username, "login@server"] => 3
[:password, "pw"] => 4
[:database, nil] => 5
[:tds_version, 5] => 6
[:appname, "appname"] => 7
[:login_timeout, 60] => 8
[:timeout, 100] => 9
[:encoding, "UTF-8"] => 10
[:azure, true] => 11

using irb which works!

client = TinyTds::Client.new username: 'login@server', password: 'pw', host: 'server.database.windows.net' 

[:username, "login@server"] => 0
[:password, "pw"] => 1
[:host, "server.database.windows.net"] => 2
[:appname, "TinyTds"] => 3
[:tds_version, 5] => 4
[:login_timeout, 60] => 5
[:timeout, 5] => 6
[:encoding, "UTF-8"] => 7
[:port, 1433] => 8
[:dataserver, "server.database.windows.net:1433"] => 9


the only thing i see that is different is the azure field and the database field which I also played around with.

**Comment by metaskills** [comment]
Thanks Vin for going thru this... I think we are close. Attacking this with the two different I think is the right path. A few points/questions:

* Does the raw TinyTds client test work when only `azure: true` is added? I am somewhat surprised it did?
* Now does the raw TinyTds client still work when you added `database: nil`?

**Comment by TigerMint** [comment]
client = TinyTds::Client.new username: 'login@server', password: 'pw', host: 'server.database.windows.net', azure: 'true', database: nil

works and results in:

[:username, "login@server"] => 0
[:password, "pw"] => 1
[:host, "server.database.windows.net"] => 2
[:azure, "true"] => 3
[:database, nil] => 4
[:appname, "TinyTds"] => 5
[:tds_version, 5] => 6
[:login_timeout, 60] => 7
[:timeout, 5] => 8
[:encoding, "UTF-8"] => 9
[:port, 1433] => 10
[:dataserver, "server.database.windows.net:1433"] => 11

=> #<TinyTds::Client:0x000000022acb30 @query_options={:as=>:hash, :symbolize_keys=>false, :cache_rows=>true, :timezone=>:local, :empty_sets=>true}>
irb(main):004:0>


-----------------
but on a side note:
client = TinyTds::Client.new username: 'login@server', password: 'pw', host: 'server.database.windows.net', azure: 'true', database: "databasename"

errors out with:

results in: TinyTds::Error: USE statement is not supported to switch between databases. Use a new connection to connect to a different database.

**Comment by metaskills** [comment]
So `azure: 'true'` is wrong. You are passing a string with `true` in it. You need to send a proper `true` value of `TrueClass`, not a `String`. Also, database has to be `nil`. Just remove it from your yaml

**Comment by TigerMint** [comment]
ok, passed in true boolean for the irb example and removed db from yml. same problem occurs.

**Comment by YvesR** [comment]
Hello @metaskills ,
I run into same situation.

Use 
- ruby 2.0.0p598
- rails 4.2.5
- tiny_tds 0.9.5.beta.11
- activerecord-sqlserver-adapter 4.2.3

IRB console with script works. I can connect and fetch data.
Using rake command => 'Connect': Write to server failed
Using rails console => 'Connect': Write to server failed

I checked the client.rb and the sqlserver_adapter.rb and commented some parameters. Always same results.
Info: Copied the client.execute commands from the adapter to my script to execute the SET statements. They all work fine in the IRB script.

While running IRB script I can see a connection on Azure.
When I do "rails c" I never get any connection on Azure.
Using those statements to monitor: https://azure.microsoft.com/en-us/documentation/articles/sql-database-monitoring-with-dmvs/

I run on same machine a small .NET test program to create table, columns and insert data to make sure the credentials are ok and all other settings work as expected.

Do you have a Azure SQL DB to test for yourself? If not, you can contact me and I can provide you one for testing. I really need to get this fixed! 

Thank you.

**Comment by metaskills** [comment]
> Do you have a Azure SQL DB to test for yourself? If not, you can contact me and I can provide you one for testing. I really need to get this fixed!

Yes, thanks to the fine folks at Microsoft. I just started doing some foundation work in the 4-2-stable branch of the adapter for Azure and if this is very common, I suspect I will hit the issue very soon, within the next few days. Will report back, hope you do the same.

**Comment by metaskills** [comment]
OK, I have a handle on this issue now. Please track the progress on the adapter issue here https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/issues/446

**Comment by metaskills** [comment]
Re-opening since I am not sure if the issue is with TinyTDS, Adapter, or Other Gems.

**Comment by metaskills** [comment]
Related, could be our error handler. https://github.com/rails-sqlserver/tiny_tds/blob/master/ext/tiny_tds/client.c#L83-L89

But I still think this has something to do with a static OpenSSL in another gem since I only see this when rails/all is required.
