### ISSUE TITLE
Fix Windows Datetimeoffset Rational Numerator

### ISSUE THREAD

**Issue by metaskills** [rails-sqlserver/tiny_tds#254]
When casting the datetimeoffset object, we need to provide a Rational that holds both the seconds and nanoseconds. For our test, the numbers would be something like the following which is given to Time.new.

```ruby
Rational(59123456700, 1000000000)
```

For the past few days I have been trying to figure out why the Windows builds have been giving me an argument out of range error. I finally figured out thru some debugging that this value is not being converted properly on Windows. For example:

```c
long numerator = 59123456700;
rb_warn("numerator: %"LONG_LONG_FORMAT, numerator);
```

Produces a consistent cross platform positive result. However, this does not:

```c
long numerator = 59123456700;
rb_warn("LONG2NUM(numerator): %"PRIsVALUE, LONG2NUM(numerator));
```

For some reason on the Windows builds, this comes out to `-1006085444`.

cc @larskanis

**Comment by metaskills** [comment]
I am currently testing this on the Appveyor build now.

```c
unsigned long long int numerator = 59123456700;
rb_warn("LONG2NUM(numerator): %"PRIsVALUE, LONG2NUM(numerator));
```

FWIW, I can get my darwin platform to make `-1006085444` if I change the above `LONG2NUM` to `INT2NUM`. I wonder if the core issue is with `LONG2NUM` on windows?

**Comment by metaskills** [comment]
OK... I think I fixed this with the following. Basically LL2NUM FTW.

```c
long long numerator = 59123456700;
rb_warn("LL2NUM(numerator): %"PRIsVALUE, LL2NUM(numerator));
```

**Comment by larskanis** [comment]
Yes, LL2NUM must be used on Windows to convert 64 bit values. Unfortunately long is only 32 bit on Windows, even on 64 bit systems. And the printf() on Windows is not fully ANSI compatible - that's why I defined LONG_LONG_FORMAT for cross platform compatibility..
