### ISSUE TITLE
Update default FREETDS_VERSION

### ISSUE THREAD

**Issue by l8nite** [rails-sqlserver/tiny_tds#258]
Following up from https://github.com/rails-sqlserver/tiny_tds/pull/257
The freetds maintainer has patched, and I'd like to have tiny_tds pick up the change.

**Comment by metaskills** [comment]
Could you confirm that work is in the 0.95 and 0.99 branches? If so, we can bump this number here https://github.com/rails-sqlserver/tiny_tds/blob/master/ext/tiny_tds/extconsts.rb#L8 to the latest 0.95.xx

**Comment by l8nite** [comment]
Yea, I'll try to run a test on Monday -- heading to Tahoe for the weekend :snowboarder:

**Comment by metaskills** [comment]
Have fun! I confirmed that 0.95.80 and 0.99.latest have the patches you needed. Glad you sorted it out on FreeTDS's end cause their solution seemed much stronger. This work is in master, but you can find it in our 0.9.5.beta.11 gem (published later today) and up if needed. Cheers!

**Comment by l8nite** [comment]
Nice, thanks!
