### ISSUE TITLE
Date conversion error not caught

### ISSUE THREAD

**Issue by oneiros** [rails-sqlserver/tiny_tds#259]
I have no idea if this is even a tiny_tds bug and sorry, I have probably no way to reproduce this. Still, I would like to leave this here in case it is something obvious you can easily fix. Feel free to close this if it is not the case.

I encountered an issue with a rails app using the sqlserver-adapter (version 4.1.0). It just froze upon certain user inputs. When I finally got around to enable logging in freetds, the problem became obvious.

The user had a typo in a date field. The date was parsed by rails as something in the year 208. And this in turn was rejected by the MSSQL server. This is an excerpt from the freetds log file:

    dbutil.c:87:msgno 8114: "Error converting data type varchar to datetime."

For some reason, this error never bubbled up into my app, so it just waited forever for the INSERT to finish.

**Comment by metaskills** [comment]
I'm going to need a lot more to go on here please.

**Comment by oneiros** [comment]
> I'm going to need a lot more to go on here please.

I am so sorry. I accidentally hit enter. I did not even know github let's you create completely empty issues... *sigh*

**Comment by metaskills** [comment]
Thanks, I am not sure where to go with this either. TinyTDS does have a solid error handler and message handler. This one is an obvious message, number 8114, which could have had a matching error (or should) that causes TinyTDS to report an exception to the adapter. I'm going to close this issue, but feel free to drop more info if any comes along. Please also try the latest 0.9.5 prerelease versions too and let me know what version of TinyTDS the error happened under.
