### ISSUE TITLE
RakeCompilerDock::DockerIsNotAvailable

### ISSUE THREAD

**Issue by metaskills** [rails-sqlserver/tiny_tds#261]
@larskanis This started happening today. I re-installed boot2docker (v1.8) and can't get past this. Any advice?

```
Using above environment variables for starting rake-compiler-dock.
rake aborted!
RakeCompilerDock::DockerIsNotAvailable: Docker is not available
/Users/kencollins/Repositories/tiny_tds/Rakefile:96:in `block in <top (required)>'
Tasks: TOP => gem:windows
(See full trace by running task with --trace)
boot2docker is installed and started, but 'docker version' failed.

    Please copy and paste above environment variables to your terminal
    and check why 'docker version' fails.
    You might need to re-init with 'boot2docker delete'
    or have a look at the FAQs: http://git.io/vtDBH
```

**Comment by metaskills** [comment]
OK, I have re-installed v1.7.1 and things seem to be working now...

**Comment by larskanis** [comment]
Not sure, what the root cause for above error could be. However since boot2docker is deprecated now, I have added support for docker-machine since rake-compiler-dock-0.5.0, as well. There's no need to switch, if boot2docker works for you - but if not, you have a second chance.

**Comment by metaskills** [comment]
The boot2docker stuff did work, sticking with it for now :)
