### ISSUE TITLE
#Destroy returns error

### ISSUE THREAD

**Issue by RobWu** [rails-sqlserver/tiny_tds#263]
I try to destroy an object..

Always get error:

> The request failed to run because the batch is aborted, this can be caused by abort signal sent from client, or another request is running in the same session, which makes the session busy.

Object is simple relation object between Contact & FavoriteCinema
```ruby 
ContactFavoriteCinema Load (16.2ms)  EXEC sp_executesql N'SELECT  [contact_favoritecinema].* FROM [contact_favoritecinema]  ORDER BY [contact_favoritecinema].[contactid] ASC OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY'
 => #<ActiveRecord::Relation [#<ContactFavoriteCinema contactid: 23, favoritecinemaid: 17>]>
```

I can create new objects.. but can not destroy.

App backtrace
-------------

 - app/controllers/api/contact_favorite_cinemas_controller.rb:18:in `destroy'

Full backtrace
--------------

 - activerecord-sqlserver-adapter (4.2.6) lib/active_record/connection_adapters/sqlserver/database_statements.rb:300:in `raw_connection_do'
 - activerecord-sqlserver-adapter (4.2.6) lib/active_record/connection_adapters/sqlserver/database_statements.rb:253:in `block in do_execute'
 - activerecord (4.2.5.1) lib/active_record/connection_adapters/abstract_adapter.rb:472:in `block in log'
 - activesupport (4.2.5.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
 - activerecord (4.2.5.1) lib/active_record/connection_adapters/abstract_adapter.rb:466:in `log'
 - activerecord-sqlserver-adapter (4.2.6) lib/active_record/connection_adapters/sqlserver/database_statements.rb:253:in `do_execute'
 - activerecord-sqlserver-adapter (4.2.6) lib/active_record/connection_adapters/sqlserver/database_statements.rb:69:in `exec_rollback_db_transaction'
 - activerecord (4.2.5.1) lib/active_record/connection_adapters/abstract/database_statements.rb:266:in `rollback_db_transaction'
 - activerecord (4.2.5.1) lib/active_record/connection_adapters/abstract/query_cache.rb:14:in `rollback_db_transaction'
 - activerecord (4.2.5.1) lib/active_record/connection_adapters/abstract/transaction.rb:145:in `rollback'
 - activerecord (4.2.5.1) lib/active_record/connection_adapters/abstract/transaction.rb:179:in `rollback_transaction'
 - activerecord (4.2.5.1) lib/active_record/connection_adapters/abstract/transaction.rb:186:in `rescue in within_new_transaction'
 - activerecord (4.2.5.1) lib/active_record/connection_adapters/abstract/transaction.rb:201:in `within_new_transaction'
 - activerecord (4.2.5.1) lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
 - activerecord (4.2.5.1) lib/active_record/transactions.rb:220:in `transaction'
 - activerecord (4.2.5.1) lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
 - activerecord (4.2.5.1) lib/active_record/transactions.rb:281:in `destroy'
 - app/controllers/api/contact_favorite_cinemas_controller.rb:18:in `destroy'
 - actionpack (4.2.5.1) lib/abstract_controller/base.rb:198:in `process_action'
 - actionpack (4.2.5.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
 - activesupport (4.2.5.1) lib/active_support/callbacks.rb:117:in `call'
 - activesupport (4.2.5.1) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
 - activesupport (4.2.5.1) lib/active_support/callbacks.rb:505:in `call'
 - activesupport (4.2.5.1) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
 - activesupport (4.2.5.1) lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
 - activesupport (4.2.5.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
 - actionpack (4.2.5.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
 - actionpack (4.2.5.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
 - activesupport (4.2.5.1) lib/active_support/notifications.rb:164:in `block in instrument'
 - activesupport (4.2.5.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
 - activesupport (4.2.5.1) lib/active_support/notifications.rb:164:in `instrument'
 - actionpack (4.2.5.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
 - actionpack (4.2.5.1) lib/abstract_controller/base.rb:137:in `process'
 - actionpack (4.2.5.1) lib/action_controller/metal.rb:196:in `dispatch'
 - actionpack (4.2.5.1) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
 - actionpack (4.2.5.1) lib/action_controller/metal.rb:234:in `block in action'
 - newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
 - airbrake (4.3.5) lib/airbrake/rack.rb:46:in `call'
 - newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
 - actionpack (4.2.5.1) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
 - actionpack (4.2.5.1) lib/action_dispatch/routing/route_set.rb:43:in `serve'
 - actionpack (4.2.5.1) lib/action_dispatch/journey/router.rb:43:in `block in serve'
 - actionpack (4.2.5.1) lib/action_dispatch/journey/router.rb:30:in `serve'
 - actionpack (4.2.5.1) lib/action_dispatch/routing/route_set.rb:815:in `call'
 - newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
 - newrelic_rpm (3.14.1.311) lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
 - newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
 - newrelic_rpm (3.14.1.311) lib/new_relic/rack/browser_monitoring.rb:32:in `traced_call'
 - newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
 - newrelic_rpm (3.14.1.311) lib/new_relic/rack/developer_mode.rb:48:in `traced_call'
 - newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
 - rack (1.6.4) lib/rack/etag.rb:24:in `call'
 - newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
 - rack (1.6.4) lib/rack/conditionalget.rb:38:in `call'
 - newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
 - rack (1.6.4) lib/rack/head.rb:13:in `call'
 - newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
 - actionpack (4.2.5.1) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
 - newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
 - actionpack (4.2.5.1) lib/action_dispatch/middleware/flash.rb:260:in `call'
 - newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
 - rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
 - rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
 - newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
 - actionpack (4.2.5.1) lib/action_dispatch/middleware/cookies.rb:560:in `call'
 - newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
 - activerecord (4.2.5.1) lib/active_record/query_cache.rb:36:in `call'
 - newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
 - activerecord (4.2.5.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
 - newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
 - activerecord (4.2.5.1) lib/active_record/migration.rb:377:in `call'
 - newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
 - actionpack (4.2.5.1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
 - activesupport (4.2.5.1) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
 - activesupport (4.2.5.1) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
 - activesupport (4.2.5.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
 - actionpack (4.2.5.1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
 - newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
 - actionpack (4.2.5.1) lib/action_dispatch/middleware/reloader.rb:73:in `call'
 - newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
 - actionpack (4.2.5.1) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
 - newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
 - airbrake (4.3.5) lib/airbrake/rails/middleware.rb:13:in `call'
 - newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
 - better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
 - better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
 - better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
 - newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
 - actionpack (4.2.5.1) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
 - newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
 - web-console (2.2.1) lib/web_console/middleware.rb:39:in `call'
 - newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
 - actionpack (4.2.5.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
 - newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
 - railties (4.2.5.1) lib/rails/rack/logger.rb:38:in `call_app'
 - railties (4.2.5.1) lib/rails/rack/logger.rb:20:in `block in call'
 - activesupport (4.2.5.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
 - activesupport (4.2.5.1) lib/active_support/tagged_logging.rb:26:in `tagged'
 - activesupport (4.2.5.1) lib/active_support/tagged_logging.rb:68:in `tagged'
 - railties (4.2.5.1) lib/rails/rack/logger.rb:20:in `call'
 - newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
 - actionpack (4.2.5.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
 - newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
 - rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
 - newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
 - rack (1.6.4) lib/rack/runtime.rb:18:in `call'
 - newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
 - activesupport (4.2.5.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
 - newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
 - rack (1.6.4) lib/rack/lock.rb:17:in `call'
 - newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
 - actionpack (4.2.5.1) lib/action_dispatch/middleware/static.rb:116:in `call'
 - newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
 - rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
 - newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
 - airbrake (4.3.5) lib/airbrake/user_informer.rb:16:in `_call'
 - airbrake (4.3.5) lib/airbrake/user_informer.rb:12:in `call'
 - newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
 - railties (4.2.5.1) lib/rails/engine.rb:518:in `call'
 - railties (4.2.5.1) lib/rails/application.rb:165:in `call'
 - newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
 - rack (1.6.4) lib/rack/lock.rb:17:in `call'
 - rack (1.6.4) lib/rack/content_length.rb:15:in `call'
 - rack (1.6.4) lib/rack/handler/webrick.rb:88:in `service'
 - /Users/row/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
 - /Users/row/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
 - /Users/row/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'

**Comment by metaskills** [comment]
Pretty sure there is no "destroy" but in TinyTDS. We only send SQL to execute. Are you sure you user that you are contesting with can DELETE? I suggest debugging more on your side. We test TinyTDS  even in ActiveRecord and all tests are green. That includes a TON of destroys. 

Sorry. I'll need a lot more to go on to help with debugging this. So far I don't see anything.

**Comment by RobWu** [comment]
Problems was a record in a table without primary key. As was a relation-table containing only foreign-keys to two other tables..
