### ISSUE TITLE
Problem querying tablename containing spaces

### ISSUE THREAD

**Issue by gavinhwatson** [rails-sqlserver/tiny_tds#264]
Hi Guys, Awesome module! :)
Just a quick one... When querying a table name that contains a space Tiny_TDS kicks back an error. I've checked the syntax in a console it the query seems to be fine. Am I missing something obvious? I'm just using the Northwind example database.

`SELECT TOP 10 Quantity FROM Northwind.dbo."Order Details";`

script.rb:150:in `each': Incorrect syntax near 'Order Details'. (TinyTds::Error)
	from datasniffer.rb:150:in `count'
	from datasniffer.rb:150:in `block (3 levels) in <main>'
	from datasniffer.rb:135:in `each'
	from datasniffer.rb:135:in `block (2 levels) in <main>'
	from datasniffer.rb:133:in `each'
	from datasniffer.rb:133:in `block in <main>'
	from datasniffer.rb:131:in `each'
	from datasniffer.rb:131:in `<main>'

Removing the double quotes results in:

datasniffer.rb:148:in `each': Incorrect syntax near the keyword 'Order'. (TinyTds::Error)
	from datasniffer.rb:148:in `count'
	from datasniffer.rb:148:in `block (3 levels) in <main>'
	from datasniffer.rb:135:in `each'
	from datasniffer.rb:135:in `block (2 levels) in <main>'
	from datasniffer.rb:133:in `each'
	from datasniffer.rb:133:in `block in <main>'
	from datasniffer.rb:131:in `each'
	from datasniffer.rb:131:in `<main>'

You can see it's cut the query short before the space in 'Order Details'

Hope you can help, thanks for your time.

**Comment by metaskills** [comment]
This is not a TInyTDS issue, you would get the same error in SMS. You have to quote the SQL properly using SQL Server quoting. For example: `Northwind.dbo.[Order Details]`.
