### ISSUE TITLE
Kerberos support for tiny_tds

### ISSUE THREAD

**Issue by hchiao** [rails-sqlserver/tiny_tds#273]
Hi,

I am currently trying to access SQL Server on a windows box.  I have successfully login and ran commands on the windows box using winrm via the Kerberos protocol.  

I was wondering how can I do the same using Kerberos protocol in tiny_tds?  

When I do `tsql  -C` on the locally compiled binary I see `Kerberos ` is set to `no`.  Is it possible to add `--enable-krb5` to the `ext/tiny_tds/extconf.rb` file?  Would that allow me to use the Kerberos ticket for authentication when connecting to SQL server?

Cheers,
Mike

**Comment by metaskills** [comment]
For starters, this sounds like something someone should compile locally for their own needs. I am also not positive just enabling that config would work. You might need to compile against things on that specific box, conf files, headers, etc. I am not even TinyTDS usage of DBLIB supports Kerberos either. 

If you want to push forward with this, you will need to test this first building your own gem. If all looks good and you think all we need to do is set that config, then make a pull request with that change. That will allow me to watch the Appveyor tests to see if it even still compiles.
