### ISSUE TITLE
Unable to connect: Adaptive Server is unavailable or does not exist (localhost:1433)

### ISSUE THREAD

**Issue by jjturner** [rails-sqlserver/tiny_tds#280]
ruby 2.2.4p230 (2015-12-16 revision 53155) [x64-mingw32]
tiny_tds (1.0.2 x64-mingw32)
Windows 10 connecting to my dev instance of SQL Server 2014:
`client = TinyTds::Client.new username: 'mydomain\myusername', host: 'localhost', database: 'sandbox'`

No issues connecting with the SSMS client nor with sqlcmd.

I have Symantec installed, so I added an exception for 'rb' files - but that didn't help.  Beyond that, I'm at a loss as to what else to diagnose.

As an aside, is there a default setting to connect via one's domain account?

**Comment by aharpervc** [comment]
Probably not but worth checking before anything else:

1. is `localhost` mapped to another ip, like in your hosts file?
1. if you change the host to `127.0.0.1`, it still doesn't work, right?
1. your localhost sql server is configured to work over sockets (tcp/ip)? check this in sql server configuration manager

**Comment by metaskills** [comment]
Also, when debugging, turn off things like firewalls to help you rule them out. Also, please try to use SQL Server authentication. We do not test domain logins.

**Comment by jjturner** [comment]
Appreciate the suggestions - but I was unsuccessful trying all of them:

- disabled Symantec firewall
- changed SQL Server authentication login/pwd in my connection hash
- changed `localhost` to `127.0.0.1` in my connection hash
- verified sql server config has tcp/ip enabled

My hosts-foo needs work, but as I gather, starting from Windows 7 the actual hosts file comments out localhost - but I'd have to believe this is accounted for in tiny_tds:
```
# localhost name resolution is handled within DNS itself.
#       127.0.0.1       localhost
#       ::1             localhost
```
Also, running the gem from Windows would have me believe that I needn't worry about the installation/enabling of dependencies.  Is there a sanity check I ought to run to verify that tiny_tds has all it needs?

FWIW, this is the full output of the return message when attempting to open a connection:
```
C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/tiny_tds-1.0.2-x64-mingw32/lib/tiny_tds/client.rb:43:in `connect': Unable to connect: Adaptive Server is unavailable or does not exist (127.0.0.1:1433) (TinyTds::Error)
        from C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/tiny_tds-1.0.2-x64-mingw32/lib/tiny_tds/client.rb:43:in `initialize'
        from sqlserver_test.rb:3:in `new'
        from sqlserver_test.rb:3:in `<main>'
```

**Comment by metaskills** [comment]
Hmmm... sorry you are having issues. I'm not seeing a solution from this end yet either.

**Comment by jjturner** [comment]
After success connecting to external instances, a quick telnet test connect failure prompted me to revisit SQL Server Config Manager.  TCP was *not* enabled (I had been looking at the wrong node - Native Client instead of Network Configuration - D'oh!!!)  So after enabling it and restarting my local instance, all is well - connection success.

**Comment by metaskills** [comment]
@jjturner Thanks so much for following up with that!
