### ISSUE TITLE
FreeTDS in Docker container

### ISSUE THREAD

**Issue by jgujgu** [rails-sqlserver/tiny_tds#281]
Hello, 

I really appreciate all the work that has gone into making this gem. I've been able to successfully integrate it with my Rails app on OS X (brew installed FreeTDS version `0.95.80`), but have run into problems when Dockerizing it. I was hoping someone could possibly clarify the steps I am doing wrong (or, hopefully, right :D).

My first inclination was to `apt-get` all the necessary packages:
`RUN apt-get install -y unixodbc unixodbc-dev unixodbc-bin freetds-dev freetds-bin tdsodbc`. 
Here I may have installed a package too many, but, as I learned, the `freetds-dev` version on Debian is `0.91-6.1+b2`, which is old and incompatible with the current version of the gem. 

This prompted me to gem install `tiny_tds` with `--disable-system-freetds`, hoping to pull the release candidate 1.0 version, at which point I received the error 
`/usr/local/lib/ruby/2.3.0/net/ftp.rb:243:in 'initialize': Connection timed out - connect(2) for "ftp.freetds.org" port 21 (Errno::ETIMEDOUT)`

or, more fully:

```
Building native extensions with:  '--disable-system-freetds'
This could take a while...
ERROR:  Error installing tinyds:
ERROR: Failed to build gem native extension.
current directory: /usr/local/bundle/gems/tiny_tds-1.0.3/ext/tiny_tds
/usr/local/bin/ruby -r ./siteconf20160517-20-1euzxkn.rb extconf.rb --disable-system-freetds
extconf.rb:14: warning: already initialized constant OpenSSL::SSL::VERIFY_PEER
checking for sybfront.h... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        ((--options excluded for brevity))

/usr/local/lib/ruby/2.3.0/net/ftp.rb:243:in initialize': Connection timed out - connect(2) for "ftp.freetds.org" port 21 (Errno::ETIMEDOUT)
        from /usr/local/lib/ruby/2.3.0/net/ftp.rb:243:in 'open'
```

Am I right to assume that the `--disable-system-freetds` downloads and makes FreeDTS on the system? Moreover, is the `ftp.freetds.org` endpoint being down the cause of my inability to get past this step?

-Jeffrey

**Comment by jgujgu** [comment]
My finding is that my company's firewall blocks FTP requests. Still, are my other assumptions correct?

**Comment by jgujgu** [comment]
I appreciate your time. I will likely just make the original source in the Dockerfile as these other options don't seem especially feasible.

**Comment by metaskills** [comment]
> Still, are my other assumptions correct?

Mostly yes. As a side note, when you install FreeTDS, you don't need UnixODBC as far as we are concerned. We use the DBLIB implementation. Might be needed for your other FreeTDS needs, but TinyTDS only needs base FreeTDS. We do recommend using `--with-tdsver=7.3` config tho if your package manager does not do that already.
