### ISSUE TITLE
 Connect Sql server in Ruby on rails #489 

### ISSUE THREAD

**Issue by luis77** [rails-sqlserver/tiny_tds#288]
I need to connect to a SQL Server database, I installed gem 'tiny_tds' gem 'activerecord-sqlserver-adapter' gem 'deprecated'
my yml file:

default: &default
adapter: sqlserver
host: basddatos.dyndns.org
username: zu
password: pass
pool: 5
timeout: 5000

development:
<<: *default
database: Basdatos_2016

I get this error: TinyTds::Error Server name not found in configuration files WHY? thanks

**Comment by metaskills** [comment]
I see this is moved from https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/issues/489#issuecomment-228059953

Have you configured SQL Server to allow for TCP connections. I suspect his has nothing to do with TinyTDS and you are actually debugging if you can reach your box with DNS or some SQL Server settings.

**Comment by luis77** [comment]
let me check, but Do I need more code than I have?

**Comment by metaskills** [comment]
No, that should work just fine if you can reach the host and have SQL Server set to listen on via TCP on the host/port.

**Comment by luis77** [comment]
Apparently everything is fine. I don't know where the problem is, sql server is set to listen on via TCP but still the same error 
TinyTds::Error
Server name not found in configuration files

**Comment by metaskills** [comment]
Did you try to remove Dydns.org from the equation?

**Comment by Karamorf** [comment]
I think I ran into this same problem, however without the rails part. It seems to not work in tiny_tds versions 0.9.5.rc.3 and 1.0.4 however it did work in 0.7.0. This was the ruby I was running:
ruby -e "require 'sequel'; db = Sequel.connect({host: '10.198.135.174', database: 'database',user: 'user',password: 'PASSWORD',adapter: 'tinytds',port: 1433, azure: true}); puts db[:some view].where(:uid => 'some_username').all"

This is the output I'd get for the error:
/home/user/.gem/ruby/2.3.0/gems/tiny_tds-0.9.5.rc.3/lib/tiny_tds/client.rb:43:in `connect': TinyTds::Error: Login failed for user 'idr_admin@10'. (Sequel::DatabaseConnectionError)

Or with the domain name (when host was set to 'name.domain.com'):
/home/user/repos/acts/.bundle/lib/ruby/2.3.0/gems/tiny_tds-0.9.5.rc.3/lib/tiny_tds/client.rb:43:in `connect': TinyTds::Error: Login failed for user 'idr_admin@name'. (Sequel::DatabaseConnectionError)

Let me know if you'd like a full stack trace.

**Comment by metaskills** [comment]
Can you debug with a simple TinyTds::Client connection first?

**Comment by Karamorf** [comment]
Sure,
With newer versions:
$ gem list | grep tiny_tds
tiny_tds (1.0.4, 0.9.5.rc.3, 0.7.0)
$ irb
irb(main):001:0> require 'tiny_tds';
irb(main):004:0* client = TinyTds::Client.new host: 'name.domain.com', database: 'database',username: 'user',password: 'password', port: 1433, azure: true
TinyTds::Error: Login failed for user 'user@name'.
        from /home/macdc014/.gem/ruby/2.3.0/gems/tiny_tds-1.0.4/lib/tiny_tds/client.rb:43:in `connect'
        from /home/macdc014/.gem/ruby/2.3.0/gems/tiny_tds-1.0.4/lib/tiny_tds/client.rb:43:in `initialize'
        from (irb):4:in `new'
        from (irb):4
        from /usr/bin/irb:11:in `<main>'
irb(main):005:0>



With 0.7.0:
$ bundle exec gem list | grep tiny_tds
tiny_tds (0.7.0)
$ bundle exec irb
irb(main):001:0> require 'tiny_tds'
=> true
irb(main):002:0> client = TinyTds::Client.new host: 'name.domain.com', database: 'database',username: 'user',password: 'password', port: 1433, azure: true
=> #<TinyTds::Client:0x00000001d271b0 @query_options={:as=>:hash, :symbolize_keys=>false, :cache_rows=>true, :timezone=>:local, :empty_sets=>true}>
irb(main):003:0>
