### ISSUE TITLE
tiny_tds insists on building native extensions

### ISSUE THREAD

**Issue by mortee** [rails-sqlserver/tiny_tds#289]
I'm trying to install tiny_tds on a 64-bit system with Win 8.1. Allegedly the gem provides precompiled versions for Windows. However, it tries to build native extensions locally nevertheless, and unfortunately, despite having DevKit and MSYS installed, the build of freetds fails at every attempt. How can I force installing the precompiled version?

```
C:\>gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.2.5
  - RUBY VERSION: 2.1.7 (2015-08-18 patchlevel 400) [x64-mingw32]
...
  - RUBYGEMS PLATFORMS:
    - ruby
    - x64-mingw32

C:\>gem search tiny_tds
*** REMOTE GEMS ***
tiny_tds (1.0.4 ruby x64-mingw32 x86-mingw32)

C:\>gem install tiny_tds --platform=x64-mingw32
Building native extensions.  This could take a while...
```

**Comment by metaskills** [comment]
> However, it tries to build native extensions locally nevertheless

WHOA! That would be a big huge issue. @aharpervc @larskanis any thoughts here?

**Comment by aharpervc** [comment]
Hm, I can't replicate this. I set up ruby 224 x86 on a VM that didn't have ruby. I also installed devkit for it. Then I ran `gem install tiny_tds`:

```
c:\ruby>gem list

*** LOCAL GEMS ***

bigdecimal (1.2.6)
io-console (0.4.3)
json (1.8.1)
minitest (5.4.3)
power_assert (0.2.2)
psych (2.0.8)
rake (10.4.2)
rdoc (4.2.0)
test-unit (3.0.8)

c:\ruby>gem install tiny_tds
Fetching: mini_portile2-2.1.0.gem (100%)
Successfully installed mini_portile2-2.1.0
Fetching: tiny_tds-1.0.4-x86-mingw32.gem (100%)
Successfully installed tiny_tds-1.0.4-x86-mingw32
Parsing documentation for mini_portile2-2.1.0
Installing ri documentation for mini_portile2-2.1.0
Parsing documentation for tiny_tds-1.0.4-x86-mingw32
Installing ri documentation for tiny_tds-1.0.4-x86-mingw32
Done installing documentation for mini_portile2, tiny_tds after 2 seconds
2 gems installed
```

No native compilation, no devkit messages... seems to be working as designed.

However, I note that you're running x64 ruby. Not sure if that would have caused different behavior.

**Comment by mortee** [comment]
OK, then how am I supposed to debug why it chooses to compile?

**Comment by metaskills** [comment]
Well, everything is open when you are debugging this. My guess is that none are related to this project but I'd be happy to help to see where it lands. If I was posed with this problem, I first my try another colleges machine or something. Find out what is different or the same. For example, what is your rubygems version?

**Comment by metaskills** [comment]
NM, just saw this in the initial comment `RUBYGEMS VERSION: 2.2.5`

**Comment by metaskills** [comment]
So maybe first upgrade ruby gems?
