### ISSUE TITLE
Connecting to contained database

### ISSUE THREAD

**Issue by anderscarling** [rails-sqlserver/tiny_tds#291]
I've trouble connecting using [contained users](https://msdn.microsoft.com/en-us/library/ff929188.aspx) using the latest versions of tiny_tds.

Earlier one could work around it using the option `azure: true` - but since #229 changes the user name into domain@sqlserver format when using `azure: true`, that does no longer work.

The line of code that's required for contained users to work is probably [here](https://github.com/rails-sqlserver/tiny_tds/blob/master/ext/tiny_tds/client.c#L331), is there any reason that `DBSETLDBNAME`couldn't always be called?

If always calling it causes issues, maybe we could add an option to indicate that user is contained?

**Comment by metaskills** [comment]
> is there any reason that DBSETLDBNAMEcouldn't always be called

I do not see why not. We can do a PR and/or run the tests to find out. Note to self, I need to get our appveyor tests passing on master again.

**Comment by anderscarling** [comment]
Added pull-req #292

**Comment by metaskills** [comment]
Pull request merged. Closing this issue. Thanks again!
