### ISSUE TITLE
Stored procedure COALESCE differences

### ISSUE THREAD

**Issue by SteveAlexander** [rails-sqlserver/tiny_tds#295]
I'm trying to call a stored procedure that take more than one parameter.

I try to call it like this:

```
client.execute("EXEC procedure_name 'string arg 1', 'string arg2'").do
```

I get the error:

```
script.rb:15:in `do': Incorrect syntax near ','. (TinyTds::Error)
```

If I connect to the same database with tsql, I can successfully do:

```
1> EXEC procedure_name 'string arg 1', 'string arg 2';
2> go
```

tiny_tds 1.0.4
freetds v1.00
TDS version: 7.3
ruby 2.3.1p112

**Comment by SteveAlexander** [comment]
I've been trying to figure this out with the DBA. Looks like there's some subtle bug in how this particular stored procedure works. But it's still very odd that the same query works with tsql but not via tiny_tds.

**Comment by SteveAlexander** [comment]
It looks like COALESCE works differently depending on whether tiny_tds or tsql was the client. Maybe it's the TDS version?

**Comment by camhine** [comment]
I'm experiencing a similar issue to this but it is happening on a trigger rather than a stored procedure.

Running an update command from tsql succeeds. Running the same update command from tiny_tds fails with a syntax error.

This succeeds from tsql:

`UPDATE TOP (1) [TABLE]SET [FIELD] = N'value' WHERE ([ATTRIBUTE] = 1)`

This produces an SQL syntax error from TinyTds:

```
result = client.execute("UPDATE TOP (1) [TABLE]SET [FIELD] = N'value' WHERE ([ATTRIBUTE] = 1)")
result.each(:symbolize_keys => true)
#<TinyTds::Error: Incorrect syntax near the keyword 'and'.>
```

The TinyTds::Error has severity 15, db_error_number 156 and os_error_number 1.

The trigger involved also makes use of `COALESCE`

Versions:

ruby: 2.3.1
tiny_tds: 1.0.5
freetds: dev.1.00.87
Microsoft SQL Server: 2008 R2

I had a look at the Ruby but didn't see anything that might be causing it.

Is there a way to enable some logging for the C binding stuff? It might provide some clues.

**Comment by metaskills** [comment]
Can we come up with a test case that fails? I tried playing with a basic use of `COALESCE` in a simple test case and found it worked just fine. Only issue I saw was the loss of the `dbcolname` in the result fields which I think is just normal. See below.

<details>
<summary>SELECT COALESCE([int], 42) FROM [datatypes]</summary>
```ruby
@client.execute("SELECT COALESCE([int], 42) FROM [datatypes]").each
# ...
{""=>nil},
{""=>nil},
{""=>-2147483647},
{""=>2147483646},
# ...
```
</details>

<details>
<summary>SELECT COALESCE([int], 42) AS [int] FROM [datatypes]</summary>
```ruby
@client.execute("SELECT COALESCE([int], 42) AS [int] FROM [datatypes]").each
# ...
{""=>nil},
{""=>nil},
{""=>-2147483647},
{""=>2147483646},
# ...
```
</details>

**Comment by neil-brett** [comment]
I know this is an old thread, but its still happening. If I run:

client = TinyTds::Client.new(username: USERNAME, password: PASSWORD, dataserver: DATASERVER)

result=client.execute("declare @n varchar; select coalesce(@n + 'and', 'f') as out1")

result.to_a => [{"out1"=>"and"}]

(i.e. coalesce is not treating the null correctly).

However, if I run the same sql in DataGrip or tsql (same credentials, connected to the same dataserver) it returns a value of out1 of 'f' - which is what I expect. 

tinytds 2.1.2
freetds 1.00.82
tds version 7.1
ruby 2.3.1p112

**Comment by aharpervc** [comment]
Check your default connection options in the other tools.... do they enable `CONCAT_NULL_YIELDS_NULL` for you? If you manually turn on that option in your connection, does it work like you want?

**Comment by neil-brett** [comment]
DataGrip does not set that option at all (leaves it at the database default) and its a fresh install of freedts that provides tsql - so again no options other than the database default.

Adding SET CONCAT_NULL_YIELDS_NULL ON ahead of the sql in question makes TinyTds give the correct response. I will use this as a workaround.

**Comment by neil-brett** [comment]
I just noticed https://docs.microsoft.com/en-us/sql/t-sql/statements/set-concat-null-yields-null-transact-sql?view=sql-server-2017 says that using CONCAT_NULL_YIELDS_NULL is deprecated and code that uses it will break in the future.

**Comment by aharpervc** [comment]
Well, what it says is: `CONCAT_NULL_YIELDS_NULL will always be ON and any applications that explicitly set the option to OFF will generate an error`. But that's okay because you want it turned on always.
