### ISSUE TITLE
Unable to connect to SQL Server with SSPI

### ISSUE THREAD

**Issue by msjonker** [rails-sqlserver/tiny_tds#296]
On Windows, when I try to connect to SQL Server using SSPI (not supplying a username or password) I receive "Adaptive Server connection failed." Based on the build script, it seems like SSPI should be enabled (--enable-sspi) on the supplied version of FreeTDS. I am unable to check this, because executing ```tsql -C``` errors due to DLLs missing that tsql.exe depends on.

I did download the compiled version of FreeTDS 1.00 from https://sourceforge.net/projects/freetdswindows/ and had no problems connecting when supplying only a host and port. It has SSPI enabled.

This is happening with version 1.04 of the gem, but I have tested the other 1.x versions and received the same results.

**Comment by metaskills** [comment]
> Based on the build script, it seems like SSPI should be enabled (--enable-sspi)

True, but I am not sure just setting that flag is all that is needed http://www.freetds.org/userguide/domains.htm. Technically I have never found the time to support that in the precompiled Windows binaries. For now, if you need that feature, you will have to install FreeTDS locally and make sure the gem install links to it. Hope that helps. Do let me know if there is something you think I can do.

**Comment by msjonker** [comment]
After comparing the TDS dump log files from a successful SSPI connection from tsql and a failed connection using the same parameters with TinyTds::Client.new, it seems that the issue was using "localhost" as the dataserver parameter with TinyTds::Client.new. In looking through the sspi.c code in FreeTDS (https://github.com/FreeTDS/freetds/blob/ae1a0f1175c2ad9b22c49b4b611d5c56883d74c5/src/tds/sspi.c#L271), it seems that there is logic that looks for a "." in the server name. Changing the dataserver parameter to "127.0.0.1" fixed the problem for me.

**Comment by metaskills** [comment]
AWESOME! Thanks so much for following up with that info.
