### ISSUE TITLE
Install fails on OS X 10.11.6

### ISSUE THREAD

**Issue by ChrisMiami** [rails-sqlserver/tiny_tds#298]
sudo gem install tiny_tds fails.

At first I thought it was due to OpenSSL missing, so I got it and did a make install but now Tiny_TDS is failing on a **typedef struct bio_st BIO**; when trying to compile freetds.

Here are my logs. Not sure what the solution is - shouldn't it 'just work'? ;-)
Chris

[tiny_tds_failure.txt](https://github.com/rails-sqlserver/tiny_tds/files/423518/tiny_tds_failure.txt)

**Comment by metaskills** [comment]
Please install FreeTDS on your system before installing TinyTDS so it has something to link to.

**Comment by metaskills** [comment]
Hope that was the fix. Closing this issue but feel free to reply and open up if needed.
