### ISSUE TITLE
Save binary column into pdf file

### ISSUE THREAD

**Issue by rjurado01** [rails-sqlserver/tiny_tds#300]
I'm using TinyTDS gem to connect to ms sql server database.

When I request table rows, one of the colum returns this info:

     "PDF_FILE"=>"~BLOBD\u0000pdf\u0000%PDF-1.3\r\n\r\n%-------------------->Init block\r\n\r\n%-------------------->Font block\r\n\r\nn3 0 obj\r\n<<\r\n/Type / Font...\x80\n\x00(\x00\xA0\x02\x80\n\x00(\x00\xA0\x02\x80<\xAB"

How can I save this into pdf file? Thanks.

**Comment by metaskills** [comment]
Thanks for using this gem. However, your question is not related to TinyTDS but just general Ruby. Please start here instead. http://stackoverflow.com/questions/941856/write-binary-file-in-ruby

**Comment by rjurado01** [comment]
@metaskills Whitch code format use TinyTDS to convert binary sql files to string for hash response?

**Comment by metaskills** [comment]
It is defined by the column. If your column is a binary column, then the string is a binary encoding. If it is a char-based column, then you you have to tell Ruby to force or transcode it.
