### ISSUE TITLE
Unexpected EOF from the server

### ISSUE THREAD

**Issue by fkoessler** [rails-sqlserver/tiny_tds#302]
I am on a Ubuntu 14.04 server with FreeTDS v1.00.15 installed:

> tsql -C
> Compile-time settings (established with the "configure" script)
>                             Version: freetds v1.00.15
>              freetds.conf directory: /usr/local/etc
>      MS db-lib source compatibility: no
>         Sybase binary compatibility: no
>                       Thread safety: yes
>                       iconv library: yes
>                         TDS version: auto
>                               iODBC: no
>                            unixodbc: no
>               SSPI "trusted" logins: no
>                            Kerberos: no
>                             OpenSSL: yes
>                              GnuTLS: no
>                                MARS: no

I am using tiny_tds gem version 1.0.4 from a Rails 4.2.1 application.
I am connecting to a Windows SQL Server 2008 R2 database.

Here is the code I use to get the client : 
`client = TinyTds::Client.new(username: db_conf['username'], password: db_conf['password'], host: db_conf['host'], port: db_conf['port'], database: db_conf['database'], tds_version: '7.3', timeout: 15000, appname: 'ERP')
`

Here is an example on how I run queries with tiny_tds:

```
query = "SELECT ARTICLE.ARKTSOC, ARTICLE.ARKTCODART, ARTICLE.ARKTCOMART,
        CASE
          WHEN NOMENC.NOCTREPFAB = 'STF' THEN '219998'
          ELSE NOMENC.NOCTCODECP END
        AS NOCTCODECP,
        NOMENC.NOCNMISENR, NOMENC.NOCTUNITE, NOMENC.NOCNQTECOM
        FROM ARTICLE
        LEFT JOIN NOMENC ON ARTICLE.ARKTSOC = NOMENC.NOKTSOC AND ARTICLE.ARKTCODART = NOMENC.NOKTCODPF AND ARTICLE.ARKTCOMART = NOMENC.NOKTCOMPF
        WHERE (NOMENC.NOCTLIBCOM LIKE 'Prioritaire%' OR NOMENC.NOCTREPFAB = 'STF') AND ARTICLE.ARKTSOC = '#{order.lcomcli_lcktsoc}' AND ARTICLE.ARKTCODART = '#{order.lcomcli_lcctcodart}' AND ARTICLE.ARKTCOMART like '%'
        ORDER BY NOMENC.NOKNLIGNOM ASC"

      priority_operations_result = self.get_pmi_client.execute(query)

      priority_operations = []
      priority_operations_result.each(first: true) do |priority_operation_result|
        priority_operation = self.new
        priority_operation.article_arktsoc = priority_operation_result['ARKTSOC'].try(:strip)
        priority_operation.article_arktcodart = priority_operation_result['ARKTCODART'].try(:strip)
        priority_operation.article_arktcomart = priority_operation_result['ARKTCOMART'].try(:strip)
        priority_operation.nomenc_noctcodecp = priority_operation_result['NOCTCODECP'].try(:strip)
        priority_operation.nomenc_nocnmisenr = priority_operation_result['NOCNMISENR']
        priority_operation.nomenc_noctunite = priority_operation_result['NOCTUNITE'].try(:strip)
        priority_operation.nomenc_nocnqtecom = priority_operation_result['NOCNQTECOM']
        priority_operations << priority_operation
      end
      priority_operations_result.cancel
```

Those queries are run from a rake task. The task always fails with the error:

> rake aborted!
> TinyTds::Error: Adaptive Server connection failed

When I look in FreeTDS log for more information, I find:

> 00a0 26 79 b4 34 75 ef aa 7e-ea a5 99 0e 47 41 6a 27 |&y.4u..~ ....GAj'|
> 00b0 f4 69 ec 80 e8 9f c4 0d-7b bc 1f 70 59 14 07 39 |.i...... {..pY..9|
> 00c0 be cd 53 e3 13 80 2a 01-15 82 f4 b3 48          |..S...*. ....H|
> 
> tls.c:105:in tds_pull_func_login
> query.c:3796:tds_disconnect()
> util.c:165:Changed query state from IDLE to DEAD
> util.c:322:tdserror(0x7238ea0, 0x7b9d8b0, 20017, 0)
> dblib.c:7947:dbperror(0x95716f0, 20017, 0)
> dblib.c:8015:dbperror: Calling dblib_err_handler with msgno = 20017; msg->msgtext = "Unexpected EOF from the server (192.168.32.105:1433)"
> dblib.c:5777:dbgetuserdata(0x95716f0)
> dblib.c:8037:dbperror: dblib_err_handler for msgno = 20017; msg->msgtext = "Unexpected EOF from the server (192.168.32.105:1433)" -- returns 2 (INT_CANCEL)
> util.c:352:tdserror: client library returned TDS_INT_CANCEL(2)
> util.c:375:tdserror: returning TDS_INT_CANCEL(2)
> tls.c:942:handshake failed
> login.c:530:login packet rejected
> util.c:322:tdserror(0x7238ea0, 0x7b9d8b0, 20002, 0)
> dblib.c:7947:dbperror(0x95716f0, 20002, 0)
> dblib.c:8015:dbperror: Calling dblib_err_handler with msgno = 20002; msg->msgtext = "Adaptive Server connection failed (192.168.32.105:1433)"

Is this a bug or am I doing things wrong?
Let me know if you need any more information.

**Comment by metaskills** [comment]
Please read over this some: https://github.com/rails-sqlserver/tiny_tds#tinytdsresult-usage. Things I see in your code are:

* Try not using the `first:true` query option.
* No need to cancel if you just iterate over each row in the results.
* Not a lot of error handling here.

If you are using Rails, may I suggest that you leverage the adapters' implementation of the TinyTDS connection. You would get everything above for free. For example, you can use ActiveRecord `find_by_sql` to return model objects and just let the adapter worry about the TinyTDS details you are trying to re-write here.

**Comment by fkoessler** [comment]
Thank you for your answer.

I followed your recommandations and removed 'first:true' and calls to 'cancel'. However I am still having the same issue.

I do error handling with exceptions.
For example in the `get_pmi_client` method:

```
def self.get_pmi_client
  db_conf = Rails.configuration.database_configuration["pmi_#{Rails.env}"]
  # Play with tiny_tds options until it works...
  client = TinyTds::Client.new(username: db_conf['username'], password: db_conf['password'], host: db_conf['host'], port: db_conf['port'], database: db_conf['database'], tds_version: '7.3', timeout: 15000, appname: 'FahrnerERP')
  raise MSSQLConnectionError, t('fahrner_erp.errors.pmi_connection_error') unless client.active?
  return client
end
```

I also rescue from `TinyTds::Error`:

```
rescue_from TinyTds::Error do |exception|
  if request.format == :json
    respond_to do |format|
      format.json { render json: {errors: t('fahrner_erp.errors.tiny_tds', error_message: exception.message)}, status: 503 }
    end
  else
    redirect_to root_path, { alert: t('fahrner_erp.errors.tiny_tds', error_message: exception.message, status: 503) }
  end
end
```

I am considering using the `activerecord-sqlserver-adapter` gem.
I only query to the MSSQL database from a rake task in order to synchronize data to a local postgresql database. Then in my application I use classic Rails ActiveRecord models linked to the postgresql database tables. Would you still recommend using `activerecord-sqlserver-adapter` for this usecase?

Last remarks: it feels like the `Unexpected EOF from the server` error happens when lots of queries are sent too fast to the MSSQL server (the ruby code sample I provided in my first post is within an each loop). The error does't happen when running single isolated queries. Does this make sense to you? Should I be careful to not send too many queries to the MSSQL server?

**Comment by fkoessler** [comment]
Update about this issue.

I've been playing with the SQL Server Profiler and looking at the trace, it looks like my rake task is opening too many connections to the MSSQL server. At some point, the max opened connection is reached and the SQL server refuses to open any new connection, resulting in the `TinyTds::Error: Adaptive Server connection failed` error. I attach an export of the trace to this comment.

For each query sent with tiny_tds, I find the following lined in the profiler trace:
1. Audit login (sets some values)
2. SQL:BatchStarting (sets textsize)
3. SQL:BatchCompleted (sets textsize)
4. SQL:BatchStarting (use PMITEST database)
5. SQL:BatchCompleted (use PMITEST database)
6. SQL:BatchStarting (executes actual SQL query)
7. SQL:BatchCompleted (executes actual SQL query)

The Audit logout line, which seems to correspond to a connection close, is missing.
After the rake task crashes and stops sending queries to the SQL server, the Audit logout line corresponding to previous connections start to appear in the trace. I interpret it as the MSSQL server closing dangling connections.

Besides when I monitor the number of active connections to the SQL server during the execution of the rake task, I see the number of open connections grows rapidly until it reaches its limit and the rake task crashes.

That is why I tried the `tiny_tds` `cancel` method, hoping it would close the open connection.

Is there any such method to force close a connection to the MSSQL server before sending a new query?

[trace_export.xlsx](https://github.com/rails-sqlserver/tiny_tds/files/498583/trace_export.xlsx)

**Comment by fkoessler** [comment]
I finally figured out that I should reuse my open connection instead of opening a new one for each query..

Translated to code:

```
def self.get_pmi_client
      if @@pmi_client.nil? or !@@pmi_client.active?
        db_conf = Rails.configuration.database_configuration["pmi_#{Rails.env}"]
        @@pmi_client = TinyTds::Client.new(username: db_conf['username'], password: db_conf['password'], host: db_conf['host'], port: db_conf['port'], database: db_conf['database'])
        raise MSSQLConnectionError, t('erp.errors.pmi_connection_error') unless @@pmi_client.active?
      end
      return @@pmi_client
    end
```

Since this change, the `TinyTds::Error: Adaptive Server connection failed` doesn't happen anymore.

The problem was due to a bad use of the gem, I apologize for creating an issue here. Hopefully it can help somebody struggling with the same problem.

Thanks a lot for your help and for your work on this open source gem. Respect :+1:

**Comment by metaskills** [comment]
Cool. This is one reason I suggested allow the Rails adapter to do this work and using the low level ActiveRecord interfaces. Could have saved you lots of time. Really appreciate the followup post on fixing your issue too!

**Comment by kevincolyar** [comment]
I'm having this exact same issue (a lot of queries and connections persisting, running out of connections, etc).  I am using the rails sql server adapter in my case.  However the code that uses the SQL Server is in a gem and the Rails site uses that gem.  They are in a gem because they are shared between projects (Rails, services, etc).

I'm using an `establish_connection` call when each model in the gem is evaluated.  Is there something I need to do on Rails end to fix these connection management issues?

**Comment by metaskills** [comment]
@kevincolyar I suggest you not call establish connection on each model. Doing so will give each class their own connection pool and things will not work like you were running a set of models on one application. Further reading:

https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/issues/173#issuecomment-4427121
https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/issues/402#issuecomment-107074580
http://technology.customink.com/blog/2015/06/22/rails-multi-database-best-practices-roundup/
