### ISSUE TITLE
tsql command isn't actually quiet

### ISSUE THREAD

**Issue by jbwl** [rails-sqlserver/tiny_tds#318]
Usage of the included tsql command produces unwanted output like shown below, even if the 'quiet' option enabled:

`$ tsql -o qfh`

`[TinyTds][v1.0.5][tsql]: /Users/dev/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/tiny_tds-1.0.5/exe/tsql`

I would like the command to be actually quiet when called for, i.e. only the query result being shown.
Supressing headers and footers with -o fh works fine.

**Comment by jbwl** [comment]
This is unrelated to the tsql binary. I just found out that the output described above is a feature of rbenv, which creates a shim for the tsql executable, which when used produces the output.

**Comment by metaskills** [comment]
Our `tsql` binstub here (https://github.com/rails-sqlserver/tiny_tds/blob/master/bin/tsql) uses our bin wrapper code here (https://github.com/rails-sqlserver/tiny_tds/blob/master/lib/tiny_tds/bin.rb). That does have a `puts info` command. I'll change that line to the following:

```ruby
puts bin.info unless args.any? { |x| x == '-q' }
```

And this will be in master for the upcoming v1.0.6 release.
