### ISSUE TITLE
Adaptive Server connection failed

### ISSUE THREAD

**Issue by sandeep100** [rails-sqlserver/tiny_tds#327]
OS :  Ubuntu 12.04 
*version of TDS : 7.3
Some times I get this error Adaptive Server connection failed. but not every time.

**Comment by sandeep100** [comment]
Got this error again
Below is the error log
OAuthClient | doRequest:success:failure:fromCacheIfAvailable: @ 1699 | REQUEST:<NSMutableURLRequest: 0x7c0e6e50> { URL: ​https://173.251.31.210:63775/api/v1/patients/53.json?clientkey=1&with_photo=true }
2016-12-16 20:01:37.146 MDofficeMobile[11853:159348] Error: Error Domain=AFNetworkingErrorDomain Code=-1011 "Expected status code in (200-299), got 500" UserInfo?={NSLocalizedRecoverySuggestion=<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>Action Controller: Exception caught</title>
<style>
body { background-color: #fff; color: #333; }
body, p, ol, ul, td {
font-family: helvetica, verdana, arial, sans-serif;
font-size: 13px;
line-height: 18px;
}
pre {
background-color: #eee;
padding: 10px;
font-size: 11px;
white-space: pre-wrap;
}
a { color: #000; }
a:visited { color: #666; }
a:hover { color: #fff; background-color:#000; }
</style>
</head>
<body>
<h1>
TinyTds::Error
in Api::V1::PatientsController#show?
</h1>
<pre>Adaptive Server connection failed</pre>
<p><code>Rails.root: /home/mdoadmin/mdsummary/releases/20161216121602</code></p>
<div id="traces">
<a href="#" onclick="document.getElementById(&#x27;Framework-Trace&#x27;).style.display=&#x27;none&#x27;;document.getElementById(&#x27;Full-Trace&#x27;).style.display=&#x27;none&#x27;;document.getElementById(&#x27;Application-Trace&#x27;).style.display=&#x27;block&#x27;;; return false;">Application Trace</a> |
<a href="#" onclick="document.getElementById(&#x27;Application-Trace&#x27;).style.display=&#x27;none&#x27;;document.getElementById(&#x27;Full-Trace&#x27;).style.display=&#x27;none&#x27;;document.getElementById(&#x27;Framework-Trace&#x27;).style.display=&#x27;block&#x27;;; return false;">Framework Trace</a> |
<a href="#" onclick="document.getElementById(&#x27;Application-Trace&#x27;).style.display=&#x27;none&#x27;;document.getElementById(&#x27;Framework-Trace&#x27;).style.display=&#x27;none&#x27;;document.getElementById(&#x27;Full-Trace&#x27;).style.display=&#x27;block&#x27;;; return false;">Full Trace</a> 
<div id="Application-Trace" style="display: block;">
<pre><code>app/controllers/api/v1/patients_controller.rb:85:in `show&#x27;</code></pre>
</div>
<div id="Framework-Trace" style="display: none;">
<pre><code>tiny_tds (0.6.1) lib/tiny_tds/client.rb:77:in `connect&#x27;
tiny_tds (0.6.1) lib/tiny_tds/client.rb:77:in `initialize&#x27;
activerecord-sqlserver-adapter (3.2.13) lib/active_record/connection_adapters/sqlserver_adapter.rb:417:in `new&#x27;
activerecord-sqlserver-adapter (3.2.13) lib/active_record/connection_adapters/sqlserver_adapter.rb:417:in `connect&#x27;
activerecord-sqlserver-adapter (3.2.13) lib/active_record/connection_adapters/sqlserver_adapter.rb:204:in `initialize&#x27;
activerecord-sqlserver-adapter (3.2.13) lib/active_record/connection_adapters/sqlserver_adapter.rb:40:in `new&#x27;
activerecord-sqlserver-adapter (3.2.13) lib/active_record/connection_adapters/sqlserver_adapter.rb:40:in `sqlserver_connection&#x27;
activerecord (3.2.13) lib/active_record/connection_adapters/abstract/connection_pool.rb:315:in `new_connection&#x27;
activerecord (3.2.13) lib/active_record/connection_adapters/abstract/connection_pool.rb:325:in `checkout_new_connection&#x27;
activerecord (3.2.13) lib/active_record/connection_adapters/abstract/connection_pool.rb:247:in `block (2 levels) in checkout&#x27;
activerecord (3.2.13) lib/active_record/connection_adapters/abstract/connection_pool.rb:242:in `loop&#x27;
activerecord (3.2.13) lib/active_record/connection_adapters/abstract/connection_pool.rb:242:in `block in checkout&#x27;
/home/mdoadmin/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize&#x27;
activerecord (3.2.13) lib/active_record/conn

**Comment by metaskills** [comment]
Seems your TinyTDS is old. I recommend upgrading both FreeTDS and re-installing the latest TinyTDS to use it.

**Comment by sandeep100** [comment]
gem 'tiny_tds', '~> 1.1'  this showing the latest , so should I wite this in gem file and run bundle install?

**Comment by metaskills** [comment]
Yes... but do not forget using the latest FreeTDS and remember, Ubuntu's version is way way out of date.

**Comment by metaskills** [comment]
But it is easy to install manually using FreeTDS's directions. We have some test scripts in the repo where we do the same on Travis/Circe too

**Comment by sandeep100** [comment]
I think I am already using latest version of tds as I ran this command ....


sandeep@sandeep-Lenovo-E40-80:~/Desktop/mdsummary_api$ tsql -C
[TinyTds][v1.0.4][tsql]: /home/sandeep/.rvm/gems/ruby-2.0.0-p648/gems/tiny_tds-1.0.4/exe/tsql
Compile-time settings (established with the "configure" script)
                            Version: freetds v1.00
             freetds.conf directory: /home/sandeep/.rvm/gems/ruby-2.0.0-p648/gems/tiny_tds-1.0.4/ports/x86_64-unknown-linux-gnu/etc
     MS db-lib source compatibility: no
        Sybase binary compatibility: no
                      Thread safety: yes
                      iconv library: yes
                        TDS version: 7.3
                              iODBC: no
                           unixodbc: no
              SSPI "trusted" logins: no
                           Kerberos: no
                            OpenSSL: yes
                             GnuTLS: no
                               MARS: no
