### ISSUE TITLE
Adaptive Server connection timed out: EXEC 

### ISSUE THREAD

**Issue by luis77** [rails-sqlserver/tiny_tds#329]
Many times I have tried to perform a search where many data is extracted, I get this error in any module:  "Adaptive Server connection timed out: EXEC ":
Completed 500 Internal Server Error in 11923ms (ActiveRecord: 11885.6ms)

ActiveRecord::StatementInvalid (TinyTds::Error: Adaptive Server connection timed out: EXEC sp_executesql N'SELECT DISTINCT SUM(Importe+detallevet.IVA) FROM [detallevet] left outer join venta ON venta.Documento=detallevet.Docto and venta.RutaId=detallevet.RutaId WHERE ((venta.RutaId = N'''' or N'''' = '''') AND (venta.TipoVta = ''Contado'') AND (venta.IdEmpresa = N''208''))'):
  app/controllers/ventas_controller.rb:37:in `busqueda_general_graficos'

how can I fixed? thanks

**Comment by metaskills** [comment]
What do you have the timeout set to and have you tried increasing it?

**Comment by luis77** [comment]
I've increased it to timeout: 60000 and it keeps happening to me, usually when the table has many records and I'm doing searches with a query

**Comment by luis77** [comment]
mmm I see, you are right. I will have to investigate how to improve the search. Thank you
