### ISSUE TITLE
Ruby2.3.0: util.c:70: tds_set_state: Assertion `tds->state < (sizeof(state_names)/sizeof(state_names[0]))' failed

### ISSUE THREAD

**Issue by vinaymehta** [rails-sqlserver/tiny_tds#335]
I am trying to run sidekiq on my server 'ubuntu' version - 14.04. But When I do so, I am receiving this error 'tds_set_state: Assertion `tds->state < (sizeof(state_names)/sizeof(state_names[0]))' failed'. 

It was working fine few days ago. But from past few days, M receiving such error.

Here is the result of tsql -c on server
`[TinyTds][v1.0.4][tsql]: /home/shared/bundle/ruby/2.3.0/gems/tiny_tds-1.0.4/exe/tsql
Compile-time settings (established with the "configure" script)
                            Version: freetds v1.00
             freetds.conf directory: /home/shared/bundle/ruby/2.3.0/gems/tiny_tds-1.0.4/ports/x86_64-pc-linux-gnu/etc
     MS db-lib source compatibility: no
        Sybase binary compatibility: no
                      Thread safety: yes
                      iconv library: yes
                        TDS version: 7.3
                              iODBC: no
                           unixodbc: no
              SSPI "trusted" logins: no
                           Kerberos: no
                            OpenSSL: yes
                             GnuTLS: no
                               MARS: no`

Please help me to resolve this issue.
Thanks in advance

**Comment by metaskills** [comment]
Could you read this first (https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/issues/402#issuecomment-107074580) and then get back to us with a few question. For example, are you using Rails/ActiveRecord and is your primary connection SQL Server with TinyTDS?

**Comment by metaskills** [comment]
Did you install FreeTDS on your Ubuntu system or did TinyTDS install it for you?

**Comment by metaskills** [comment]
Please reply back to keep this going. Closing in the meantime.
