### ISSUE TITLE
Do Not Install FreeTDS on Gem Installs

### ISSUE THREAD

**Issue by metaskills** [rails-sqlserver/tiny_tds#342]
Using MiniPortile to configure & install Iconv, OpenSSL, and FreeTDS crosses the line into package manager territory. This system is setup for us to build static gems for Windows platforms only and is being accidentally relied on by some platforms and/or happenstantial users that do not have these shared libraries installed. 

Dependencies like FreeTDS should be installed by users via their package manager of choice. As needed, it is the user's responsibility to make sure TinyTDS knows how to find and link to these shared libraries. By avoiding getting caught up in a package manager's game, we can avoid:

* Playing host(s) for package mirrors.
* Accidentally installing and using an unknown version of FreeTDS.

### Related Issues:

* https://github.com/rails-sqlserver/tiny_tds/pull/341
* https://github.com/rails-sqlserver/tiny_tds/issues/333
* https://github.com/rails-sqlserver/tiny_tds/pull/341
https://github.com/rails-sqlserver/tiny_tds/issues/330

**Comment by coderjoe** [comment]
I think this is a fantastic idea. I've been toying with a similar idea off on a feature branch in my fork while debugging the various windows "cannot load tiny_tds" errors in the issue list. The resulting tiny_tds build process became much much simpler once 3rd party dependencies and MiniPortile were removed from the extension build's responsibilities.

**Comment by coderjoe** [comment]
Do you think this might warrant a major version number change? While the intent of the issue does indeed match the the documentation it will very likely break builds which rely on automatic downloading of 3rd party dependencies.

I ran into exactly this problem while experimenting with removing MiniPortile from the extension build at https://github.com/coderjoe/tiny_tds/tree/extension.build.experiment

As an aside, if all goes well I might have something resembling a PR for this issue soon. :)

**Comment by metaskills** [comment]
> Do you think this might warrant a major version number change?

Yes, I set the label to 1.2.

>  if all goes well I might have something resembling a PR for this issue soon. :)

Sweet! I am working on building new Docker images for TinyTDS/Adapter baed on the new CTP1.3

**Comment by coderjoe** [comment]
I meant along the lines of 2.0.0. ;)

**Comment by metaskills** [comment]
Yea... I thought so :) for some reason I was kind of hoping to keep 1.x for the sake of FreeTDS version matching... but I guess that does not really matter. You are right, to avoid the semver 👮 we should go to 2.0.

**Comment by aristotelesbr2014** [comment]
Ubuntu 16.04 gem install tiny_tds no work ;(

**Comment by metaskills** [comment]
We now have v2.1.0pre1 and v2.1.0.pre2 which both solve this issue. Soon there will be a full v2.1.0 release.
