### ISSUE TITLE
Undefined method connect for TinyTds::Client In Windows

### ISSUE THREAD

**Issue by sithara** [rails-sqlserver/tiny_tds#349]
I 'm trying to install tiny_tds in my windows machine.

This is the result I get when I `tsql -C `
```
[TinyTds][v1.1.0][tsql]: C:/Ruby22/lib/ruby/gems/2.2.0/gems/tiny_tds-1.1.0-x86-
ingw32/exe/tsql.EXE
```

This is the error message I get when I try executing  
`TinyTds::Client.new(username: "xx", password: "xxx", host: "xxxx", database: "xxxxxx")
`

 ```

NoMethodError: undefined method `connect' for #<TinyTds::Client:0x2eda828>
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/tiny_tds-1.1.0-x86-mingw32/lib/t
iny_tds/client.rb:53:in `initialize'
        from (irb):12:in `new'
        from (irb):12
        from C:/Ruby22/bin/irb:11:in `<main>'

```

**Comment by metaskills** [comment]
Hmm... I have not seen that one before. I hints at no compiled binary. Could you please install the latest 1.2.0 prerelease. You can do that by bundling to `1.2.0.beta1` in your Gemfile or by doing `gem install tiny_tds --pre`. Which ever works for you. Interested in hearing if that helps.

**Comment by metaskills** [comment]
Pull Request #347 pulled in OpenSSL v1.1.0 and we got new versions of TinyTDS at v1.2.0 which should solve this issue. Please reply back and let us know.

**Comment by sithara** [comment]
NoMethodError: undefined method `connect' for #<TinyTds::Client:0x2b77ba0>
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/tiny_tds-1.2.0.beta1-x86-mingw32
/lib/tiny_tds/client.rb:53:in `initialize'
        from (irb):7:in `new'
        from (irb):7

Same error :(

**Comment by metaskills** [comment]
Ouch! Would you mind trying the official release of v1.2.0? I doubt it would be different but worth a shot. What platform are you on? Can you do a gem fetch and unpack (google it) to see if the lib/tiny_tds/tiny_tds is present? Maybe try a `require 'tiny_tds/tiny_tds'` in IRB before hand?

**Comment by sithara** [comment]
@metaskills Yes the require does not work . It throws an error. But it says my gem has installed successfully. I'm on windows 7 !

**Comment by metaskills** [comment]
@sithara Sorry to hear about the problems. Could you try to find a version that works for you? Using this list (https://rubygems.org/gems/tiny_tds/versions) jumping to each last minor release. Ex:

```shell
$ gem install -v 0.9.5.rc.3
$ irb
> gem 'tiny_tds, '0.9.5.rc.3'
> require 'tiny_tds'
> # test connection 
```

And then like below to the next. And so on.

```shell
$ gem install -v 0.7.0
$ irb
> gem 'tiny_tds, '0.7.0'
> require 'tiny_tds'
> # test connection 
```

I'd be interested in if an older version worked for you on Windows 7.

**Comment by orgads** [comment]
libsybdb-5.dll depends on libgcc_s_sjlj-1.dll which is not installed by default.

Maybe we should use `-static-libgcc` for freetds?

**Comment by coderjoe** [comment]
That might work around it for the 1.2 branch. Another work around is to ensure devkit is loaded in your path before loading the project. Devkit comes with the appropriate libgcc_s_sjlj-1.dll for its build environment.

**Comment by orgads** [comment]
Right, but most users don't have devkit...

**Comment by coderjoe** [comment]
True but until the real issue is fixed it's very simple to install devkit and rails installer seems to come with it pre-installed correct?

**Comment by orgads** [comment]
For some reason, I can't build freetds locally (with 32-bit). Is there a way to grab the artifacts from AppVeyor?

**Comment by coderjoe** [comment]
I don't think the appveyor build builds binary artifacts. That has to be done locally via the rake-compiler-dock via the gem:windows rake task I believe. Thank you for the PR btw. :)

**Comment by sithara** [comment]
@metaskills  I was able to `require 'tiny_tds'` without any error using using version 0.9.5.rc.3

But now I get 
```
TinyTds::Error: Adaptive Server connection failed (xxx:1433)
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/tiny_tds-0.9.5.rc.3-x86-mingw32/
lib/tiny_tds/client.rb:43:in `connect'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/tiny_tds-0.9.5.rc.3-x86-mingw32/
lib/tiny_tds/client.rb:43:in `initialize'
        from (irb):6:in `new'
        from (irb):6
        from C:/Ruby22/bin/irb:11:in `<main>'

```

**Comment by metaskills** [comment]
Could you please try v1.3.0 that was released today?

**Comment by zbychfish** [comment]
"When I try running this .exe I get missing a libeay32-1.0.2f-x86-64-w64-mingw32.dll file error"
Fresh installation of Tiny_TDS does not change windows path variable. Please add to path the directory where static libraries are located and tsql will work.
