### ISSUE TITLE
No precompiled 1.3.0  x86-mingw32 gem

### ISSUE THREAD

**Issue by taliesins** [rails-sqlserver/tiny_tds#354]
I was expecting x86 precompiled gem at https://rubygems.org/gems/tiny_tds/versions

My poor Windows box is trying to build native extensions (and is freezing/failing) when attempting to install.

**Comment by taliesins** [comment]
Turns out I can't use 1.2.0 as I am running into #330

**Comment by taliesins** [comment]
To make it work from Chef:

```
chef_gem 'tiny_tds' do
    action :install
    version '1.2.0'
    options '--no-user-install'
end
```

**Comment by metaskills** [comment]
What about v1.3.0?

**Comment by mblundin** [comment]
tiny_tds-1.3.0-x86-mingw32 is not available on rubygems.  x86 and ruby are.
See https://rubygems.org/gems/tiny_tds

**Comment by metaskills** [comment]
OH! That would be my fault. Building that again now and posting...

**Comment by metaskills** [comment]
Just pushed `tiny_tds-1.3.0-x86-mingw32.gem` to rubygems. Sorry about that.

**Comment by metaskills** [comment]
Closed the issue, please let me know if you have any issues with it.

**Comment by taliesins** [comment]
Thanks :-) now us ChefDk users should be able to use this gem again.
