### ISSUE TITLE
Error trying to execute an update SQL statement while iterating a result set

### ISSUE THREAD

**Issue by drobertr** [rails-sqlserver/tiny_tds#358]
Hi,

Using TinyTds v1.3.0 with Ruby 2.3.1 on Windows 10, connecting to SQL Server 2014. I'm trying to iterate over a recordset and run an update during iteration. The error I get is:

Attempt to initiate a new Adaptive Server operation with results pending

My code is something like:

client = TinyTds::Client.new ...
results = client.execute("SQL STATEMENT...")
results.each do |result|
  ...
  client.execute("ANOTHER SQL STATEMENT...")
end
client.close

It seems 'client' is tied up fetching rows into 'results' during iteration. What I'm trying to accomplish is a common pattern, I'm just not sure the right way...a second client? Eager load the results and release the client? I've read the docs and searched Google, sorry if the solution went over my head! Any advice would be appreciated. Thanks much

**Comment by metaskills** [comment]
Yea... you can't do that. Since an each is pulling data across the wire, you have to finish that batch first. Use multiple connections if you need to or record work you need to do in the loop and then execute that work post the each loop. HTH.

**Comment by drobertr** [comment]
Thanks for the reply. I ended up creating a read and a write client. Seems to be working well that way.

**Comment by metaskills** [comment]
Nice idea. That's certainly a good way to do it. Thanks for sharing.
