### ISSUE TITLE
Adaptive Server connection timed out during each loop

### ISSUE THREAD

**Issue by aaldrich** [rails-sqlserver/tiny_tds#363]
I'm having a weird issue. I'm able to query the SQL database correctly and get back records, however for some reason when it gets to the last 8 rows, it times out during the each loop. It only happens during a specific instance on row 46359. I really don't know what is going on. The same exact code works fine for another query that pulls 1.9 Million Rows and runs fine so it doesn't seem to be a volume issue.

* What platform you are on. Windows, Mac, Ubuntu, etc.
Ubuntu

* What version of FreeTDS you are using.
Rails with Tiny TDS 2.4.8

**Comment by metaskills** [comment]
Odd! A few questions.

* What gem version of TinyTDS?
* What version of FreeTDS is installed on your system?
* Can you isolate a bit more why this might be happening? Ex: does row 46359 have something in it that causes this?

**Comment by aaldrich** [comment]
@metaskills 

- What gem version of TinyTDS?
2.4.8

- What version of FreeTDS is installed on your system?
Not sure how to find this, I'm using rails and installed via Gemfile. Can you provide an example of how to do this? 

- Can you isolate a bit more why this might be happening? Ex: does row 46359 have something in it that causes this?
I thought the same thing and none of the data in that row is an issue. I changed the SQL to specifically skip that record and it still happens. It is something to do with that row number, not the values in that row.

**Comment by metaskills** [comment]
There is no `2.4.8` for TinyTDS. That sounds like a Ruby version? What version of TinyTDS is your app/bundled locked to? Most people can find this in Gemfile.lock?

FreeTDS has nothing to do with Rails. It is a system dependency like libXML, postures extensions, etc. Mot people on Darwin/Macs install it with Homebrew. Ubuntu is normally a manual install. For example, I install OpenSSL & FreeTDS using these scripts for Ubuntu on our CI setup. https://github.com/rails-sqlserver/tiny_tds/tree/master/test/bin

>  It is something to do with that row number, not the values in that row.

Are you using TinyTDS low level code or Rails model code? Is there anyway you can give me an example of what your doing so I can debug?

**Comment by metaskills** [comment]
Closing issue due to age, but please reply back with new info and we can re-open.
