### ISSUE TITLE
Bulk Insert performs multiplied insert

### ISSUE THREAD

**Issue by sithara** [rails-sqlserver/tiny_tds#364]
Have been noticing this issue for long - it does not happen regularly though only when I add the script to the cron - the bulk insert performs itself n times

Meaning if 7k records were to be saved to the database, I get 7k *  n records saved

Not sure whats going around. I'm using azure sql server
I also tried using bulk_insert , still I get the issue. I'm trying to save 60k records in a stretch

Kindly help

**Comment by metaskills** [comment]
I need your help to reproduce this. Would you be able to provide example SQL and or Ruby to reproduce the issue.

**Comment by metaskills** [comment]
Closing this issue. But please do respond with more info if it becomes present.
