### ISSUE TITLE
Windows Server 2012 SQL 2016 tiny_tds error

### ISSUE THREAD

**Issue by markwintch** [rails-sqlserver/tiny_tds#366]
I get the following error when using tiny_tds 0.7.0 or 0.6.2.  "0.6.2" was in the original gemfile, after researching this issue I saw a post that said 0.7.0 would work with Windows.

C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/tiny_tds-0.7.0-x64-mingw32/lib/tiny_tds/client.rb:74:in `connect': Adaptive Server connection failed (TinyTds::Error)

c:\inetpub\wwwroot\redmine>tsql -c
C:/Ruby22-x64/bin/tsql:23:in `load': cannot load such file -- C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/tiny_tds-0.7.0-x64-mingw32/bin/tsql (LoadError)
        from C:/Ruby22-x64/bin/tsql:23:in `<main>'

I am guessing that means an error stemming from freetds, but as this is Windows I thought freetds was precompiled.

I am not a developer, so I apologize if my vernacular is off.  I will do what I can to answer any questions for troubleshooting.

**Comment by metaskills** [comment]
So common issues with `Adaptive Server connection failed (TinyTds::Error)` are things like wrong configs like host, port, username, ensuring you have TCP connections on SQL Server, etc.

**Comment by markwintch** [comment]
Thank you Ken.  I will look into that now.
