### ISSUE TITLE
Randomly getting: "TinyTds::Error: Cannot insert the value NULL into column 'created_at'

### ISSUE THREAD

**Issue by munirehmad** [rails-sqlserver/tiny_tds#367]
I am experiencing a very weird error and have been trying to debug it for weeks now. 

Randomly our create record calls start failing, and always same issue, created_at is not being set. While it should be. You can see below, in the insertion hash there's no value for created_at, update_at when it should be set automatically. 

`"TinyTds::Error: Cannot insert the value NULL into column 'created_at', table 'cnhi_server.dbo.quotes'; column does not allow nulls. INSERT fails.: EXEC sp_executesql N'INSERT INTO [quotes] ([quote_no], [brand_id], [dealer_party_id], [is_quick_quote], [is_lease], [delivery_date], [total_invoice_amount], [fee_amount], [financed_amount], [rv_amount], [rv_percentage], [interest_rate], [term_months], [payment_frequency_id], [is_arrear], [cash_deposit], [trade_in], [payout], [balloon_percentage], [balloon_amount], [gst_payment_month], [finance_type], [payment_type], [structure_info], [gst_amount], [user_id], [repayment_amount], [rent_per_month]) OUTPUT INSERTED.[id] VALUES (@0, @1, @2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18, @19, @20, @21, @22, @23, @24, @25, @26, @27)', N'@0 bigint, @1 int, @2 int, @3 bit, @4 bit, @5 datetime, @6 decimal(18,5), @7 decimal(18,5), @8 decimal(18,5), @9 decimal(18,5), @10 decimal(18,5), @11 nvarchar(4000), @12 int, @13 int, @14 bit, @15 decimal(18,5), @16 decimal(18,5), @17 decimal(18,5), @18 decimal(18,5), @19 decimal(18,5), @20 int, @21 int, @22 int, @23 nvarchar(max), @24 nvarchar(4000), @25 int, @26 nvarchar(4000), @27 nvarchar(4000)', @0 = 170418124610, @1 = 1, @2 = 1, @3 = 1, @4 = 0, @5 = '04-18-2017 00:00:00.0', @6 = N'1567.0', @7 = N'2500.0', @8 = N'3967.0', @9 = N'396.7', @10 = N'10.0', @11 = N'3', @12 = 23, @13 = 5, @14 = 0, @15 = N'56.0', @16 = N'56.0', @17 = N'12.0', @18 = N'10.0', @19 = N'396.7', @20 = 0, @21 = 0, @22 = 1, @23 = N'---\n-`

When succesfully created (most of the time) records have proper created_at and updated_at values in the creation hash, as they should be. You can see below, now this is problematic as this error comes randomly and created_at, updated_at keys start vanishing from inserts and then it gets fixed automatically. Please help
```

a = Asset.create asset_subtype_id: 1
  SQL (0.8ms)  USE [cnhi_server]
  SQL (0.9ms)  BEGIN TRANSACTION
  Asset Exists (1.0ms)  EXEC sp_executesql N'SELECT  1 AS one FROM [assets] WHERE [assets].[name] IS NULL  ORDER BY [assets].[id] ASC OFFSET 0 ROWS FETCH NEXT @0 ROWS ONLY', N'@0 int', @0 = 1  [["LIMIT", 1]]
  SQL (1.1ms)  EXEC sp_executesql N'INSERT INTO [assets] ([asset_subtype_id], [created_at], [updated_at]) OUTPUT INSERTED.[id] VALUES (@0, @1, @2)', N'@0 int, @1 datetime, @2 datetime', @0 = 1, @1 = '07-07-2017 12:50:37.799', @2 = '07-07-2017 12:50:37.799'  [["asset_subtype_id", 1], ["created_at", "07-07-2017 12:50:37.799"], ["updated_at", "07-07-2017 12:50:37.799"]]
  SQL (1.7ms)  COMMIT TRANSACTION
```
 

 Version: freetds v1.00.27

**Comment by metaskills** [comment]
What version of Rails are you using? ActiveRecord would be the party responsible for setting `created_at` using its timestamp module which encapsulate all the logic around dirty and when to set it. Have you investigated those behaviors and/or have you been able to write a simple test case of models that you are able to exercise which exposes the issue?
