### ISSUE TITLE
ActiveRecord::StatementInvalid (TinyTds::Error: Write to the server failed: BEGIN TRANSACTION):

### ISSUE THREAD

**Issue by Rodcompta** [rails-sqlserver/tiny_tds#370]
I'm using Windows server 2012 and [TinyTds][v1.3.0][tsql]:

I am getting the following error` ActiveRecord::StatementInvalid (TinyTds::Error: Write to the server failed: BEGIN TRANSACTION):` when I try to do
 `user = User.create({NumeroEmpregado: "999", nome: username})`
on my rails app.

**Comment by metaskills** [comment]
Sorry for the late reply. In order to help - you would need to share more information like the version of the adapter and steps to trouble shoot that the connection was working before issuing your first insert, etc. I suspect that was the issue. Perhaps a bad username or IP or something?
