### ISSUE TITLE
Support deploy to Heroku (version 2.0.0)

### ISSUE THREAD

**Issue by masonhale** [rails-sqlserver/tiny_tds#371]
When trying to deploy to Heroku using the tiny_tds gem version 2.0.0, the gem fails to install because freetds is not included in the default Heroku stack (see: https://devcenter.heroku.com/articles/stack-packages ).

I went down the route of creating a custom buildpack to install freetds so that it would be available when the later heroku/ruby buildpack ran and installed the tiny_tds gem.

However, I ran into a wall because:
1. A custom buildpack is not allowed to install into /usr/local or /opt/local
2. Based on my review of  https://github.com/rails-sqlserver/tiny_tds/blob/master/ext/tiny_tds/extconf.rb -- these are the directories searched when looking for freetds headers and libraries
3. I couldn't find a good way to pass the --with-freetds-dir parameter when building the gem via Bundler. The .bundle/config file is not allowed to be present in Heroku deploys.
4. A custom buildpack *can* export environment variables, however, so I was hoping the tiny_tds library would search the $PATH or look for a specific env var like $FREETDS_DIR if set.

I couldn't get any of the above to work, so I retreated to deploying with tiny_tds version 1.3.0, which installed fine with no custom buildpack.

**Comment by coderjoe** [comment]
While it's possible to make this work by twiddling with library load paths using standard environment variables used while building running, a simpler solution is probably a good idea.

This feature used to be there but was removed during the build refactor. Adding it back shouldn't be hard.

**Comment by kiddrew** [comment]
In the mean time, can we downgrade to a previous version to get it to work? I need to connect to SQL Server from Azure (unfortunately) so I need to find a solution.

**Comment by masonhale** [comment]
@kiddrew You can specify version 1.3.0 of tiny_tds in your Gemfile to avoid this issue.

After change @codejoe is working on is done, will still require someone to create a custom build pack to install the the freetds library that tiny_tds relies on. The requested change will make it easier to tell the tiny_tds gem where to find the freetds libs and headers for its own compilation.

**Comment by kiddrew** [comment]
Awesome, thanks!

**Comment by metaskills** [comment]
Can you test v2.1.0.pre1 too? I think this has the work needed to support the custom build pack.

**Comment by metaskills** [comment]
Closing this issue with the thinking that `v2.1.0.pre1` or `pre2` solves this issue with `FREETDS_DIR` env var. Please reply back if not or there is more we can do.

**Comment by thibaudgg** [comment]
@metaskills I'm just trying it (using [heroku-buildpack-apt](https://github.com/heroku/heroku-buildpack-apt)) but I'm not sure which value to set for `FREETDS_DIR`. Could you please share what you have set?

**Comment by thibaudgg** [comment]
@coderjoe masonhale @kiddrew which freetds path are you using on Heroku?

I used the [apt buildpack](https://elements.heroku.com/buildpacks/heroku/heroku-buildpack-apt) to install the following packages:

```
unixodbc
unixodbc-dev
tdsodbc
freetds-common
freetds-dev
freetds-bin
```

and used the `2.1.0.pre3` version of `tiny_tds`. I tried many `FREETDS_DIR` values, but I still get the `*** extconf.rb failed ***` error message.

**Comment by masonhale** [comment]
Sorry, I abandoned my attempt at a build pack once I realized reverting to previous tinytds version avoided the issue. My need for tinytds was short-lived. That project has already launched and wrapped up. I don't have any more details to share.

**Comment by coderjoe** [comment]
@thibaudgg I don't use heroku, I just ported some code that was refactored away into the current code base. The path should be set to whatever the root path is of your freetds include/lib paths.

If freetds is installed in /usr/local/freetds/include and /usr/local/freetds/lib then the environment variable should be set to /usr/local/freetds.

Where does the apt package freetds-dev and freetds-bin install its sources and libraries? I don't have either of those packages on my system so I can't debug it.

**Comment by thibaudgg** [comment]
Thanks for your feedback @masonhale @coderjoe, I ended up using another buildpack: https://github.com/amHealth/heroku-buildpack-freetds.git that one is also setting `FREETDS_DIR` and works like a charm. 👌

**Comment by metaskills** [comment]
## GO HERE

https://github.com/rails-sqlserver/heroku-buildpack-freetds

**Comment by RickEaton** [comment]
On Heroku, using TinyTDS 2.1.2 on Rails 5.2, I am unable to get the buildpack problem resolved. I have buildpack https://github.com/rails-sqlserver/heroku-buildpack-freetds#v1.1.2 followed by ruby, specified as buildpacks. The deploy to Heroku fails with:

An error occurred while installing tiny_tds (2.1.2), and Bundler cannot continue. Make sure that `gem install tiny_tds -v '2.1.2' --source 'https://rubygems.org/'` succeeds before bundling. In Gemfile: tiny_tds.

Any help in understanding how to get this to work would be greatly appreciated!
