### ISSUE TITLE
After installing tiny_tds, the command tsql fails with an implicit conversion error

### ISSUE THREAD

**Issue by coderjoe** [rails-sqlserver/tiny_tds#374]
While testing #346 I found that `tsql` fails with the following error in 2.1.0.pre1:

```
root@freetds-test:~# tsql -C
[TinyTds][v2.1.0.pre1][tsql]: 
/var/lib/gems/2.3.0/gems/tiny_tds-2.1.0.pre1/bin/tsql:3:in `exit': no implicit conversion from nil to integer (TypeError)
        from /var/lib/gems/2.3.0/gems/tiny_tds-2.1.0.pre1/bin/tsql:3:in `<top (required)>'
        from /usr/local/bin/tsql:23:in `load'
        from /usr/local/bin/tsql:23:in `<main>'
root@freetds-test:~# tsql
[TinyTds][v2.1.0.pre1][tsql]: 
/var/lib/gems/2.3.0/gems/tiny_tds-2.1.0.pre1/bin/tsql:3:in `exit': no implicit conversion from nil to integer (TypeError)
        from /var/lib/gems/2.3.0/gems/tiny_tds-2.1.0.pre1/bin/tsql:3:in `<top (required)>'
        from /usr/local/bin/tsql:23:in `load'
        from /usr/local/bin/tsql:23:in `<main>'
root@freetds-test:~# tsql -H
[TinyTds][v2.1.0.pre1][tsql]: 
/var/lib/gems/2.3.0/gems/tiny_tds-2.1.0.pre1/bin/tsql:3:in `exit': no implicit conversion from nil to integer (TypeError)
        from /var/lib/gems/2.3.0/gems/tiny_tds-2.1.0.pre1/bin/tsql:3:in `<top (required)>'
        from /usr/local/bin/tsql:23:in `load'
        from /usr/local/bin/tsql:23:in `<main>'
root@freetds-test:~#
```

**Comment by coderjoe** [comment]
This seems to be because the `bin.rb` runner presumes that the tsql command will exist in the gem's exe directory. But that isn't true if we didn't build bundle and distribute it. This gets trickier since the tiny_tds gem forces the user to overwrite tsql as part of the install.

Maybe we should consider renaming the tiny_tds version of tsql to tinytds-tsql to avoid naming conflicts with the system tsql?

**Comment by metaskills** [comment]
> Maybe we should consider renaming the tiny_tds version of tsql to tinytds-tsql to avoid naming conflicts with the system tsql?

I think that is best. The main usage for these bins was `defncopy` since the SQL Server Rails adapter wanted to use this for schema structure dumps easier with Windows. But given that this utility can never replicate a true schema dumper, we should just remove both bin stubs from TinyTDS or rename them to something like `defncopy-ttds` or something. Related: https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/issues/437

**Comment by coderjoe** [comment]
Well I'd love to just remove them (deleting code is my favorite pastime), but given that the adapter depends on defncopy today I think I'm more in favor of a rename until something better can replace the tools.

**Comment by metaskills** [comment]
Closing this because #377 is happening. Doing so does not diminish what the adapter needs, it just means people will have to wire up their $PATH as needed which is always a good thing.
