### ISSUE TITLE
performance of multiple raw SQL inserts

### ISSUE THREAD

**Issue by dan-corneanu** [rails-sqlserver/tiny_tds#375]
Hello,
I am struggling with some performance issues inserting ~3000 records in a SQL server database. I've put up a test that uses `ActiveRecord::Base.connection` to execute raw insert statements and comparing the results between localhost postgresql and intranet SQL server I get a huge difference (even accounting for the fact that the SQL server is accessed via the local network).
localhost postgresql: 7839.136426098922 inserts / s
intranet SQL server:  509.03529467857027 inserts / s

I need to figure out if this difference is solely due to the network latency or is there something else that slows it down. Any advice on how to investigate this is highly appreciated.

Here is a link to the test code that I am using
https://gist.github.com/dan-corneanu/c446ce2af9d5c8aab008a8d426a95e63

My current setup is
```
ruby-2.2.0@omfg Dans-MacBook-Pro:omfg cdan$ tsql -C
[TinyTds][v2.0.0][tsql]: /usr/local/bin/tsql
Compile-time settings (established with the "configure" script)
                            Version: freetds v1.00.48
             freetds.conf directory: /usr/local/Cellar/freetds/1.00.48/etc
     MS db-lib source compatibility: no
        Sybase binary compatibility: no
                      Thread safety: yes
                      iconv library: yes
                        TDS version: 7.3
                              iODBC: no
                           unixodbc: no
              SSPI "trusted" logins: no
                           Kerberos: no
                            OpenSSL: yes
                             GnuTLS: no
                               MARS: no
ruby-2.2.0@omfg Dans-MacBook-Pro:omfg cdan$
```

I am running the ruby code on macOS Sierra and using
```
activerecord-sqlserver-adapter (4.2.10)
tiny_tds (2.0.0)
freetds v1.00.48
SQL Server 12.0.2569 on a Windows Box
```

Pinging the windows box from the macOS box shows
```
ruby-2.2.0@omfg Dans-MacBook-Pro:omfg cdan$ ping 10.0.5.79
PING 10.0.5.79 (10.0.5.79): 56 data bytes
64 bytes from 10.0.5.79: icmp_seq=0 ttl=128 time=0.540 ms
64 bytes from 10.0.5.79: icmp_seq=1 ttl=128 time=0.458 ms
64 bytes from 10.0.5.79: icmp_seq=2 ttl=128 time=0.606 ms
64 bytes from 10.0.5.79: icmp_seq=3 ttl=128 time=0.659 ms
64 bytes from 10.0.5.79: icmp_seq=4 ttl=128 time=0.607 ms
64 bytes from 10.0.5.79: icmp_seq=5 ttl=128 time=0.546 ms
64 bytes from 10.0.5.79: icmp_seq=6 ttl=128 time=0.458 ms
^C
--- 10.0.5.79 ping statistics ---
7 packets transmitted, 7 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 0.458/0.553/0.659/0.071 ms
ruby-2.2.0@omfg Dans-MacBook-Pro:omfg cdan$
```

Regards,
Dan

**Comment by metaskills** [comment]
I suspect what you may be seeing is a low level per issue in the 4.2 adapter, maybe around #insert which scans SQL for identity inserts. May I suggest you redo your test script to work at higher level of ActiveRecord and running theses test again. The script would:

* Establish a connection
* Create a simple schema w/table and columns.
* Make a simple `Fill` to that new table.
* Benchmark 3000 times doing a simple `Fill.create(attributes)`

Doing it this way would allow us to share this test script and work for everyone and we can even use `gem` statements at the top that wold target a specific version of the adapter. Sound cool to you?

**Comment by dan-corneanu** [comment]
@metaskills Sure, I'll redo my test script.

In the meantime I'll add a few more clues that might help.
1. From the `Benchmark`'s output I tend to believe that most of the time is wasted on waiting on something.
```
              user     system      total        real
order.fills => 0
Sample 1  1.280000   0.870000   2.150000 (  9.474415)
order.fills => 3000
order.fills => 0
Sample 2  1.130000   0.760000   1.890000 (  4.808378)
order.fills => 3000
order.fills => 0
Sample 3  1.130000   0.750000   1.880000 (  4.874679)
order.fills => 3000
order.fills => 0
Sample 4  1.120000   0.740000   1.860000 (  4.812661)
order.fills => 3000
order.fills => 0
Sample 5  1.120000   0.760000   1.880000 (  4.805358)
order.fills => 3000
>total:   5.780000   3.880000   9.660000 ( 28.775491)
>avg:     1.156000   0.776000   1.932000 (  5.755098)
Inserting 3000 fills tx: 521.276934955105 inserts / s
```
how else can I explain the difference between **total** and **real** time?

2. Executing the same amount of SQL inserts inside a script that I feed directly to `tsql` via
`tsql -H **** -p 1433 -U omfg -D *** -P *** < msSQL-samples.sql > msSQL-out.csv` I could conclude that the execution time on the server was ~300ms

```
DECLARE @EndTime datetime
DECLARE @StartTime datetime
SELECT @StartTime=GETDATE()
BEGIN TRANSACTION
INSERT INTO [futures_fills] ([side], [multi_leg_reporting_type], [contract_id], [quantity], [price], [tt_username], [fill_key], [transact_time], [order_id], [created_at], [updated_at]) OUTPUT INSERTED.[id] values (50,49,3,10,100,N'123456',N'871fd6','07-30-2017',1,'07-30-2017','07-30-2017')
-- another 2999 inserts
COMMIT TRANSACTION
SELECT @EndTime=GETDATE()
--This will return execution time of your query
SELECT DATEDIFF(MILLISECOND,@StartTime,@EndTime) AS [Duration in millisecs]
GO
```

**Comment by dan-corneanu** [comment]
https://gist.github.com/dan-corneanu/c446ce2af9d5c8aab008a8d426a95e63
@metaskills is this what you you had in mind?

**Comment by metaskills** [comment]
More something like this: https://gist.github.com/metaskills/f8a7e0ee2e7f5abeac70a14afc478816

I thought it was important to get a high level difference which looks about what I expect and see when I run the adapter test. It is important that this test is just that, an adapter test. This could be rewritten to use the low level pg/tinytds raw connections to get more insight into what each C extension is doing. I'd be curious of those results. A few things about your benchmark.

Are you really doing bulk inserts? It looked more like you were doing 1500 inserts in one transaction and maybe SQL Server is not that good at that? Is it your intention to benchmark the low level connection or adapters? I know that the SQL Server adapter could have a few more perf fixes, I already got most of the low hanging fruit... but maybe there is a spot I missed?

**Comment by dan-corneanu** [comment]
> Are you really doing bulk inserts? It looked more like you were doing 1500 inserts in one transaction and maybe SQL Server is not that good at that? 

That is my last option for getting better performance. However, I though I might be able to do something to speed things up before I move to bulk inserts.

> Is it your intention to benchmark the low level connection or adapters? I know that the SQL Server adapter could have a few more perf fixes, I already got most of the low hanging fruit... but maybe there is a spot I missed?

I was just curios where the loss of performance might come from. So I guess I am interested in both. I was hoping that I've made some silly mistake and maybe there is something easy like a configuration parameter or something that I might have missed.

**Comment by metaskills** [comment]
I'd be interested in knowing how a raw PG connection competes with TinyTDS. That gist could be changed to make the fill table have a few very few basic rows and the SQL could be hand formatted and simple inserts via the raw connection. That would give us a baseline before making any assumptions. 

> I was just curios where the loss of performance might come from.

In the adapter? It could be so many places and go all the way to the DB and implementation unique to us. You can search some of the old issues. I remember Rails v5 I did a lot of work to remove complexity. Things like SQL string scanning to tell if an identity insert was needed to removing our schema cache hacks (https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/pull/572) and such. More examples here https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/pull/536

If you got the time and interest, it would be fun to find anything else.

**Comment by dan-corneanu** [comment]
> In the adapter? It could be so many places and go all the way to the DB and implementation unique to us. 

That was my first suspicion but then I've tried some raw SQL and did some profiling on it and found out that 97% of the time was spent in `TinyTds::Result#do` which makes me think that it might actually be in the native libraries. Please correct me if I am wrong.

**Comment by metaskills** [comment]
> TinyTds::Result#do

I think that is a false lead since what you appear to be doing is waiting on SQL Server for a batch transaction. You can tho make more discreet (like the raw connection one mentioned above) and find out.

**Comment by metaskills** [comment]
Still interesting in learning about the results of these tests.
