### ISSUE TITLE
tsql is working but in test.rb the tiny_tds always undefined method "connect" in ruby-2.4.1

### ISSUE THREAD

**Issue by ajignacio** [rails-sqlserver/tiny_tds#376]
I access the table in tsql and it is work
>tsql -S server-sql01 -U username -P pw -D database
and it's work
but when in the tiny_tds

require 'tiny_tds'
client = TinyTds::Client.new(username: "username", password: "pw", host:  "data.server.net", azure: true)

i got error 
>client.rb:54:in 'initialize':undefined method 'connect' for #<TinyTds::Client:0x00000002664b60> (NoMethodError)

**Comment by metaskills** [comment]
What version of TinyTds are you using?
