### ISSUE TITLE
Can't install tiny_tds

### ISSUE THREAD

**Issue by arthurbailao** [rails-sqlserver/tiny_tds#378]
FTP is down?
```bash
/usr/local/lib/ruby/2.3.0/net/ftp.rb:243:in `initialize': getaddrinfo: Name or
service not known (SocketError)
```

**Comment by arthurbailao** [comment]
F

**Comment by ssxenon01** [comment]
FTP is still down ?

**Comment by coderjoe** [comment]
I can download from the FTP as of the timestamp on this comment. Are you still having issues?

**Comment by ssxenon01** [comment]
Thanks it's up and now working.
I forked and used s3 as download source as a workaround for this until server up.
