### ISSUE TITLE
cant download ftp://ftp.freetds.org/pub/freetds/stable/freetds-1.00.21.tar.gz

### ISSUE THREAD

**Issue by joseschmidt** [rails-sqlserver/tiny_tds#380]
Guys - 

I'm having a hard time trying to either donwload the file directly from the FTP (requests username/password) or with wget (connection refused)

Is this temporary or i'm i missing something?

**Comment by coderjoe** [comment]
Works great for me as of right now.

Their FTP uses anonymous login, maybe that's what you're experiencing? Use the username "anonymous" and your e-mail address as the password (or really anything). Or use an FTP client that supports anonymous login and let it do it for you.

**Comment by coderjoe** [comment]
Also in the future, please consider posting these questions to the FreeTDS project at https://github.com/FreeTDS/freetds. Maybe it will encourage them to improve their tarbal/binary distribution method.
