### ISSUE TITLE
TinyTds::Error: The target table 'COMMENT' of the DML statement cannot have any enabled triggers if the statement contains an OUTPUT clause without INTO clause.

### ISSUE THREAD

**Issue by bunnrf** [rails-sqlserver/tiny_tds#385]
Started getting this error today on Sierra 10.12.6 with freetds v1.00.24, gem version 1.3.0

    TinyTds::Error: The target table 'COMMENT' of the DML statement cannot have any enabled 
    triggers if the statement contains an OUTPUT clause without INTO clause.

The error occurs when when attempting a `create`, which generates the following SQL logged from the server:

    Sequel::TinyTDS::Database (15.1ms)  BEGIN TRANSACTION
    Sequel::TinyTDS::Database (0.1ms)  INSERT INTO [COMMENT] ([USERID], [TEXT], [CREATEDATE], [CHANGEDATE]) OUTPUT [INSERTED].* VALUES (2277, N'comment', '2017-09-07T16:28:30.031', '2017-09-07T16:28:30.031')
    Sequel::TinyTDS::Database (17.3ms)  IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
    Completed 500 Internal Server Error in 129ms (Views: 0.3ms | Models: 32.7ms)

Seems like this is a TinyTds issue to me because the error complains that there's no INTO clause while there clearly is.

It's possible (using the Sequel gem) to `create` without the output clause, which works but requires a subsequent query to get the created record back.

Any help would be appreciated. Is this really even a TinyTds error?

**Comment by metaskills** [comment]
I don't think this is a TinyTDS issue. Seems like you have at trigger on a table and the default SQL generated by the ActiveRecord adapter for the insert is not compatible with that single table's setup. Might be worth it to Google that error more to see if this is something you can change on the schema from your end. If not, perhaps look into using the adapter's `use_output_inserted` setting to false and it would fall back to `SELECT CAST(SCOPE_IDENTITY() AS bigint) AS Ident`. You can test all this in SMS too.

**Comment by metaskills** [comment]
https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/pull/595

**Comment by metaskills** [comment]
Closing as v5.1.2 of the adapter addressed this issue.
