### ISSUE TITLE
LoadError: cannot load such file -- tiny_tds

### ISSUE THREAD

**Issue by geeshans** [rails-sqlserver/tiny_tds#386]
I'm trying to use the tiny_tds to connect to a MS SQL with Dashing widget.  I run into below error when trying to start my job. 

> /root/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thin-1.6.4/lib/thin/server.rb:107: warning: constant ::Fixnum is deprecated
> bundler: failed to load command: thin (/root/.rbenv/versions/2.4.1/bin/thin)
> LoadError: cannot load such file -- tiny_tds

The gem is already installed. 

> [root@localhost todo]#  gem list | grep tiny_tds
> tiny_tds (2.0.0)
> 
> [root@localhost todo]# tsql -C
> [TinyTds][v2.0.0][tsql]: /usr/bin/tsql
> Compile-time settings (established with the "configure" script)
>                             Version: freetds v0.95.81
>              freetds.conf directory: /etc
>      MS db-lib source compatibility: yes
>         Sybase binary compatibility: yes
>                       Thread safety: yes
>                       iconv library: yes
>                         TDS version: 4.2
>                               iODBC: no
>                            unixodbc: yes
>               SSPI "trusted" logins: no
>                            Kerberos: yes
>                             OpenSSL: no
>                              GnuTLS: yes
> 
> [root@localhost todo]# yum list freetds*
> Loaded plugins: fastestmirror, langpacks
> Loading mirror speeds from cached hostfile
>  * base: ftp.iitm.ac.in
>  * epel: epel.mirror.angkasa.id
>  * extras: ftp.iitm.ac.in
>  * updates: ftp.iitm.ac.in
> Installed Packages
> freetds.x86_64                                                    0.95.81-1.el7                                              @epel
> freetds-devel.x86_64                                              0.95.81-1.el7                                              @epel
> Available Packages
> freetds-doc.noarch                                                0.95.81-1.el7                                              epel
> [root@localhost todo]#

I don't have much experience working with Ruby so please let me know if you need further information.

**Comment by geeshans** [comment]
The issue was due to not adding 'tiny_tds' to the Gemfile ( I have added it to Gemfile.lock by mistake). Adding the gem and running 'bundle install' resolved the issue.

> [root@localhost todo]# bundle info tiny_tds
>   * tiny_tds (2.0.0)
>         Summary: TinyTDS - A modern, simple and fast FreeTDS library for Ruby using DB-Library.
>         Homepage: http://github.com/rails-sqlserver/tiny_tds
>         Path: /root/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/tiny_tds-2.0.0
>

**Comment by metaskills** [comment]
Thanks for following up!
