### ISSUE TITLE
Create a debugging tool for common issues relating to loading tiny_tds.so

### ISSUE THREAD

**Issue by coderjoe** [rails-sqlserver/tiny_tds#389]
This gem is fairly complicated to set up since on POSIX systems it requires a fully functioning freetds install, and on windows it may or may not require different devkit based on the rubyinstaller version, as well as the architecture.

We should probably create a simple ruby script bundled with the gem `tinytds-troubleshoot` which inspects the environment and reports on potential problems to the user while also providing potential remedies.

If it is low impact enough it may even be able to be run automatically in the event of a library load failure to provide a developer instant issue resolution.

**Comment by metaskills** [comment]
Hmmm... we do always need more info. But I wonder what is the best way. If we did a bundled bin/script, then we would be reliant on first getting people on a version that had that to report info and our troubleshooting would be coupled to gem releases. Maybe we can clean up the ISSUE TEMPlATE a bit to be WAY MORE SPECIFIC. What do you think? This file is shown when creating issues.

https://github.com/rails-sqlserver/tiny_tds/blob/master/ISSUE_TEMPLATE.md

**Comment by coderjoe** [comment]
Hmm I think you might be right. Would you like me to take a stab at
updating the ISSUE_TEMPLATE.md to include steps for windows users facing
the cannot load tiny_tds.so problem? Should I maybe collect troubleshooting
steps for that into a common markdown file and just reference that from the
ISSUE_TEMPLATE and README?

**Comment by metaskills** [comment]
Sounds good to me.
