### ISSUE TITLE
lazy loading large datasets

### ISSUE THREAD

**Issue by mccmoses** [rails-sqlserver/tiny_tds#393]
I've followed the instructions and everything works great for smaller datasets, but one of the datasets is too big.

Below are instructions on using result to lazy load the data, but it still takes ten minutes.

I wonder if the problem is that I am executing stored procedures rather than accessing tables.  Here's my model:

class sproc_xxxxxxxxxxx < DataSource
    def self.execute
        self.execute_procedure 'dbo.sproc_xxxxxxxxxxx', 'abc', '123'
    end
end

Is there a better implementation in general?  
Is the execution of a stored procedure able to lazy load?  (I've tried to capture it in a result, and it still takes too  long time to get past the execution)
Is there a parameter I can pass to limit the returned recordset to a particular range?
If I need to copy the data locally, is there a recommended codeset to copy the data over?

**Comment by metaskills** [comment]
Typically if you have to process large amounts of data, you would select batches via some windowing function. In general, TinyTDS should be as fast as loading data into SMS.

**Comment by aharpervc** [comment]
> Is there a better implementation in general?
Yes. Do pagination in sql. There are many ways to do this.

> Is the execution of a stored procedure able to lazy load? (I've tried to capture it in a result, and it still takes too long time to get past the execution)
What you mean by "lazy load" isn't clear. TinyTDS can read results out as they are streamed from SQL Server, if you use an iterator block. You can process the results on the fly this way, before the entire record set is completely loaded. Check the readme in this repo for examples. Whether or not this is useful depends on what SQL you are executing and what you want to do with results.

> Is there a parameter I can pass to limit the returned recordset to a particular range?
No, but you can use an iterator block to cancel reading the results at any point you choose

> If I need to copy the data locally, is there a recommended codeset to copy the data over?
I don't really understand this question. What do you mean "locally"?

**Comment by mccmoses** [comment]
metaskills,  what would be a windowing function?  something like is available in mysql, "limit 0,30" and "limit 30,60" on the sqlserver side?

aharpervc, is this also a solution for implementation on the sqlserver side?

I don't have access to the server.

As far as "lazy load", I got the phrase from the readme file.

"result = client.execute("SELECT * FROM [datatypes]")
...
Calling #each on the result will lazily load each row from the database.

result.each do |row|
  # By default each row is a hash.
  # The keys are the fields, as you'd expect.
  # The values are pre-built Ruby primitives mapped from their corresponding types.
end"

I think this is what you mean by iteration block.  But when I tried it, the server takes just as long to return the results when called this way.

As far as copying the data locally, I mean that the server is remote, managed by someone else.  By copying it locally, I mean copying it into a table on my server or caching it.

One reason I though that there might be a better way is that the result set that I am getting back from my implementation is a hash and not an active record object.  I did not know if my implementation had short circuited active record lazy loading.

**Comment by metaskills** [comment]
If you are in Rails and the SQL Server adapter, it uses the batches interfaces (https://github.com/customink/rails/blob/master/activerecord/lib/active_record/relation/batches.rb) and each adapter does limit/offset differently. If you dont want to use Rails, then doing the SQL to window/batch results is up to you.
