### ISSUE TITLE
undefined symbol: dbanydatecrack

### ISSUE THREAD

**Issue by brodjustice** [rails-sqlserver/tiny_tds#396]
## Before submitting an issue please check these first!

* On Windows? If so, do you need devkit for your ruby install?
On Debian 9
* Using Ubuntu? If so, you may have forgotten to install FreeTDS first.
Have installed freeTDS 1.00.70 from source
* Are you using FreeTDS 0.95.80 or later? Check `$ tsql -C` to find out.
```
Compile-time settings (established with the "configure" script)
                            Version: freetds v1.00.70
             freetds.conf directory: /usr/local/etc
     MS db-lib source compatibility: no
        Sybase binary compatibility: no
                      Thread safety: yes
                      iconv library: yes
                        TDS version: 7.3
                              iODBC: no
                           unixodbc: no
              SSPI "trusted" logins: no
                           Kerberos: no
                            OpenSSL: yes
                             GnuTLS: no
                               MARS: no
```
* If not, please update then uninstall the TinyTDS gem and re-install it.
Tried, made no difference
* Have you made sure to [enable SQL Server authentication](http://bit.ly/1Kw3set)?
N/A
* Doing work with threads and the raw client? Use the ConnectionPool gem?
N/A

If none of these help. Please fill out the following:

## Environment

**Operating System**
```
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.2 (stretch)
Release:	9.2
Codename:	stretch
Linux imms-dev 4.9.0-3-686-pae #1 SMP Debian 4.9.30-2+deb9u5 (2017-09-19) i686 GNU/Linux

```
**TinyTDS Version and Information**
```
# tsql -C
Compile-time settings (established with the "configure" script)
                            Version: freetds v1.00.70
             freetds.conf directory: /usr/local/etc
     MS db-lib source compatibility: no
        Sybase binary compatibility: no
                      Thread safety: yes
                      iconv library: yes
                        TDS version: 7.3
                              iODBC: no
                           unixodbc: no
              SSPI "trusted" logins: no
                           Kerberos: no
                            OpenSSL: yes
                             GnuTLS: no
                               MARS: no

# bundle show tiny_tds
/home/bl/skylar-imms-master/shared/bundle/ruby/2.3.0/gems/tiny_tds-2.1.0
```

**FreeTDS Version**

1.00.70 (but tried many others)

## Description

Please describe the bug or feature request here.

On starting the Rails environment there is a failure in the tiny_tds so, eg:
```
bundle exec rake assets:precompile
rake aborted!
LoadError: /home/<snip>/shared/bundle/ruby/2.3.0/gems/tiny_tds-2.1.0/lib/tiny_tds/tiny_tds.so: undefined symbol: dbanydatecrack - /home/<snip>/shared/bundle/ruby/2.3.0/gems/tiny_tds-2.1.0/lib/tiny_tds/tiny_tds.so
```
But this only happens on a clean debian 9. No problems at all on debian 8 or even on a raspbian (raspberry PI debian 9). So this sounds like a debian 9 configuration problem. But before I start trawling through the libraries, has anybody seen a similar problem?

**Comment by metaskills** [comment]
Hmm, this is very interesting. The `dbanydatecrack` is there in FreeTDS and should be fine. I wonder the way FreeTDS was installed or better, how TinyTDS was compiled against FreeTDS could be worth looking into. Could you use `otool` on your .so file to see what it links against?

**Comment by brodjustice** [comment]
@metaskills Many thanks, but we've now tracked it down. It turns out that the Debian 9 image had freetds-dev installed. We then installed freetds from source over the top and this somehow confused tiny_tds.
Sorry to have bothered you, I'll close this now

**Comment by metaskills** [comment]
No bother at all! Glad you got it sorted.
