### ISSUE TITLE
I've made a heroku buildpack.  Any interest in putting it in this org?

### ISSUE THREAD

**Issue by bf4** [rails-sqlserver/tiny_tds#402]
https://github.com/x-b-e/heroku-buildpack-freetds/tree/v1.0.0

I spent some not insignificant time today working on this. It builds off of how tests are run in CI in this repo and the active record one, as well as learnings from other buildpacks.  I believe I've designed it so that it should be fairly flexible.  Some of it is still a bit of voodoo though, so comments :)

For example of what's on Heroku now: https://elements.heroku.com/search/buildpacks?q=freetds

and through the magic of jq `pbpaste | jq '.results | .[] | .hits | .[] | .url'`

"https://elements.heroku.com/buildpacks/clickmechanic/heroku-buildpack-freetds"
"https://elements.heroku.com/buildpacks/mikepack/heroku-buildpack-freetds"
"https://elements.heroku.com/buildpacks/denistsuman/heroku-buildpack-freetds"
"https://elements.heroku.com/buildpacks/zerobearing2/heroku-buildpack-freetds"
"https://elements.heroku.com/buildpacks/jordan-brough/heroku-buildpack-freetds"
"https://elements.heroku.com/buildpacks/firmhouse/heroku-buildpack-ruby-freetds"
"https://elements.heroku.com/buildpacks/yagudaev/heroku-buildpack-ruby-freetds"
"https://elements.heroku.com/buildpacks/rzablit/heroku-buildpack-freetds"
"https://elements.heroku.com/buildpacks/inspectall/heroku-buildpack-ruby-freetds"
"https://elements.heroku.com/buildpacks/eltiare/heroku-buildpack-freetds"
"https://elements.heroku.com/buildpacks/cm-studios/heroku-buildpack-freetds"
"https://elements.heroku.com/buildpacks/boomerangnyc/heroku-buildpack-python-freetds-pymssql"
"https://elements.heroku.com/buildpacks/amanjain/heroku-buildpack-python-freetds-pymssql"
"https://elements.heroku.com/buildpacks/m1schka/heroku-buildpack-python"
"https://elements.heroku.com/buildpacks/erickthered/heroku-buildpack-php"

related: https://github.com/rails-sqlserver/tiny_tds/issues/226

**Comment by metaskills** [comment]
> Any interest in putting it in this org?

YES! I did the following to help with that:

* Converted `rails-sqlserver` to an org.
* Created a `Contributors` team/group.
* Added you to said group.
* Created an empty repo with group access. 
* https://github.com/rails-sqlserver/heroku-buildpack-freetds

Feel free to have at it and welcome to the team :)

**Comment by bf4** [comment]
@metaskills oh fun!

I released a `v1.1.0` today, but am still having some trouble with the dynamic linking of `tiny_tds.so` to `freetds/lib/libsybdb.so.5` when I cache the build artifact. Right now the workaround is to always build FreeTDS.  If that's good enough, then I'll start pushing here.

**Comment by bf4** [comment]
It's there now :) https://github.com/rails-sqlserver/heroku-buildpack-freetds
