### ISSUE TITLE
Switch from BigDecimal.new to Kernel.BigDecimal

### ISSUE THREAD

**Issue by jeremyevans** [rails-sqlserver/tiny_tds#409]
`BigDecimal.new` is deprecated and produces these warning messages in verbose mode on ruby 2.5: `warning: BigDecimal.new is deprecated; use Kernel.BigDecimal method instead.`  tiny_tds currently uses the C-API to call `BigDecimal.new` in `ext/tiny_tds/result.c`, you may want to consider calling `Kernel.BigDecimal` instead.

**Comment by metaskills** [comment]
Thanks for taking the time to let me know about that Jeremy. I just made this pull request that passed locally. https://github.com/rails-sqlserver/tiny_tds/pull/411

If it goes green (which it did locally) I will merge that in and also take on your other reported issue around the use_utf16 option and then get v2.1.2 released.
