### ISSUE TITLE
Update freetds version in readme

### ISSUE THREAD

**Issue by Qwertie-** [rails-sqlserver/tiny_tds#436]
I ran the commands for building freetds exactly as the readme described and it failed on the `make` step. I tried the process again but used the latest version of freetds (1.1.6) and it worked this time. It might be worth updating the readme to use a later version of freetds as the one in the readme is from 2016.

**Comment by padmick** [comment]
+1 on this 
we moved to 18.04 LTS machines recently and so needed to bump the version of freeTDS

**Comment by wpolicarpo** [comment]
Do you mind opening a PR? I see we have #432, but that might be out of date already.

**Comment by padmick** [comment]
#438 created as there is a new version compared to that PR

**Comment by wpolicarpo** [comment]
Closing this once #432 was merged. Thanks @padmick and @Qwertie-.
