### ISSUE TITLE
activerecord-sqlserver-adapter only supports MSSQL 2012

### ISSUE THREAD

**Issue by AppyCat** [rails-sqlserver/tiny_tds#440]
I am using Debian 8 with Rails 5. Am connecting to MSSQL Server on a windows VPS in the same location and network.

activerecord-sqlserver-adapter only supports MSSQL 2012. Upgrading the db is not an option on this project.

Is it possible in Rails 5 to connect directly to MSSQL 2008 using just tiny_tds?

Thank you for any feedback or suggestions.

**Comment by KDGundermann** [comment]
Some remarks:
- Support for SQL 2008 was dropped two weeks ago by Microsoft
- Support for SQL 2008 was dropped with version  5.x of activerecord-sqlserver-adapter
  ( you may still use the 4.x version with Rails 4 )
- You may try to use Rails 5 with https://github.com/jeremyevans/sequel and tiny_tds

**Comment by AppyCat** [comment]
Thank you, using sequel with tiny_tds solves the problem.
