### ISSUE TITLE
Outdated TDS version information in README?

### ISSUE THREAD

**Issue by betelgeuse** [rails-sqlserver/tiny_tds#447]
Under the header "FreeTDS Compatibility & Configuration" README says: "We are currently having issues with passing down a TDS version with the login bit. Till we get that fixed, if you are not using a freetds.conf or a TDSVER environment variable, then make sure to use 7.1."

Later under "TinyTds::Client Usage" it says: ":tds_version - TDS version. Defaults to "7.3"."

Based on blame history besides a typo change the section "FreeTDS Compatibility & Configuration" has not been updated for many years and I assume is out of date.

**Comment by aharpervc** [comment]
Looks like the default changed [here](https://github.com/rails-sqlserver/tiny_tds/commit/d5d86c45afeb36daf2b0bf53c219906cf5f5d34c) with the switch to FreeTDS 1.0. Can you open a PR to update the readme?
