### ISSUE TITLE
TinyTDS support for SQL Server 2019

### ISSUE THREAD

**Issue by sithara** [rails-sqlserver/tiny_tds#449]
Does tinytds -v 0.7.0 running on ruby 1.9.3 support sql server -v 2019 ? 0.7.0v worked for me till sql server -v2016 but not beyond that.
My activerecord-sqlserver-adapter version is 3.2.16

**Comment by aharpervc** [comment]
Probably not, if it didn't work with 2016. But it'd be interesting to know what happened when you tried.

**Comment by sithara** [comment]
![image](https://user-images.githubusercontent.com/3234964/70768263-66772c80-1d8a-11ea-9a72-9e6165faa950.png)
 It worked for 2016 but not beyond that. Is there a workaround ?

**Comment by sithara** [comment]
Hi @aharpervc 

I tried upgrading the activerecord-sqlserver-adapter version to 3.2.18 and the app now supports sql version 2017.

![image](https://user-images.githubusercontent.com/3234964/70795048-ff2a9e00-1dc4-11ea-83b1-34ba96adcdfd.png)

Is there a patch or workaround for sql server v2019 support?

**Comment by KDGundermann** [comment]
you error is from the activerecord_sqlserver_adapter gem, TinyTDS has nothing to do with it..
so, you are still using Rails 3 ?? Why not update to Rails 5 ?

You may clone the project activerecord_sqlserver_adapter,
change the line  [sqlserver_adapter.rb#L184](https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/blob/dcbb2117515bc4c9666a1732af7c0889fb86beb5/lib/active_record/connection_adapters/sqlserver_adapter.rb#L184)
run your tests and see if you are happy ;-)

**Comment by sithara** [comment]
Thank you @KDGundermann for helping me on this :)
