### ISSUE TITLE
Client should raise error on failed execution

### ISSUE THREAD

**Issue by scbabacus-midnight** [rails-sqlserver/tiny_tds#451]
## Environment
Debian (Docker)
Image `ruby:2`

I am wondering if `execute` should raise `TinyTds::Error` on failed execution?  
See more info here:
https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/pull/717

To summarize the consumer got `false` as a return value which IMO totally unexpected.  
I wonder did you forgot to raise an error in ruby instead of returning false from the native C to the consumer?

**Comment by scbabacus-midnight** [comment]
cc @metaskills 
https://github.com/rails-sqlserver/tiny_tds/commit/2a8b8e9489f3a619e6d79e9cf8525be7f802c2bf

**Comment by aharpervc** [comment]
This seems like a plausible bug to me. Is it possible to write a new TinyTDS test case to verify the expected behavior?

**Comment by andyundso** [comment]
This has been fixed with #560 and released with v3.0.0.
