### ISSUE TITLE
repository is missing git tags for v2.1.1 and v2.1.0

### ISSUE THREAD

**Issue by PaulCharlton** [rails-sqlserver/tiny_tds#460]
this repository is missing git tags for v2.1.1 and v2.1.0
both are in the wild and referenced in CHANGELOG.md

**Comment by aharpervc** [comment]
2.1.0 is here: https://github.com/rails-sqlserver/tiny_tds/tree/v2.1.0

But I agree, 2.1.1 and 2.1.2 are missing, I assume this was an accidental oversight

**Comment by PaulCharlton** [comment]
@aharpervc is the tagging process manual, or partly automated?   seems like there should be a Gemfile.lock updated at the time of tagging so that we can get reproducible builds of a given tag.  I can do another PR and Issue for that.

**Comment by swatosh** [comment]
Just want to add 2.1.3-pre and the upcoming 2.1.3 to the list of things it'd be cool to have tags for. Thanks!

**Comment by aleksandrs-ledovskis** [comment]
@bvogelzang @aharpervc Current & recent gem's version still aren't represented as Git tags. 

Can this, please, be mitigated?

**Comment by andyundso** [comment]
I pushed the missing tags v2.1.1, v2.1.2, v2.1.3 and v2.1.4. I did not add tags for the prelease versions. Let me know if those are needed in some way.
