### ISSUE TITLE
Native extensions for windows fails in 2.1.3, leaves pacman db locked

### ISSUE THREAD

**Issue by Castone22** [rails-sqlserver/tiny_tds#479]
## Environment

**Operating System**

OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.18362 N/A Build 18362

Ruby Versions: 
ruby 2.6.6p146 (2020-03-31 revision 67876) [x64-mingw32]
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x64-mingw32]
(Tried, both, with fresh installs)

**TinyTDS Version and Information**

2.1.3

## Description

Attempting to install version 2.1.3 with `gem install tiny_tds -v '2.1.3' yields the following error logs
https://gist.github.com/Castone22/933c6c790dbe8b082a73b56234e07212

It also causes mysys' pacman db.lck to persist, after which it must be manually deleted with
ridk exec rm /var/lib/pacman/db.lck

**Comment by aharpervc** [comment]
I only pushed the Windows versions of 2.1.3 a few moments ago, can you try uninstalling the copy you have, then reinstalling? You should then get the correct copy for your platform/architecture

**Comment by Castone22** [comment]
Success!

**Comment by aharpervc** [comment]
> Success!

Glad to hear it!
