### ISSUE TITLE
tiny_tds (2.1.2) [BUG] Bus Error at 0x000001102d47a0

### ISSUE THREAD

**Issue by lovefool** [rails-sqlserver/tiny_tds#487]
tiny_tds (2.1.2) crushes on the following environment with this message. Since the production environment (Linux) uses 
ruby 2.3.1 and rails 4.2.71, I don't want to upgrade ruby to 2.4, so I can't use tiny_tds 2.1.3 or later.  The tsql CLI commands works fine. Any known issue this crash?

[Error message]
Started GET "/" for ::1 at 2021-01-20 09:58:01 +0900
/Users/xxxxx/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/tiny_tds-2.1.2/lib/tiny_tds/client.rb:60: [BUG] Bus Error at 0x000001102d47a0
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin19]

[Environment]
MacOS Big Sur 11.1 (recently updated)
FreeTDS 1.2.18 (recently updated)
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin19]
Rails 4.2.7.1

**Comment by dmexs** [comment]
I'm seeing the same after running

`
    require "tiny_tds"
    @client = TinyTds::Client.new username: username, password: pw,
        host: hostname, port: 1433, database: database, timeout: 600
`

[Stack Trace]
`
-- Control frame information -----------------------------------------------
c:0033 p:---- s:0129 e:000128 CFUNC  :connect
c:0032 p:0466 s:0125 e:000124 METHOD /Users/username/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/tiny_tds-2.1.3/lib/tiny_tds/client.rb:60 [FINISH]
c:0031 p:---- s:0120 e:000119 CFUNC  :new
c:0030 p:0077 s:0116 e:000115 METHOD /Users/username/Development/app/lib/db_adapter.rb:7 [FINISH]
c:0029 p:---- s:0110 e:000109 CFUNC  :new
c:0028 p:0052 s:0104 e:000103 METHOD /Users/username/Development/app/lib/tasks/patients_inpt_antibiotics.rake:10
c:0027 p:0105 s:0099 E:000ef0 BLOCK  /Users/username/Development/app/lib/tasks/testing.rake:17 [FINISH]
c:0026 p:0012 s:0095 e:000094 BLOCK  /Users/username/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-12.3.1/lib/rake/task.rb:271 [FINISH]
c:0025 p:---- s:0092 e:000091 CFUNC  :each
c:0024 p:0131 s:0089 e:000088 METHOD /Users/username/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-12.3.1/lib/rake/task.rb:271
c:0023 p:0152 s:0085 e:000084 BLOCK  /Users/username/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-12.3.1/lib/rake/task.rb:213
c:0022 p:0015 s:0082 e:000081 METHOD /Users/username/.rbenv/versions/2.3.3/lib/ruby/2.3.0/monitor.rb:214
c:0021 p:0030 s:0079 e:000078 METHOD /Users/username/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-12.3.1/lib/rake/task.rb:193
c:0020 p:0027 s:0073 e:000072 BLOCK  /Users/username/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-12.3.1/lib/rake/task.rb:237 [FINISH]
c:0019 p:---- s:0069 e:000068 CFUNC  :each
c:0018 p:0038 s:0066 e:000065 METHOD /Users/username/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-12.3.1/lib/rake/task.rb:235
c:0017 p:0137 s:0061 e:000060 BLOCK  /Users/username/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-12.3.1/lib/rake/task.rb:212
c:0016 p:0015 s:0058 e:000057 METHOD /Users/username/.rbenv/versions/2.3.3/lib/ruby/2.3.0/monitor.rb:214
c:0015 p:0030 s:0055 e:000054 METHOD /Users/username/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-12.3.1/lib/rake/task.rb:193
c:0014 p:0039 s:0049 e:000048 METHOD /Users/username/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-12.3.1/lib/rake/task.rb:182
c:0013 p:0038 s:0044 e:000043 METHOD /Users/username/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:160
c:0012 p:0010 s:0037 e:000036 BLOCK  /Users/username/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:116 [FINISH]
c:0011 p:---- s:0034 e:000033 CFUNC  :each
c:0010 p:0050 s:0031 e:000030 BLOCK  /Users/username/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:116
c:0009 p:0030 s:0029 e:000028 METHOD /Users/username/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:125
c:0008 p:0009 s:0025 e:000024 METHOD /Users/username/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:110
c:0007 p:0026 s:0022 e:000021 BLOCK  /Users/username/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:83
c:0006 p:0006 s:0020 e:000019 METHOD /Users/username/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:186
c:0005 p:0018 s:0016 e:000015 METHOD /Users/username/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:80
c:0004 p:0024 s:0012 e:000011 TOP    /Users/username/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-12.3.1/exe/rake:27 [FINISH]
c:0003 p:---- s:0010 e:000009 CFUNC  :load
c:0002 p:0136 s:0006 E:001ba0 EVAL   /Users/username/.rbenv/versions/2.3.3/bin/rake:22 [FINISH]
c:0001 p:0000 s:0002 E:001080 (none) [FINISH]
`

[Environment]
MacOS Big Sur (11.1)
FreeTDS (1.2.18)
tiny_tds (2.1.3) - updated from 2.1.2 and was getting the same
rails (5.1.6)

**Comment by dmexs** [comment]
Problem seems to be gone when running on Ruby 2.6.6.

**Comment by lovefool** [comment]
> Problem seems to be gone when running on Ruby 2.6.6.

Thank you for verifying this issue. I will consider to update ruby then.

**Comment by cquinterom096** [comment]
I am having the exact same issue but in my case I can't upgrade the project from ruby 2.3.4. Did you find any alternative? @lovefool

**Comment by andyundso** [comment]
I'll close this issue as we no longer provide for Ruby below v2.7. Good to know that using Ruby v2.6 solved this issue.
