### ISSUE TITLE
Getting error Sequel::DatabaseConnectionError: TinyTds::Error: Login failed for user 'username'.

### ISSUE THREAD

**Issue by poorna441** [rails-sqlserver/tiny_tds#489]
## Before submitting an issue please check these first!

* On Windows? If so, do you need devkit for your ruby install?
* Using Ubuntu? If so, you may have forgotten to install FreeTDS first.
* Are you using FreeTDS 0.95.80 or later? Check `$ tsql -C` to find out.
* If not, please update then uninstall the TinyTDS gem and re-install it.
* Have you made sure to [enable SQL Server authentication](http://bit.ly/1Kw3set)?
* Doing work with threads and the raw client? Use the ConnectionPool gem?

If none of these help. Please fill out the following:

## Environment

Windows Operating System

**TinyTDS Version and Information**

Ruby 2.5.8
Successfully installed tiny_tds (2.1.3 x64-mingw32, 2.1.2 x64-mingw32)

**FreeTDS Version**

Please provide your system's FreeTDS version. If you are using the pre-compiled
windows gem you may omit this section.

I was running this code snippet

       Sequel.connect({adapter: 'tinytds',
                        host: db_info['HOST'],
                        port: db_info['PORT'],
                        database: db_info['DATABASE'],
                        user: user_info['USERNAME'],
                        password: user_info['PASSWORD']})

and getting an error Sequel::DatabaseConnectionError: TinyTds::Error: Login failed for user 'username'.

Also ran TinyTds::Client.new(:username => 'xxxxx', :password => 'xxxx', :host => 'xxxxx', :port => 'xxxx') in IRB console, and getting the same error:
TinyTds::Error (Login failed for user 'xxxxx'.)

Can someone look into this issue and help with the solution???

**Comment by wpolicarpo** [comment]
Hi, it looks like you are using `Sequel`. TinyTDS is what Sequel uses behind the scenes to talk to SQL Server and you should probably file a bug [here](https://github.com/jeremyevans/sequel) instead.

Did you double check the credentials to make sure they are correct? Have you made sure to [enable SQL Server authentication](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/change-server-authentication-mode?redirectedfrom=MSDN&view=sql-server-ver15)?
