### ISSUE TITLE
severity 9:\nUnable to connect: Adaptive Server is unavailable or does not exist (EFSPC14)\nDB-Lib error message 20009

### ISSUE THREAD

**Issue by amitfw1** [rails-sqlserver/tiny_tds#490]
Hi

I am new to python, I am writing small program in which I need to access the database from local machine's ( EFSPC14) SQLEXPRESS server . For that I used  pymssql library and wrote the below piece of code in order to connect to SQLEXPRESS server installed on my local machine.

*import pymssql

mydbb = pymssql.connect(server ='EFSPC14\SQLEXPRESS', user='sa', password='sa123', database='PythonAutomation')*

But, when I execute this code , I got the error as shown below:

**"severity 9:\nUnable to connect: Adaptive Server is unavailable or does not exist (EFSPC14)\nDB-Lib error message 20009"**

Please advice

**Comment by wpolicarpo** [comment]
Hi, you should probably look at https://github.com/pymssql/pymssql instead. `tiny_tds` is for Ruby what `pymssql` is for Python.
