### ISSUE TITLE
FIX for `require`: libsybdb.so.5: cannot open shared object file: No such file or directory - 

### ISSUE THREAD

**Issue by pgericson** [rails-sqlserver/tiny_tds#50]
If you get the following error after `gem install tiny_tds` have successfully build the native extension:

/superpathhere/ruby/1.9.1/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:239:in `require': libsybdb.so.5: cannot open shared object file: No such file or directory - /superpaththere/ruby/1.9.1/gems/tiny_tds-0.4.5/lib/tiny_tds/tiny_tds.so (LoadError)

run this command `ldconfig /usr/local/lib`<---- for ubuntu 11.04
I have used user specific RVM

I used way too long time on this and I hope this will make it easier for someone else in the future

**Comment by reydi** [comment]
@ahoglund it was `$ /sbin/ldconfig /usr/local/lib` for me. thanks!

**Comment by ginolon** [comment]
On Heroku Cedar-14? I can do: `/sbin/ldconfig /usr/local/lib`?
