### ISSUE TITLE
Support for structure.sql seems to be broken

### ISSUE THREAD

**Issue by gucki** [rails-sqlserver/tiny_tds#502]
activerecord-sqlserver-adapter (6.1.0.0)
tiny_tds (2.1.5)

Compile-time settings (established with the "configure" script)
Version: freetds v1.2.18
freetds.conf directory: /etc
MS db-lib source compatibility: yes
Sybase binary compatibility: no
Thread safety: yes
iconv library: yes
TDS version: auto
iODBC: no
unixodbc: yes
SSPI "trusted" logins: no
Kerberos: no
OpenSSL: yes
GnuTLS: no
MARS: yes

The structure.sql (config.active_record.schema_format = :sql) generated can't be imported (rails db:setup) again. Bugs noticed so far:

- Column names are not quoted. For example the column "key" of "ar_internal_metadata" causes: ActiveRecord::StatementInvalid: TinyTds::Error: Incorrect syntax near the keyword 'key'.
- Views are not supported. Import fails with: ActiveRecord::StatementInvalid: TinyTds::Error: 'CREATE VIEW' must be the first statement in a query batch.

**Comment by aharpervc** [comment]
This seems like it's more related to the AR SQL Server adapter, so probably best to ask over there: https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/issues

**Comment by gucki** [comment]
Hmm yeah, maybe you are right. But afaik it just calls some command-line tool to generate the file, so most probably they won't be able to do anything about it (too). But I just created an issue there https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/issues/944

**Comment by Michoels** [comment]
This is still an issue in 2024.
The created `structure.sql` fails to import when running `rails db:schema:load`.

**Comment by freddy77** [comment]
Fixed in FreeTDS 1.4.12 and master branch
