### ISSUE TITLE
[URGENT] An error occurred while installing tiny_tds (2.1.7), and Bundler cannot continue in Ruby-3.2.1

### ISSUE THREAD

**Issue by sdey-mdsol** [rails-sqlserver/tiny_tds#555]
Hi Team
I am trying to install tiny_tds (2.1.7) with Ruby-3.2.1 but its getting failed:
**An error occurred while installing tiny_tds (2.1.7), and Bundler cannot continue.**
Even trying to install separately its getting below error:
gem install tiny_tds
Building native extensions. This could take a while...
ERROR:  Error installing tiny_tds:
	ERROR: Failed to build gem native extension.

    current directory: /.rvm/gems/ruby-3.2.1/gems/tiny_tds-2.1.7/ext/tiny_tds
/.rvm/rubies/ruby-3.2.1/bin/ruby -I /.rvm/rubies/ruby-3.2.1/lib/ruby/3.2.0 extconf.rb
looking for freetds headers in the following directories:
 - /opt/local/include
 - /opt/local/include/freetds
 - /usr/local/include
 - /usr/local/include/freetds
looking for freetds library in the following directories:
 - /opt/local/lib
 - /opt/local/lib/freetds
 - /usr/local/lib
 - /usr/local/lib/freetds
checking for sybfront.h... no
checking for sybdb.h... no
checking for tdsdbopen() in -lsybdb... no
checking for dbanydatecrack() in -lsybdb... no
Failed! Do you have FreeTDS 0.95.80 or higher installed?
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/.rvm/rubies/ruby-3.2.1/bin/$(RUBY_BASE_NAME)
	--help
	--with-freetds-dir
	--without-freetds-dir
	--with-freetds-include
	--without-freetds-include=${freetds-dir}/include
	--with-freetds-lib
	--without-freetds-lib=${freetds-dir}/lib
	--with-sybdb-dir
	--without-sybdb-dir
	--with-sybdb-include
	--without-sybdb-include=${sybdb-dir}/include
	--with-sybdb-lib
	--without-sybdb-lib=${sybdb-dir}/lib
	--with-sybdblib
	--without-sybdblib
	--with-sybdblib
	--without-sybdblib

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /.rvm/gems/ruby-3.2.1/extensions/x86_64-darwin-22/3.2.0/tiny_tds-2.1.7/mkmf.log

extconf failed, exit code 1

Its blocking in Production env for Ruby-3.2.1 up-gradation, please check.

**Comment by andyundso** [comment]
the error message states quite clearly what you need to do to fix this error:

`Failed! Do you have FreeTDS 0.95.80 or higher installed?`

since it appears that you are on Mac, you can get it from homebrew: `brew install freetds`.
