### ISSUE TITLE
Installing on OSX Lion

### ISSUE THREAD

**Issue by emarthinsen** [rails-sqlserver/tiny_tds#71]
Hello-

I'm struggling to get this to install on OSX Lion. The root of the problem is that iconv can't be found. Here's what I'm trying to run:

gem install tiny_tds -- --enable-iconv --with-iconv-dir=/usr/local/Cellar/libiconv/1.14

I confirmed that the directory above is present. It contains the directories bin, include, lib, and share. When I run the above command. Here is the output:

```
ERROR:  Error installing tiny_tds:
    ERROR: Failed to build gem native extension.

        /Users/ericmarthinsen/.rvm/rubies/ruby-1.9.2-p136/bin/ruby extconf.rb --enable-iconv --with-iconv-dir=/usr/local/Cellar/libiconv/1.14
checking for iconv_open() in iconv.h... no
checking for iconv_open() in -liconv... no
-----
libiconv is missing.
-----
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.

Provided configuration options:
    --with-opt-dir
    --without-opt-dir
    --with-opt-include
    --without-opt-include=${opt-dir}/include
    --with-opt-lib
    --without-opt-lib=${opt-dir}/lib
    --with-make-prog
    --without-make-prog
    --srcdir=.
    --curdir
    --ruby=/Users/ericmarthinsen/.rvm/rubies/ruby-1.9.2-p136/bin/ruby
    --enable-lookup
    --disable-lookup
    --with-iconv-dir
    --with-iconv-include
    --without-iconv-include=${iconv-dir}/include
    --with-iconv-lib
    --without-iconv-lib=${iconv-dir}/lib
    --with-freetds-dir
    --without-freetds-dir
    --with-freetds-include
    --without-freetds-include=${freetds-dir}/include
    --with-freetds-lib
    --without-freetds-lib=${freetds-dir}/lib
    --with-iconvlib
    --without-iconvlib
```

Any ideas what might be going on?

Regards,
Eric

**Comment by zhengyue** [comment]
Seeing the same as nkcfan on Yosemite, but I've found a solution. The problem is that during the gem building process, mkmf will try to look for 32 bit version of freetds, which is not available on OS X. The error message in mkmf.log said:

    ld: warning: ignoring file /usr/local/lib/libsybdb.dylib, file was built for x86_64 which is not the architecture being linked (i386): /usr/local/lib/libsybdb.dylib
    Undefined symbols for architecture i386:
      "_tdsdbopen", referenced from:
          _t in conftest-a13287.o
    ld: symbol(s) not found for architecture i386
`
So, the solution is to force it to use the 64 bit architecture:

    $ brew install freetds
    $ ARCHFLAGS="-arch x86_64" gem install tiny_tds
