### ISSUE TITLE
FreeTDS on Heroku Cedar

### ISSUE THREAD

**Issue by brian-mann** [rails-sqlserver/tiny_tds#74]
The goal of my project is to get FreeTDS working on the Cedar stack on Heroku.

While the bamboo stack does have FreeTDS installed, its an older version and it causes this problem as documented here: https://github.com/rails-sqlserver/tiny_tds/issues/54

It just so happens that my database (which I don't have control of on this project) is chock full of GUID columns which become a garbled, mangled mess.  I've tried writing some after_initialize methods in Rails to try to convert that pesky binary ASCII-8BIT output but converting to UTF-8 achieves nothing.  Therefore I've settled on the fact that I have to find a way to get FreeTDS installed on Heroku.

So far this is what I have tried... I feel I am very close so any help is much appreciated!

1) I know I have to statically compile the tiny_tds gem with the freetds and libiconv libraries baked in.  I first setup my own VM that matched the specs of heroku cedar stack, and followed the instructions on tiny_tds to create my own gem.

2) I hosted this gemfile on gemfury so it can be pushed to heroku

3) Upon creating a cedar app on heroku and pushing up, it does install tiny_tds and the sql server adapter just fine without any errors

4) However whenever the app actually tries to run (or when I drop into heroku console) I immediately get this error: 

/app/vendor/bundle/ruby/1.9.1/gems/tiny_tds-0.5.1-x86_64-linux/lib/tiny_tds.rb:16:in `require': libruby.so.1.9: cannot open shared object file: No such file or directory - /app/vendor/bundle/ruby/1.9.1/gems/tiny_tds-0.5.1-x86_64-linux/lib/tiny_tds/tiny_tds.so (LoadError)

So far these are the additional steps I've taken in troubleshooting this...

Dropping into heroku bash by running 'heroku run bash' gives me temporary access to their filesystem.  Running 'ld tiny_tds.so' returns the following info: 

```
ld: warning: libruby.so.1.9, needed by tiny_tds.so, not found (try using -rpath or -rpath-link)
ld: warning: cannot find entry symbol _start; not setting start address
```

..followed by a lot of undefined references...

running ldd on tiny_tds.so also returns this...

```
linux-vdso.so.1 =>  (0x00007fffd89ff000)
libruby.so.1.9 => not found
libpthread.so.0 => /lib/libpthread.so.0 (0x00007fb723752000)
librt.so.1 => /lib/librt.so.1 (0x00007fb72354a000)
libdl.so.2 => /lib/libdl.so.2 (0x00007fb723346000)
libcrypt.so.1 => /lib/libcrypt.so.1 (0x00007fb72310c000)
libm.so.6 => /lib/libm.so.6 (0x00007fb722e89000)
libc.so.6 => /lib/libc.so.6 (0x00007fb722b06000)
/lib64/ld-linux-x86-64.so.2 (0x00007fb723cd6000)
```

Okay so its clear that it's missing this file, and when I search heroku's file system for it, the only thing I get close to is:
    ./usr/local/lib/libruby-static.a

Now I'm not an expert in this, but I do know that Heroku statically installs their ruby versions, so perhaps that is why they only have a libruby-static.a instead of a libruby.so.1.9 

In hopes of working with this further, I did some additional tests.  

1) I forced heroku to use ruby 1.9.3-p0 and pushed again-- no difference

2) Whilst inside of heroku's bash you cannot actually create your own gem with the libraries baked in, but I was able to make and configure both freetds and libiconv by curl'ing out and prefixing to a tmp path.  I then scp'd myself the folders they created, and added those into the tiny_tds folder structure and then finished creating a new custom gem.  After pushing this gem to heroku however ends up in the exact same place as before, with no further progress... so I'm thinking really all that's preventing getting this working is linking to libruby-static.a instead of the .so file.

I poked around in the tiny_tds source but couldn't find where it determines the path of this file.  I looked through the previous closed issues and even some similar posts related to statically compiling gems into heroku.  No dice yet.

**Comment by ginolon** [comment]
Today is 2015 and still nothing? How to install TinyTDS on Heroku without pain?

**Comment by dimanyc** [comment]
@ginolon  were you able to find a solution?
