### ISSUE TITLE
Option to return DateTime instead of Time objects

### ISSUE THREAD

**Issue by Wardrop** [rails-sqlserver/tiny_tds#83]
I'd like to request a new option be added to TinyTds to allow date/datetime fields to be returned as DateTime objects instead of Time objects. This would allow libraries like Sequel which have a configurable datetime class to work as expected. The option could be added as a connection option.

**Comment by Wardrop** [comment]
@metaskills Wow, can't believe this discussion was 6 years ago. How time flies when you're having fun.

So... I've once again hit a snag with Time.

This time, there's a bug in the JSON library where it handles DateTime correctly, but spits out a less browser-compatible JSON string for Time. I'm hoping to work-around this by getting TinyTds to spit out DateTime objects instead of Time, but then I found myself back here, haha.

I still don't write C unfortunately, so any interest in implementing an option to use DateTime instead of Time?

**Comment by metaskills** [comment]
WOW! Welcome back Tom :)

Hmmm... I remember actual bugs in Rails with regard to JSON formatting of Time. Are you sure you are not hitting a Rails issue? What version are you using and have you investigated that side of the equation?

**Comment by Wardrop** [comment]
Not using rails, so can safely rule that out. Here's the problem I'm hitting with converting Time to JSON, if you're curious: https://github.com/flori/json/issues/351

I still prefer DateTime over Time however; I mean there's a reason Date and DateTime came into existence after Time's inception. I believe DateTime is only a second class citizen as to not break backwards compatibility. DateTime in most circumstances is superior I find, or at least more convenient and pleasant to use, and would love for TinyTDS to provide some option to use DateTime instead of Time.

**Comment by metaskills** [comment]
> would love for TinyTDS to provide some option to use DateTime instead of Time

For starters, I do not want to shut that idea down and remain open minded. However, my initial stance is that it seems reasonable at first... but would add risk. For example, imagine someone using TinyTDS with the Sequel gem or even ActiveRecord and filing a ticket that all the tests should pass with this config on. I would then have to make some hard calls down the way. Let's not dwell on that now and talk this thru a bit.

> Here's the problem I'm hitting with converting Time to JSON, if you're curious: flori/json#351

Totally curious! I looked over that and I wonder if this is one of those places where ActiveSupport smooth's over core Ruby for a valid reason? As an example, here is what Rails does.

```ruby
Time.now.to_json # => "\"2018-03-14T23:31:28.737-04:00\""
DateTime.now.to_json # => "\"2018-03-14T23:31:33.334-04:00\""
```

I even noticed that that project documents a compatibility to Rails' JSON implementation. Why not use that?

**Comment by Wardrop** [comment]
Well flori/json is the JSON implementation bundled with Ruby as part of the stdlib, and I generally avoid the temptation to use ActiveSupport as it often touches _too_ much, and can end up creating a whole new set of issues. I've been bitten in the past, even when only including very specific components of ActiveSupport.

As for DateTime support, indeed, you'd need to make sure that out-of-the-box, TinyTds continues to behave as it does by default. Looking at the code, there are only 5 lines that explicitly reference Time, and a couple of other instances where it timezones are referenced.

**Comment by metaskills** [comment]
>  you'd need to make sure that out-of-the-box, TinyTds continues to behave as it does by default

I think that will be easy. I'm more concerned with the n+1 features or issues after that that I have to support. Example, someone turning on DateTime in TinyTDS and expecting the adapter work. And so on and so on.

>  generally avoid the temptation to use ActiveSupport as it often touches too much, and can end up creating a whole new set of issues

Here is what I am hearing.

* You want DateTime and Time to be consistent, but Ruby is not.
* Or, you want to use one Ruby primitive vs another that fits your pattern.
* In order for your code to be simple, others need to be complex or at least take on more config.

If I think about it... one contract that ActiveSupport has done over the 6 years that I have been watching and even see them publish is they dont want to be what you described them to be. I remember years ago that concern was valid... but a lot of other work has gone into that system over the past 3 years to avoid that. As is, from simple to complex, it feels like you have a TON of options without making changes upstream to other code. Examples:

* Dep on AS and very specific require to only what you need. This is supported.
* Copy paste what is in ActiveSupport and change Ruby to do what you need it to do.
* Encapsulates your needed logic around the ruby primitives. Ex: a PORO or model extension that forces Time to DateTime prior to rendering JSON.

If all this sounds like a no go, make a pull request that changes TinyTDS and see what happens. Maybe it'll work and might have a chance to get pulled. I'll remain open till I see it. However, it could be that DateTime was not used for some crazy Ruby C & Windows reason and just maybe it will force us t revist the above. Let me know what happens.
