### ISSUE TITLE
ActiveRecord Timeout Ignored When Using TinyTDS

### ISSUE THREAD

**Issue by jlaskowski** [rails-sqlserver/tiny_tds#84]
I am running a Rake task under Rails 3.1.4, Ruby 1.9.3.  I am using tiny_tds (0.5.1 x86-mingw32).

Each time I run the rake task, I get a connection timeout on the same line of code.  Printing a timestamp to the console before the line executes and as soon as the rescue block is entered, I can see that 6 seconds have transpired.  Adding either of these lines to the database.yml didn't change it from 6 seconds:

timeout : 25
timeout: 25000

Also, when I execute the SQL using a different SQL Server client, it completes successfully in 5.4 seconds.

Here's the exception, https://gist.github.com/2908008

**Comment by attilahorvath** [comment]
Sorry to resurrect this old thread, I was just curious if it's still impossible to set the timeout on a per-connection basis.

It seems this feature has landed in FreeTDS in the meantime (https://github.com/FreeTDS/freetds/commit/33fa016ca933ea5534007bce69c10e657e92e653) but according to my tests TinyTDS is not taking advantage of it yet.

Would it be possible to implement this feature now? I'm happy to help get it working.

**Comment by attilahorvath** [comment]
It was actually easy to track this down, so I've submitted a PR for this: https://github.com/rails-sqlserver/tiny_tds/pull/348.
